### ISSUE TITLE
Preloader cannot run

### ISSUE THREAD

**Issue by Lighty0226** [BepInEx/BepInEx#107]
**Describe the bug**
The preloader does not start, so it just launched vanilla RoR2 and not a modded build.

**To Reproduce**
For me, I just need to launch the game.

**Expected behavior**
I expected the mods to run, yet the preloader cannot launch.

**Screenshots and logs**
![Annotation 2020-02-20 113633](https://user-images.githubusercontent.com/60712471/74925943-67a18700-53d5-11ea-9bc6-786eb45609bd.png)

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: RoR2, December update (can't find numerated version)
 - BepInEx version [e.g. 4.0]: 5.0.0

**Additional context**
N/A

**Comment by bbepis** [comment]
This is a MonoMod version mismatch.

Make sure you download the latest BepInEx pack for Risk of Rain 2:
https://thunderstore.io/package/bbepis/BepInExPack/
