### ISSUE TITLE
Cannot load mods on HunieCamStudio

### ISSUE THREAD

**Issue by GamingTVreal** [BepInEx/BepInEx#108]
**Describe the bug**
The bug is basically that the game won't launch with the mods I made and it gives me a text log
explaining that the installer failed

**To Reproduce**
A short description of what you did for the bug to happen.
I just followed the download instructions but I did notice I don't have a DoorStop.dll file in my HunieCam Folder

**Expected behavior**
My mods to run
**Screenshots and logs**
Include a console log (`output_log.txt` and/or `preloader_xxx_xxx.log`), if the error is visible there.  
If not possible, include a screenshot of the error.

[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Error  :   BepInEx] Could not load "HCSLoader.dll" as a plugin!
[Error  :   BepInEx] Could not load "Newtonsoft.Json.dll" as a plugin!
[Error  :   BepInEx] Could not load "System.Data.dll" as a plugin!
[Error  :   BepInEx] Could not load "System.Xml.dll" as a plugin!
[Info   :   BepInEx] 0 / 0 plugins to load
[Message:   BepInEx] Chainloader startup complete

**Desktop (please complete the following information):**
 - Game and game version Hunie Cam Studio Ver.1.0.2
 - BepInEx version 5.0 

**Additional context**

**Comment by denikson** [comment]
Closing this issue as it has become old. We are releasing BepInEx 5.1 with various bugfixes related to older plugins not working. Please test with it.

If it still doesn't work, do feel free to create a new issue.
