### ISSUE TITLE
Installation instructions for Linux users

### ISSUE THREAD

**Issue by FlyingKawasaki74** [BepInEx/BepInEx#110]
Hello,

It would be very nice if you could add Linux specific steps to the installation instructions. You can copy paste the following text for that (credit to https://steamcommunity.com/app/632360/discussions/0/1747899228763759018/ ):

1. Install Protontricks https://github.com/Sirmentio/protontricks (requires Winetricks https://wiki.winehq.org/Winetricks)
2. In Terminal, run "protontricks 632360 --gui" and ignore the error msg.
3. In the GUI, choose "Select the default Wine prefix"
4. Choose "Install a Windows DLL or component"
5. Scroll down and check "winhttp" then click OK

Possible bug caused at step 1 with error at step 5:
For anyone getting a sha26sum error when trying to install winhttp: It's because you installed winetricks using apt. Instead install winetricks as follows:

cd ~/Downloads
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks
sudo mv -v winetricks /usr/local/bin

**Comment by bbepis** [comment]
Will add this to the official documentation.
Also of note is that 5.1 is planned to add support for native Linux and OSX games, so I will need to touch up documentation for those native platforms too.

**Comment by denikson** [comment]
We now have a WIP installation guide for Unix systems:
[General installation guide](https://bepinex.github.io/bepinex_docs/master/articles/user_guide/installation/index.html?tabs=tabid-win)
[Running games on Steam](https://bepinex.github.io/bepinex_docs/master/articles/advanced/steam_interop.html)
[Running games with Proton/Wine](https://bepinex.github.io/bepinex_docs/master/articles/advanced/steam_interop.html#protonwine)

The BE builds of Unix version of BepInEx will begin as soon as we merge `feature-unix-support` branch into master.

**Comment by denikson** [comment]
The branch was merged into master. As such, BE builds for Linux are available and the guides mentioned above valid. As such, I'll close the issue.

If you have problems with the guide, please create a new issue.
