### ISSUE TITLE
[Risk of Rain 2] Multiple errors, persistant stuttering.

### ISSUE THREAD

**Issue by jnchaba** [BepInEx/BepInEx#112]
**Describe the bug**
Risk of Rain 2 is stuttering every 5 seconds or so. I am playing in a lobby with 4 other people, and no one else is experiencing the same bug.

While this is occurring, BepInEx is outputting a constant stream of errors.

**To Reproduce**
I am playing Risk of Rain 2 with 4 other friends. We are using the Too Many Friends mod which allows up to 16 players in a lobby, the stats display mod, and ordered items mod also.

I am using Bep in Ex Pack v3.2.0 as obtainable through the RoR2ModManager v1.0.3, through thunderstore.io, although it appears that BepInEx is running as version 5.0.0 based on the information in the BepInEx window as it loads the game.

**Expected behavior**
I expected to be able to play the game with the mods smoothly, like my friends were able to.

**Screenshots and logs**
Include a console log (`output_log.txt` and/or `preloader_xxx_xxx.log`), if the error is visible there.  
If not possible, include a screenshot of the error.

The relevant part of the log: 

[Warning: Unity Log] [Server] function 'System.Int32 RoR2.CharacterMaster::GetKillerBodyIndex()' called on client
[Warning: Unity Log] [Server] function 'System.String RoR2.PlayerCharacterMasterController::get_finalMessageTokenServer()' called on client
[Warning: Unity Log] [Server] function 'System.Int32 RoR2.CharacterMaster::GetKillerBodyIndex()' called on client
[Warning: Unity Log] [Server] function 'System.String RoR2.PlayerCharacterMasterController::get_finalMessageTokenServer()' called on client
[Warning: Unity Log] [Server] function 'System.Int32 RoR2.CharacterMaster::GetKillerBodyIndex()' called on client
[Warning: Unity Log] [Server] function 'System.String RoR2.PlayerCharacterMasterController::get_finalMessageTokenServer()' called on client
[Warning: Unity Log] [Server] function 'System.Int32 RoR2.CharacterMaster::GetKillerBodyIndex()' called on client
[Warning: Unity Log] [Server] function 'System.String RoR2.PlayerCharacterMasterController::get_finalMessageTokenServer()' called on client
[Warning: Unity Log] [Server] function 'System.Int32 RoR2.CharacterMaster::GetKillerBodyIndex()' called on client
[Warning: Unity Log] [Server] function 'System.String RoR2.PlayerCharacterMasterController::get_finalMessageTokenServer()' called on client
[Warning: Unity Log] [Server] function 'System.Int32 RoR2.CharacterMaster::GetKillerBodyIndex()' called on client
[Warning: Unity Log] [Server] function 'System.String RoR2.PlayerCharacterMasterController::get_finalMessageTokenServer()' called on client

This loops until I close the game.

**Desktop (please complete the following information):**
 - Risk Of Rain 2 version 4811921
 - BepInEx version 5.0

**Additional context**

The logs also output this, which might be relevant?
[Info   : Unity Log] Could not load config /Config/autoexec.cfg: Could not find file "E:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\autoexec.cfg"

[Info   : Unity Log] Steamworks lobby join succeeded. Lobby id = 109775240990494917
[Info   : Unity Log] Intercepting bad or out-of-order lobby update to server id.
[Info   : Unity Log] Initiating connection to server 76561198030861191...
[Info   : Unity Log] Intercepting bad or out-of-order lobby update to server id.
[Info   : Unity Log] Intercepting bad or out-of-order lobby update to server id.

**Comment by bbepis** [comment]
The console spam can degrade performance, so I would suggest turning it off in the BepInEx/config/BepInEx.cfg config file. You can also disable the disk logging for more performance (and less disk space usage, since a volume of messages that large will make it huge).

As for stuttering, from what I understand this is an issue with the Unity engine itself not playing very well with the generated hook library that RoR2API provides, and a fix is somewhat on it's way.

In any case, it's not a BepInEx issue.
