### ISSUE TITLE
[KoiKatsu] Plugins/mods not loading

### ISSUE THREAD

**Issue by jinnous620** [BepInEx/BepInEx#117]
Hello everyone, I am new to BepInEx in general as I recently picked up the game and wanted to try some modding.  However, even following the many instructions provided by the community I couldn't get my plugins/mods to load properly in the game.

**Describe the bug**

Basically as the title implies, I've placed the BepInEx folder and the additional plugins in its respective folders, but when I run the game there's no indication of the mods or plugins loading.  I could potentially be missing some additional plugins as well but even after getting any other possible plugins I've had no luck.

**Screenshots and logs**
Include a console log (`output_log.txt` and/or `preloader_xxx_xxx.log`), if the error is visible there.  
If not possible, include a screenshot of the error.

[LogOutput.log](https://github.com/BepInEx/BepInEx/files/4640498/LogOutput.log)

These are the log output of me running the game, as stated I am not too familiar with BepInEx in general, so I do not know what I am expected to see when everything works.

**Desktop (please complete the following information):**
 - Koikatsu patch 5.0
 - BepInEx 5.0

Any help is appreciated, thank you all in advance

**Comment by ManlyMarco** [comment]
Did you resolve the issue?

**Comment by jinnous620** [comment]
Hi there thx for the email

Yes I managed to figure it out, thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
