### ISSUE TITLE
BepInEx won't run at all for me (Linux)

### ISSUE THREAD

**Issue by ThatguySteam** [BepInEx/BepInEx#120]
Won't run at all. When run manually with ./run_bepinex.sh it says:

Cannot identify executable type (got PE32+ executable (GUI) x86-64, for MS Windows)!

Creates no log or config when i try to run it.

 - Outward on steam with Proton
 - Latest version for Linux

Was following this guide: https://outward.gamepedia.com/Installing_Mods
I'm sure it's an issue just i'm having, but i have no idea what to do after hours of non-working fixes found on google.

**Comment by lordkitsuna** [comment]
I am having this same problem were you able to solve it?

**Comment by denikson** [comment]
Greetings!

Assuming you have exactly the same problem (running `run_bepinex.sh` giving `Cannot identify executable type (got PE32+ executable (GUI) x86-64, for MS Windows)!`), it means that you're trying to use BepInEx unix build on a Windows game.

Whenever trying to use BepInEx with Windows game on Wine, you need to follow **Windows installation instructions** (Outward seems to have its own, but here's also [the official BepInEx install guide](https://bepinex.github.io/bepinex_docs/master/articles/user_guide/installation/index.html?tabs=tabid-win)) and then [configure Wine to run BepInEx properly](https://bepinex.github.io/bepinex_docs/master/articles/advanced/steam_interop.html#protonwine).

I'm basing this assumption on the error given in the issue and not on the particular game in question. If you need help modding Outward, I suggest seeking the modding community, as it is able to provide more tailored help than this general issue tracker.
