### ISSUE TITLE
BepInEx can't run in the game "911 Operator"

### ISSUE THREAD

**Issue by Yan-Zero** [BepInEx/BepInEx#124]
**Describe the bug**
Hmmmm
If I open game with BepInEx,the game will log 'Object::FindAnyObjectOfType<MonoBehaviour> ()' and 'object::FindAnyObjectOfType<MonoScript> ()'.
And then,the game will start but nothing is in the game.

**To Reproduce**
I have done nothing except installing BepInEx.
I'm sure BepInEx is installed correctly,because it can work in other game.

**Expected behavior**
The game work with BepInEx.

**Screenshots and logs**
![Game](https://user-images.githubusercontent.com/32036413/87167601-cffaf180-c2ff-11ea-973d-172c43d17dc6.png)
![Log](https://user-images.githubusercontent.com/32036413/87167612-d2f5e200-c2ff-11ea-94b0-c8025e674430.png)
[output_log.txt](https://github.com/BepInEx/BepInEx/files/4903792/output_log.txt)

**Desktop (please complete the following information):**
 - Game: 911 Operator
 - Game version: 1.34.18 +FR +SR +ELM +SaR
 - BepInEx version:  5.2.0.0

**Additional context**
I have tried other version of BepInEx ,but all can't work.

**Comment by denikson** [comment]
Greetings!

Thank you for the report and all the logs! I'll check the game shortly to replicate the problem.

Meanwhile, please try to change the entrypoint as per [the troubleshooting guide](https://bepinex.github.io/bepinex_docs/master/articles/user_guide/troubleshooting.html#change-the-entrypoint-1).

**Comment by denikson** [comment]
Managed to replicate the issue. 

To fix it, please follow the guide on changing [the entrypoint to `MonoBehaviour`](https://bepinex.github.io/bepinex_docs/master/articles/user_guide/troubleshooting.html#change-the-entrypoint-1).

Please report if this solved the issue or not.

**Comment by Yan-Zero** [comment]
I'm sorry I received your message just now.

Following the guide, I succeed in fixing the problem.
BepInEx work well now.
Thanks for your help.
