### ISSUE TITLE
Game Crashed After Picking Up Elite Item

### ISSUE THREAD

**Issue by vizthex123** [BepInEx/BepInEx#125]
**Describe the bug**
I picked up the Lightning elite item, the game lagged a bunch, then crashed

**To Reproduce**
Pick up Lightning elite item then see what happens.

**Expected behavior**
I expected it not to crash

**Screenshots and logs**
Not sure if this is the right one, but it's the only one I could find
[LogOutput.log](https://github.com/BepInEx/BepInEx/files/4909787/LogOutput.log)

**Desktop (please complete the following information):**
Bep: 3.2.0
Risk of Rain 2: Whatever the latest is (Idk how to check and only got the game a week or two ago, sorry)

**Comment by denikson** [comment]
Greetings!

Thank you for providing the log and information about the issue!  
Unfortunately we cannot provide plugin-specific support here, as BepInEx is a general-purpose Unity modding framework aimed at supporting various Unity games. As such, we provide help with BepInEx-related issues, but we are not able to track issues related to specific plugin setups.

Instead, I suggest seeking help from RoR2 Modding Discord: https://discord.gg/VREqSF 
Provide them the same error log you sent here and I'm sure they will be able to solve your plugin-related problem.

I'll close this issue for now, but don't hesitate to create another should you need further help or a pointer where to get more information.
