### ISSUE TITLE
Can't call RunParallel in any other thread than the main thread

### ISSUE THREAD

**Issue by jeiea** [BepInEx/BepInEx#127]
## What I did
I called [RunParallel](https://bepinex.github.io/bepinex_docs/master/api/BepInEx.ThreadingExtensions.html#BepInEx_ThreadingExtensions_RunParallel__2_System_Collections_Generic_IEnumerable___0__System_Func___0___1__System_Int32_) in the thread created by `QueueUserWorkItem`.

## What I expected
`RunParallel` should be executed without exceptions.

## What I got
```
[Error  :    plugin] UnityEngine.UnityException: get_processorCount can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
  at (wrapper managed-to-native) UnityEngine.SystemInfo:get_processorCount ()
  at BepInEx.ThreadingExtensions+<RunParallel>d__1`2[System.Int32,<>f__AnonymousType0`2[System.Int32,System.Collections.Generic.List`1[System.Int32]]].MoveNext () [0x00000] in <filename unknown>:0 
  at BepInEx.ThreadingExtensions+<RunParallel>d__0`2[System.Int32,<>f__AnonymousType0`2[System.Int32,System.Collections.Generic.List`1[System.Int32]]].MoveNext () [0x00000] in <filename unknown>:0 
...
```

## Environment
BepInEx: *5.2*
Patcher assembly target: .net 3.5
Unity version: 2017.4.26f1

**Comment by denikson** [comment]
Greetings! Thank you for pointing this problem out and sending the stack trace!

Please test the latest Bleeding Edge build (#238) from https://builds.bepis.io/projects/bepinex_be 

From a quick test it seems to solve the problem, but please do give it a test. If it works fine, I'll close the issue.

**Comment by jeiea** [comment]
I missed notification.

I've just confirmed the issue is resolved. Feel free to close.
