### ISSUE TITLE
BepInEx 3.0

### ISSUE THREAD

**Issue by bbepis** [BepInEx/BepInEx#13]
Targets for release:

- [x] Add BepInEx version to logger
- [x] Add plugin versions to logger
- [x] Transfer plugin metadata to attributes (breaking change)
- [x] Change ID checks to a full dependency system
  - [x] Add minimum version checks for BepInEx and other plugins
- [x] Update Intellisense documentation
- [x] Update wiki documentation

**Comment by dronoketer** [comment]
could you please extend the range of the slide？just like -200~500 ？I  think maybe It is  easy to do.

**Comment by dronoketer** [comment]
and the plugins is pretty good.keep it up~

**Comment by denikson** [comment]
Old issue. Closing because it's done and to clean up issue listing.
