### ISSUE TITLE
Bepinex Error Loading Mods in Risk of Rain 2

### ISSUE THREAD

**Issue by Blu117** [BepInEx/BepInEx#131]
Description
Whenever I start the modded client of Risk of Rain 2, I get an error message which causes my game not being able to use the mods installed (MiniRpcLid and R2API fail to load which prevents StartingItemsGUI from working) and the mod not working either.

Reproduction
I installed the mods ow I was instructed on thunderstore and opened the game. the game runs fine and the starting items mod, which creates a tab on the main menu, loads fine but when i start a run the mod doesnt load in any of the items

Logs
[Message:   BepInEx] BepInEx 5.0.1.0 - Risk of Rain 2
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher methods from BepInEx.MonoMod.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :   BepInEx] 2 patcher plugin(s) loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   MonoMod] Collecting target assemblies from mods
[Info   :   BepInEx] Patching [Assembly-CSharp] with [BepInEx.MonoMod.Loader.Patcher]
[Message:   MonoMod] [Main] Scanning for mods in directory.
[Message:   MonoMod] [ReadMod] Loading mod dir: D:\SteamLibrary2\steamapps\common\Risk of Rain 2\BepInEx\monomod
[Message:   MonoMod] [ReadMod] Loading mod: D:\SteamLibrary2\steamapps\common\Risk of Rain 2\BepInEx\monomod\Assembly-CSharp.R2API.mm.dll
[Message:   MonoMod] [Main] Found 1 mods
[Message:   MonoMod] [Main] mm.PatchRefs(); fixup pre-pass
[Message:   MonoMod] [Main] mm.AutoPatch();
[Message:   MonoMod] [AutoPatch] Parsing rules in loaded mods
[Info   :BepInEx Preloader] [MonoMod] [RulesModder]
[Info   :BepInEx Preloader] [Write] Writing modded module into output stream.
[Message:   MonoMod] [AutoPatch] PrePatch pass
[Message:   MonoMod] [AutoPatch] Patch pass
[Message:   MonoMod] [AutoPatch] PatchRefs pass
[Message:   MonoMod] [PostProcessor] PostProcessor pass #1
[Message:   MonoMod] [Main] Done.
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [R2API 2.4.21]
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000316 (from typeref, class/assembly UnitySystemConsoleRedirector, )
Stack trace:
R2API.R2API..ctor () (at <76886c54bb8d48658f5df2d9fc090f74>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.SkinDef:Awake()

[Info   :   BepInEx] Loading [MiniRpcLib 1.0]
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000316 (from typeref, class/assembly UnitySystemConsoleRedirector, )
Stack trace:
MiniRpcLib.MiniRpcPlugin..ctor () (at <b2b86dbcaca64a5db30f56f5ac953f62>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.SkinDef:Awake()

[Info   :   BepInEx] Loading [StartingItemsGUI 1.1.7]
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] Network message MsgType.Highest + 22 is unregistered.
Setting breakpad minidump AppID = 632360
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198333334857 [API loaded no]

Desktop
 - Game and game version: Risk of Rain 2 Major Update 1.0 (8/11/2020)
 - BepInEx version: 3.2.0

**Comment by denikson** [comment]
Greetings!

Thank you for providing the log and information about the issue!  
Unfortunately we cannot provide plugin-specific support here, as BepInEx is a general-purpose Unity modding framework aimed at supporting various Unity games. As such, we provide help with BepInEx-related issues, but we are not able to track issues related to specific plugin setups.

Instead, I suggest seeking help from RoR2 Modding Discord: https://discord.gg/VREqSF 
Provide them the same error log you sent here and I'm sure they will be able to solve your plugin-related problem.

I'll close this issue for now, but don't hesitate to create another should you need further help or a pointer where to get more information.

**Comment by Blu117** [comment]
Thanks for the suggestion and for responding so quickly 👍
