### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by helloshorty** [BepInEx/BepInEx#132]
Game crashes without any external plugins installed (only BepInEx and R2 a PI)

Crash log:

[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [R2API 2.5.6]
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.UnitySystemConsoleRedirector.Redirect
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.DisableIfGameModded.OnEnable
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.Networking.ServerAuthManager.HandleSetClientAuth
[Debug  :     R2API] Hook added by assembly:  for: RoR2.Networking.ServerAuthManager.HandleSetClientAuth
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.SteamworksLobbyDataGenerator.RebuildLobbyData
[Debug  :     R2API] Hook added by assembly:  for: RoR2.SteamworksLobbyDataGenerator.RebuildLobbyData
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] Network message MsgType.Highest + 22 is unregistered.
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   :   Console] Facepunch.Steamworks Arch: x64
[Info   : Unity Log] Shutting down Steamworks...
[Info   : Unity Log] Shut down Steamworks.

**Comment by denikson** [comment]
Greetings!

Thank you for providing the log and information about the issue!  
Unfortunately we cannot provide plugin-specific support here, as BepInEx is a general-purpose Unity modding framework aimed at supporting various Unity games. As such, we provide help with BepInEx-related issues, but we are not able to track issues related to specific plugin setups.

Instead, I suggest seeking help from RoR2 Modding Discord: https://discord.gg/VREqSF 
Provide them the same error log you sent here and I'm sure they will be able to solve your plugin-related problem.

I'll close this issue for now, but don't hesitate to create another should you need further help or a pointer where to get more information.
