### ISSUE TITLE
Unix Stream Helper: Argument cannot be null

### ISSUE THREAD

**Issue by MinusGix** [BepInEx/BepInEx#134]
**Describe the bug**
After installing BepInEx v5.3 (later, this was tested with latest bleeding edge build #251) I receive an error saying that it failed to make the `UnixStreamHelper` due to an argument being `null`.  

**To Reproduce**
Downloaded BepInEx_unix_5.3.0.0.zip (later tried with bleeding edge #251).  
Extracted all of the files into the `~/.steam/steam/steamapps/common/Pillars of Eternity/` folder.
`chmod u+x ./run_bepinex.sh`  
Edited `run_bepinex.sh` so that: `executable_name="PillarsOfEternity"`  
`TERM=xterm ./run_bepinex.sh` to launch the game. The `TERM=xterm` line is due to if I do not have that, then I get a separate error about "Magic number is wrong: 542". Usually my `TERM` environment variable is set to `xterm-256color`.
The game launches fine, but upon exiting I see that there is a preloader log file with an error.
Attempted to mess with the config file. Enabled console, made log levels 'all'. Tried setting `StandardOutType` to both values.Tried setting `Type` to `Camera`. Also tried running as root. Tried in four separate terminals: VScode terminal, termite, xterm (xterm does not need to set `TERM`), and konsole.

**Expected behavior**
Expected it to initialize properly without errors.

**Screenshots and logs**
```
System.TypeInitializationException: An exception was thrown by the type initializer for BepInEx.Unix.UnixStreamHelper ---> System.ArgumentNullException: Argument cannot be null.
Parameter name: libraryPtr
  at MonoMod.Utils.DynDll.InternalTryGetFunction (IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x00000] in <filename unknown>:0 
  at MonoMod.Utils.DynDll.TryGetFunction (IntPtr libraryPtr, System.String name, System.IntPtr& functionPtr) [0x00000] in <filename unknown>:0 
  at MonoMod.Utils.DynDll.InternalResolveDynDllImports (System.Type type, System.Object instance, System.Collections.Generic.Dictionary`2 mappings) [0x00000] in <filename unknown>:0 
  at MonoMod.Utils.DynDll.ResolveDynDllImports (System.Type type, System.Collections.Generic.Dictionary`2 mappings) [0x00000] in <filename unknown>:0 
  at BepInEx.Unix.UnixStreamHelper..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at BepInEx.Unix.LinuxConsoleDriver.Initialize (Boolean alreadyActive) [0x00000] in <filename unknown>:0 
  at BepInEx.ConsoleManager.Initialize (Boolean alreadyActive) [0x00000] in <filename unknown>:0 
  at BepInEx.Preloader.Preloader.Run () [0x00000] in <filename unknown>:0 
```
Of note is that in my terminal it outputs:
```
Got image: 0x3414f50 
/usr/bin/uname: symbol lookup error: /home/minus/.local/share/Steam/steamapps/common/Pillars of Eternity/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen
```

**Desktop (please complete the following information):**
 - Pillars of Eternity. Latest Steam version, v3.7.0.1318. I believe PoE uses Unity 4? The game's executable is 64bit.
 - BepInEx 5.3.0, and BepInEx bleeding edge #251.

**Additional context**
Linux. Manjaro (Arch Linux).  
The game does have a System.dll, and System.Core.dll  
Based on the error location in the source code, I'd assume it is having trouble loading libc for some reason.  
I added
```
echo $LD_LIBRARY_PATH
echo $LD_PRELOAD
echo $DYLD_LIBRARY_PATH
echo $DYLD_INSERT_LIBRARIES
```
To the end (right before launching) to see the values exported:
```
/home/minus/.local/share/Steam/steamapps/common/Pillars of Eternity/doorstop_libs:
libdoorstop_x64.so:
/home/minus/.local/share/Steam/steamapps/common/Pillars of Eternity/doorstop_libs
/home/minus/.local/share/Steam/steamapps/common/Pillars of Eternity/doorstop_libs/libdoorstop_x64.so
```

**Comment by denikson** [comment]
Greetings!

Thank you for such detailed report! Thanks to it, I was able to reproduce the xterm issue and potential subsequent problem related to game using Unity 4.7.

Please try the latest Bleeding Edge build: [BepInEx_unix_a53d4d5_5.3.0.252.zip](https://builds.bepis.io/projects/bepinex_be/252/BepInEx_unix_a53d4d5_5.3.0.252.zip)

I have managed to successfully boot  BepInEx in Pillars of Eternity with the above BE on Manjaro 20.0.3. Do note that you have to [change the entrypoint](https://bepinex.github.io/bepinex_docs/master/articles/user_guide/troubleshooting.html#change-the-entrypoint-1) in order to boot into the game fully (using `Camera` is fine as you did, however it tends to be a bit too late for some plugins).

Please test the above BE and report if any issues prevail. If you still have issues with mono not detecting libc, you might need to make sure that `ldconfig` has libc listed and properly mapped to `libc.6.so`.

**Comment by MinusGix** [comment]
I am still getting the same issue (though the term issue is fixed, thanks!) with updated bepinex. (Removed all old files, and put new files in. Ran bepin sh script. Then edited generated config to enable console and set Type to 'MonoBehaviour'). I will try investigating ldconfig.
```
ldconfig -p | grep libc.so
        libc.so.6 (libc6,x86-64, OS ABI: Linux 3.2.0) => /usr/lib/libc.so.6
        libc.so.6 (ELF, OS ABI: Linux 3.2.0) => /usr/lib32/libc.so.6
```

**Comment by MinusGix** [comment]
Alright, I manually compiled the library (which was painless, thanks!) with a change. I commented out the "libc" line in UnixStreamHelper.cs, so that it would not try loading that (I do have a libc.so file, but it is a linker script which seems to be meant to load libc.so.6). I also changed the name of the list to "libc.so.6" and all the `DynDllImport("libc")`  to `DynDllImport("libc.so.6")`. That last part was likely not needed, but I just went 'why not'.
Of course this isn't  a great solution (have to go and build a custom one with "libc" commented out). If you have any ideas for fixing it on my end (or your end, but I presume it is an issue with my OS install) I would be happy to hear them. This isn't too much of an annoyance as the program is fast to build (unlike, for example, llvm).

**Comment by bbepis** [comment]
Hi,
I'm not sure if changing the `DynDllImport` attributes were necessary. It doesn't actually only attempt to load `libc`; it actually enumerates over [this mapped list](https://github.com/BepInEx/BepInEx/blob/master/BepInEx/Console/Unix/UnixStreamHelper.cs#L42) and uses the first one that `dlopen()` can successfully attach to.

Does re-arranging that list to put libc.so.6 at the top help? If not, it might be an issue with the underlying library not skipping over an error pointer returned by dlopen().

**Comment by denikson** [comment]
> Does re-arranging that list to put libc.so.6 at the top help?

Speaking of that, do you @MinusGix mind testing the version which has the ordering revised a bit?

https://builds.bepis.io/projects/bepinex_be/253/BepInEx_unix_fd656ec_5.3.0.253.zip

**Comment by MinusGix** [comment]
Okay, I rather did badly at explaining what happened fully yesterday. I blame being tired, as I climbed in bed right after posting that :)
If I ran the modified version (that I made), or the #253 version without properly modifying the config, then I get a `﻿./run_bepinex.sh: line 100:  5081 Aborted                 (core dumped) "${executable_path}"`. Though it still generates the config, so  I can then go set `Logging.Console` `Enabled = true`; `Preloader.Entrypoint` `Type = MonoBehaviour`. Then use the run_bepinex script again.
That will then start printing to the terminal and actually start running the game. There is a lot of output from Unity.  
Of note is that many of the lines (in my modified, and #253) are like:
`1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m1%{8}%<%t37%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;7%;m[Message:   BepInEx] BLEEDING EDGE Build #253 from fd656ecf529516dd1f5f9415205561751483fa24 at master` I assume that is meant to be some form of formatting, but it doesn't appear to display in my vscode terminal, termite, or konsole. It seems to work in xterm, and upon testing, if I did `TERM=xterm ./run_bepinex.sh` then the formatting would work as expected.
So the #253 build did work for me. I'm not really sure what the issue is on my end.

**Comment by bbepis** [comment]
You're correct, those are control characters for xterm consoles. I haven't implemented any code for compatibility with any terminals that don't use xterm, since it's an open-ended issue to try and support everything. I just went for what I think would encompass the widest set possible: `xterm` and `xterm-256color`.

So it's expected that setting your TERM env var to xterm fixed that. However it should also be working for `TERM=xterm-256color`. Are you using something different as a default?

**Comment by MinusGix** [comment]
Termite apparently has `xterm-termite` set as the default. I've ran into issues on termite with ssh as well, so I have been tempted to just permanently change termite's default `$TERM` variable.  
Vscode, and Konsole, says `$TERM` is xterm-256color. 
xterm of course says `$TERM` is xterm, and this is the one it works properly without messing with the `$TERM` variable.

**Comment by bbepis** [comment]
This is very strange. What encoding is your terminal using? The control characters might not be being interpreted correctly.

And out of curiosity, do you have any games running Unity 2017 or later you can test BepInEx out on with `xterm-256color`? The version of mono shipped with those engine versions have a (mostly) functional xterm implementation in them, and don't require a completely new implementation like how Unity 5.x and below does.

**Comment by MinusGix** [comment]
Of note, is that if I do `TERM=xterm-color ./run_bepinex.sh` (note that it is not `xterm-256color`) then it works fine.
I tried it with Nimbatus (I apparently don't have many unity games, but this is one that I had installed), which Bepinex says is Unity v2018.4.25f1. Color appears to work properly in the terminal for xterm-256color and for xterm-termite with this game.

**Comment by bbepis** [comment]
Thank you for the detailed information throughout this issue! We've discovered that Unity 4.7 (the version of Unity that Pillars of Eternity uses) has yet another broken TTY implementation that we were unaware of. Adding additional checks for for this test case has luckily fixed this without major changes to BepInEx.

Pull the latest changes (or use the [latest bleeding edge build](https://builds.bepis.io/projects/bepinex_be)) and try it out with `xterm-256color` again

**Comment by MinusGix** [comment]
Colors work in xterm-256color now, as well as in xterm-termite :)
Thanks! (I guess this can be closed now? Though, still not sure why it was failing to link with libc until you reordered it, but if it works, it works.)

**Comment by bbepis** [comment]
Dynamically loading libc on linux is surprisingly difficult to get working correctly. A lot of useful things like how static linking finds libraries (something that ldconfig shows) don't work as effectively. For example, you mentioning that `libc` just has a redirect to libc.so.6 works with static linking but not dynamic linking.

Glad to hear it works!
