### ISSUE TITLE
BepInEx on Linux with Wine (command line only)

### ISSUE THREAD

**Issue by dubvulture** [BepInEx/BepInEx#136]
Hi, i'm currently working on adding mod support on a [dockerized Risk of Rain 2 Dedicated Server](https://github.com/avivace/ror2-server) running on Linux with wine.

I stumbled upon your [guide](https://bepinex.github.io/bepinex_docs/master/articles/advanced/steam_interop.html?tabs=tabid-1#protonwine) on getting BepInEx to work under wine, the problem is that having to use a GUI with Docker kinda defeats the whole use case.

I tried some fiddling with `WINEDLLOVERRIDES` as you can see [here](https://github.com/avivace/ror2-server/issues/4#issuecomment-682163084]), but to no avail.
First thing that could help me is knowing if what I tried is even remotely related to what is suggested your guide.

Thanks

**Comment by denikson** [comment]
Greetings!

From what I understand, this seems like a rather interesting issue. I have tested RoR2 dedicated server with BepInEx on Windows and know that it does work.

Looking at the linked issue, setting `WINEDLLOVERRIDES="winhttp=n,b"` or `WINEDLLOVERRIDES="winhttp=n"` should be the way to go, as Doorstop itself will always load the original winhttp (it needs to do that so that it can proxy functions to it).

First, please try this verbose version of Doorstop:

[winhttp.zip](https://github.com/BepInEx/BepInEx/files/5141178/winhttp.zip)

This should generate `doorstop_<num>.log` into the game's directory with logging information about Doorstop invoking BepInEx.

Please do send the generated log or report if it wasn't created.

**Comment by dubvulture** [comment]
I tried the DLL you provided but nothing different happens.
Here are the full logs:
- [Native + Builtin](https://gist.github.com/dubvulture/86233ee85031de848d8c51a4530b61b4)
- [Native Only](https://gist.github.com/dubvulture/1dfc6051656a358a3bf247c065458a93)

**Comment by denikson** [comment]
Have you checked if a file named `doorstop_<num>.log` appears in the game dir once you run the server? If that is not happening, it could point to Wine not actually properly loading Doorstop's `winhttp.dll`.

As an alternative, you can also try renaming `winhttp.dll` to `version.dll` and try setting up overrides for it instead.

**Comment by dubvulture** [comment]
Yeah sorry, I totally forgot that part. Here's both [doorstop](https://gist.github.com/dubvulture/7629078ca0566be00efb48820ee509bb) and [preloader](https://gist.github.com/dubvulture/8889de822e488b27273c47748335b239) logs (native + builtin mode).

Doorstop seems to be working, while the preloader is giving some useful insights:
`System.UnauthorizedAccessException: Access to the path "Z:\home\steam\ror2-dedicated\BepInEx\config" is denied.`

And that's probably it since it is owned by `root` instead of the `steam` that is running the server.
I'll try to fix that and report back asap.

**Comment by dubvulture** [comment]
After fixing the permissions I get this:
```
[Message:   BepInEx] BepInEx 5.3.0.0 - Risk of Rain 2
[Info   :   BepInEx] Running under Unity v2018.4.18.6421734
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin(s) loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
```

I guess it's working now, in a few hours I'll be able to upload some mods and check if it's really working.
Thanks for the help.

**Comment by dubvulture** [comment]
I tried some mods and it seems to be working just fine.

Thanks for you time!
