### ISSUE TITLE
BepinEX doesn't initialize Chainloader

### ISSUE THREAD

**Issue by SpartianM4ster** [BepInEx/BepInEx#140]
**Describe the bug**
The preloader finishes and doesn't start the chainloader.

**To Reproduce**
Don't know what is causing it to happen. Made sure everything was up to date, and checked for any dependencies. There were none to my knowledge. 

**Expected behavior**
For the chainloader to start up after the preloader was finished.

**Screenshots and logs**
[Message:   BepInEx] BepInEx 5.3.0.0 - Risk of Rain 2
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher methods from BepInEx.MonoMod.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :   BepInEx] 2 patcher plugin(s) loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   MonoMod] Collecting target assemblies from mods
[Info   :   BepInEx] Patching [Assembly-CSharp] with [BepInEx.MonoMod.Loader.Patcher]
[Message:   MonoMod] [Main] Scanning for mods in directory.
[Message:   MonoMod] [ReadMod] Loading mod dir: C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\BepInEx\monomod
[Message:   MonoMod] [ReadMod] Loading mod: C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\BepInEx\monomod\Assembly-CSharp.R2API.mm.dll
[Message:   MonoMod] [Main] Found 1 mods
[Message:   MonoMod] [Main] mm.PatchRefs(); fixup pre-pass
[Message:   MonoMod] [Main] mm.AutoPatch();
[Message:   MonoMod] [AutoPatch] Parsing rules in loaded mods
[Info   :   Console] [MonoMod] [RulesModder]
[Info   :   Console] [Write] Writing modded module into output stream.
[Message:   MonoMod] [AutoPatch] PrePatch pass
[Message:   MonoMod] [AutoPatch] Patch pass
[Message:   MonoMod] [AutoPatch] PatchRefs pass
[Message:   MonoMod] [PostProcessor] PostProcessor pass #1
[Message:   MonoMod] [Main] Done.
[Message:   BepInEx] Preloader finished

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: 
 - BepInEx version [e.g. 4.0]: 

**Additional context**
I have no clue what could be going on. Tried reinstalling and redownloading everything, and still no luck. Any help with the problem would be greatly appreciated.

**Comment by denikson** [comment]
Greetings!

Thank you for providing the log and information about the issue!  
Unfortunately we cannot provide plugin-specific support here, as BepInEx is a general-purpose Unity modding framework aimed at supporting various Unity games. As such, we provide help with BepInEx-related issues, but we are not able to track issues related to specific plugin setups.

Instead, I suggest seeking help from RoR2 Modding Discord: https://discord.gg/VREqSF 
Provide them the same error log you sent here and I'm sure they will be able to solve your plugin-related problem.

I'll close this issue for now, but don't hesitate to create another should you need further help or a pointer where to get more information.
