### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by conex1** [BepInEx/BepInEx#146]
I don't see any .exe file to install this in the file. Only .dll and XML Docucments.

**Comment by Mantas-2155X** [comment]
BepInEx doesn't come with an .exe installer. Try following the "How to install" link in the repo readme.

https://bepinex.github.io/bepinex_docs/master/articles/user_guide/installation/index.html?tabs=tabid-win

**Comment by denikson** [comment]
Closing this as I see this was answered. If you have any other issues, feel free to create a new issue.
