### ISSUE TITLE
[Wiki] Dead link on old wiki page toward new wiki

### ISSUE THREAD

**Issue by HijackHornet** [BepInEx/BepInEx#151]
**Describe the bug**

On this page, link toward new wiki points to a 404
https://github.com/BepInEx/BepInEx/wiki/Installation

**Expected behavior**

End up on the wiki

**Comment by denikson** [comment]
Fixed links by pointing most of them to [BepInEx 5 docs index](https://bepinex.github.io/bepinex_docs/master/articles/index.html) as some old wiki pages don't have an equivalent in new docs
