### ISSUE TITLE
[help] Native plugin loading?

### ISSUE THREAD

**Issue by nitsuga5124** [BepInEx/BepInEx#156]
I'm currently trying to run rust code over the FFI interface inside a unity game mod; for this currently I'm using some very basic code to try and get it working:
```toml
[package]
name = "unity_mod"
version = "0.0.1"
authors = ["nitsuga5124 <nitsuga5124@gmail.com>"]
edition = "2018"

[lib]
name = "unity_rust"
crate-type = ["dylib"]
```
```rust
#[no_mangle]
pub extern fn hello() -> i32 {
    42069
}
```
```cs
using UnityEngine;
using System.Collections;
using System.Runtime.InteropServices;
using BepInEx;
using BepInEx.Logging;

namespace RustMod
{
    [BepInPlugin("org.bepinex.plugins.rustmod", "RustMod", "1.0.0.0")]
    public class RustMod: BaseUnityPlugin
    {
        public RustMod() {}

        void Awake()
        {
            Logger.LogInfo("Rust Mod Test Start");

            Logger.LogInfo(hello());

            Logger.LogInfo("Rust Mod Test Finish");
        }


        //[DllImport("unity_rust")]
        //[DllImport("unity_rust.dll")]
        //[DllImport("unity_rust.bundle")]
        [DllImport("/home/nitsuga/Documents/mod/unity_rust")]
        private static extern int hello();
    }
}
```

This currently fails with
```
[Info   :   BepInEx] Loading [RustMod 1.0.0.0]
[Info   :   RustMod] Rust Mod Test Start
[Error  : Unity Log] DllNotFoundException: /home/nitsuga/Documents/mod/unity_rust
Stack trace:
RustMod.RustMod.Awake () (at <0b1625707cb841239716566677b675a8>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Sirenix.Utilities.UnityVersion:.cctor()
```
I have tried putting the compiled dll file in every single folder of the game, and i also tried a full path to it; i have also tried changing the file extension to `.bundle` with no success.
Anything i do seems to not be able to find the dll.

Compiled the rust using corss with `cross build --target x86_64-pc-windows-gnu`
Running the game with BepInEx 5.0.1 though wine; native linux was not stable with BepInEx.

**Comment by bbepis** [comment]
Hello,
There are some things I think you can try to get a bit further with this.

1. Update to BepInEx 5.4.2. Proper native unix support wasn't actually added until 5.1, and since then there have been some bugfixes with that too.
2. Ensure that the game's bitness matches the same as the compiled native library; at least on windows, LoadLibraryW and it's friends will silently fail saying that it's "not able to find the library" if there's a mismatch.
3. Use DynDll from MonoMod.Utils instead of DllImport. DllImport is known to not work very well under mono (especially Unity's version of mono), so MonoMod reimplements it from scratch with a lot of issues fixed. There's an example on how to use it [here](https://github.com/BepInEx/BepInEx/blob/master/BepInEx.Core/Console/Unix/UnixStreamHelper.cs).
4. Specify the extension of the library as well. I've had problems where it'll refuse to append the relevant extension if it can't find the library. IIRC DynDll requires the extension, but I could be wrong about that.

Let me know how you go with this. I haven't tried to do something like this in a plugin, nor do I have any experience with rust. However i'm particularly interested in how this turns out.

**Comment by nitsuga5124** [comment]
1. Done, though i will still use wine, to ensure the vast majority of the users modding the game will have the mod working too.
2: Both the game and the rust library are x64
3/4: Using MonoMod tag `v20.11.16.01`, loaded with
```xml
        <Reference Include="MonoMod.Utils">
            <HintPath>Libs/MonoMod.Utils.dll</HintPath>
        </Reference>
```
```cs
        void Awake()
        {
            Logger.LogInfo("Rust Mod Test Start");

            Logger.LogInfo(helloRust());

            Logger.LogInfo("Rust Mod Test Finish");
        }

        public delegate int hello();
        //[DynDllImport("unity_rust.dll")]
        [DynDllImport("/home/nitsuga/Documents/mod/unity_rust.dll")]
        public static hello helloRust;
```
Currently trying this code, but it does not appear to work, as it's causing this log:
```
[Info   :   BepInEx] Loading [RustMod 1.0.0.0]
[Info   :   RustMod] Rust Mod Test Start
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RustMod.RustMod.Awake () (at <712dcd9143814d44b71716589aa0fb14>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Sirenix.Utilities.UnityVersion:.cctor()
```
The dll is on the full path shown in the code, along with `$GAME/` `$GAME/BepInEx/plugins/` `$GAME/Game_Data` `$GAME/Game_Data/Plugins`, where the commented code was tested on.

> nor do I have any experience with rust.
This is all compiled in an ffi safe way, so it should be interacting the same way as C would; could even go as far as using `#[repr(C)]` if needed.

**Comment by bbepis** [comment]
You still need to add the code that initializes DynDll before you use an imported method: https://github.com/BepInEx/BepInEx/blob/master/BepInEx.Core/Console/Unix/UnixStreamHelper.cs#L50 (changed to the type of your class)

The mapping dictionary is optional; it allows you to use a key in the DynDllImport attributes, and DynDll will iterate over the supplied list looking for an assembly it can load. Very useful for cross-platform support

**Comment by nitsuga5124** [comment]
```
[Info   :   BepInEx] Loading [RustMod 1.0.0.0]
[Error  : Unity Log] EntryPointNotFoundException: No matching entry point found for hello in RustMod.RustMod
Stack trace:
MonoMod.Utils.DynDll.InternalResolveDynDllImports (System.Type type, System.Object instance, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) (at <e2d07d9893ce46d6bd8d5bb116d0ef25>:0)
MonoMod.Utils.DynDll.ResolveDynDllImports (System.Type type, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) (at <e2d07d9893ce46d6bd8d5bb116d0ef25>:0)
RustMod.RustMod..cctor () (at <d5f105e6a1774a519408019c7125348e>:0)
Rethrow as TypeInitializationException: The type initializer for 'RustMod.RustMod' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Sirenix.Utilities.UnityVersion:.cctor()

[Error  : Unity Log] EntryPointNotFoundException: No matching entry point found for hello in RustMod.RustMod
Stack trace:
MonoMod.Utils.DynDll.InternalResolveDynDllImports (System.Type type, System.Object instance, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) (at <e2d07d9893ce46d6bd8d5bb116d0ef25>:0)
MonoMod.Utils.DynDll.ResolveDynDllImports (System.Type type, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) (at <e2d07d9893ce46d6bd8d5bb116d0ef25>:0)
RustMod.RustMod..cctor () (at <d5f105e6a1774a519408019c7125348e>:0)
Rethrow as TypeInitializationException: The type initializer for 'RustMod.RustMod' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Sirenix.Utilities.UnityVersion:.cctor()
```
```cs
    public class RustMod: BaseUnityPlugin
    {
        static RustMod() {
            var mapping = new Dictionary<string, List<DynDllMapping>>
            {
                ["unity_rust"] = new List<DynDllMapping>
                {
                    "unity_rust.dll",
                    "unity_rust",
                    "/home/nitsuga/Documents/mod/unity_rust.dll",
                }
            };

            typeof(RustMod).ResolveDynDllImports(mapping);
        }

        void Awake()
        {
            Logger.LogInfo("Rust Mod Test Start");

            Logger.LogInfo(hello());

            Logger.LogInfo("Rust Mod Test Finish");
        }

        public delegate int helloRust();
        [DynDllImport("unity_rust")]
        //[DynDllImport("unity_rust.dll")]
        //[DynDllImport("/home/nitsuga/Documents/mod/unity_rust.dll")]
        public static helloRust hello;
    }
```
noticed i had the delegates backwards in the naming, fixed that
though, it appears that it's not able to find the hello function now?

**Comment by nitsuga5124** [comment]
i just realized that that path won't work over wine, lemme try Z:\...

**Comment by bbepis** [comment]
Try examining the exports of the .dll with a tool like this:
https://www.nirsoft.net/utils/dll_export_viewer.html
There should be an entry with a function name exactly the same as "hello", which is the same you're exporting.

I did a short look into this, and found another compilation option that might make a difference:

> `--crate-type=cdylib`, `#[crate_type = "cdylib"]` - A dynamic system library will be produced. This is used when compiling a dynamic library to be loaded from another language. This output type will create *.so files on Linux, *.dylib files on macOS, and *.dll files on Windows.

https://doc.rust-lang.org/reference/linkage.html

https://users.rust-lang.org/t/what-is-the-difference-between-dylib-and-cdylib/28847/3

I'm not sure if it'll make a difference, but I'm also not sure what other options are left

**Comment by nitsuga5124** [comment]
https://5124.16-b.it/ss/10:16:14_17-11-2020.png

the hello function is indeed there, along with debug stuff because it's not being build in release, but shouldn't be affecting anything.


https://users.rust-lang.org/t/what-is-the-difference-between-dylib-and-cdylib/28847/3
This are the differences between dylib and cdylib.
https://medium.com/jim-fleming/rust-lang-in-unity3d-eeaeb47f3a77
I was somewhat vaguely following this guide, which was using dylib, and looking at the differences between both, dylib looked like the more reasonable choice, but apparently it doesn't go well with this anymore.
Compiling for `cdylib` did make it work. Thanks for the help!
https://5124.16-b.it/ss/10:24:29_17-11-2020.png
