### ISSUE TITLE
5.4.1 does not upgrade assemblies loaded via Assembly.LoadFrom

### ISSUE THREAD

**Issue by denikson** [BepInEx/BepInEx#158]
**Describe the bug**

BepInEx 5.4.1 fails to automatically upgrade 5.3 assemblies in case they are loaded via `Assembly.LoadFrom`

**To Reproduce**

1. Compile an old DLL that uses old Harmony
2. Try to load said DLL via `Assembly.LoadFrom` and invoke its Harmony patches

**Expected behavior**

DLL is automatically upgraded to work with BepInEx 5.4.1 and patches are applied.

**Screenshots and logs**

Check latest comments in #147 for error logs.

**Desktop (please complete the following information):**
 - BepInEx version [e.g. 4.0]: 5.4.1

**Comment by denikson** [comment]
@gbooker Do you mind testing the following version:

[BepInEx_unix_5.4.2.0.zip](https://github.com/BepInEx/BepInEx/files/5578442/BepInEx_unix_5.4.2.0.zip)

This should likely fix the problem with loading of some assemblies that you reported in #147.

Please include the logs like before.

**Comment by denikson** [comment]
This was tested and seems to be fixed, closing the issue

**Comment by gbooker** [comment]
I know I'm late to this but I did get around to testing this just now and it works as expected.
