### ISSUE TITLE
HS 2 after updating from 5.0.0.0 to 5.4.5.0 got error

### ISSUE THREAD

**Issue by mantisss111** [BepInEx/BepInEx#164]
**Describe the bug**
```
[Fatal  :   BepInEx] Could not run preloader!
[Fatal  :   BepInEx] System.ArgumentNullException: Value cannot be null.
Parameter name: path
  at System.IO.Path.InsecureGetFullPath (System.String path) [0x00003] in <7ba07f088431485bb722f3b3373e87ee>:0
  at System.IO.Path.GetFullPath (System.String path) [0x00000] in <7ba07f088431485bb722f3b3373e87ee>:0
  at System.Diagnostics.FileVersionInfo.GetVersionInfo (System.String fileName) [0x00000] in <d2957de1c3fd4781a43d89572183136c>:0
  at BepInEx.Preloader.Preloader.GetUnityVersion () [0x0000e] in <2a40e3e9724c465d90976291a9b865b3>:0
  at BepInEx.Preloader.Preloader.Run () [0x000db] in <2a40e3e9724c465d90976291a9b865b3>:0
```

**To Reproduce**
Game not laucnh (all plugins updated to compatible versions

**Expected behavior**

**Screenshots and logs**

**Desktop (please complete the following information):**
 - Honey Select Libido R3 Hotfix 1 
 - BepInEx version 5.4.5.0

**Additional context**

**Comment by denikson** [comment]
Greetings!

This issue is caused usually by incomplete BepInEx update. When updating BepInEx, you need to replace **all** files, including Doorstop (`winhttp.dll`). If you don't replace Doorstop with one shipped with latest BepInEx version, this error will appear.

Make sure your `winhttp.dll` file is of the latest version (one shipped with 5.4.5 is 3.0.2.2) and that there are no older `version.dll` builds of Doorstop present.

**Comment by mantisss111** [comment]
I placed all files from archive to game folder core folder to bepinex folder and doorstop_config.ini with winhttp.dll to root of game.

Error log:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: path1
  at System.IO.Path.Combine (System.String path1, System.String path2) [0x00003] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at BepInEx.Preloader.Preloader.Run () [0x002cb] in <2a40e3e9724c465d90976291a9b865b3>:0 
  at BepInEx.Preloader.PreloaderRunner.PreloaderMain () [0x00016] in <2a40e3e9724c465d90976291a9b865b3>:0 
  at BepInEx.Preloader.PreloaderRunner.PreloaderPreMain () [0x00057] in <2a40e3e9724c465d90976291a9b865b3>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <7ba07f088431485bb722f3b3373e87ee>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <7ba07f088431485bb722f3b3373e87ee>:0 
  at BepInEx.Preloader.Entrypoint.Main () [0x0008b] in <2a40e3e9724c465d90976291a9b865b3>:0

**Comment by denikson** [comment]
Judging by the error you still may have mismatching BepInEx and Doorstop DLLs.

Since you're using some kind of pack, I would suggest seeking help from the game's community. In case of HS2, there is [IllusionSoft Discord](https://discord.gg/illusionsoft) where it is possible to seek tech support for the packs they create. Provide enough information like logs, what you did and your game folder screenshots to see how the files are placed.

If you still want to try fixing it yourself, you can try temporarily moving out **all** BepInEx files (that is, `BepInEx` folder alongside `winhttp.dll` and `doorstop_config.ini`) of the game and then download [fresh BepInEx 5.4.5](https://github.com/BepInEx/BepInEx/releases/download/v5.4.5/BepInEx_x64_5.4.5.0.zip) zip and install it. If it works just fine on clean BepInEx (that is, the game starts without errors), your previous install is still not correct.  

I just tested BepInEx on HS2 out and it does indeed work fine.

**Comment by mantisss111** [comment]
I launch it but now direct gpu acceleration not work in game.

**Comment by mantisss111** [comment]
> Judging by the error you still may have mismatching BepInEx and Doorstop DLLs.
> 
> Since you're using some kind of pack, I would suggest seeking help from the game's community. In case of HS2, there is [IllusionSoft Discord](https://discord.gg/illusionsoft) where it is possible to seek tech support for the packs they create. Provide enough information like logs, what you did and your game folder screenshots to see how the files are placed.
> 
> If you still want to try fixing it yourself, you can try temporarily moving out **all** BepInEx files (that is, `BepInEx` folder alongside `winhttp.dll` and `doorstop_config.ini`) of the game and then download [fresh BepInEx 5.4.5](https://github.com/BepInEx/BepInEx/releases/download/v5.4.5/BepInEx_x64_5.4.5.0.zip) zip and install it. If it works just fine on clean BepInEx (that is, the game starts without errors), your previous install is still not correct.
> 
> I just tested BepInEx on HS2 out and it does indeed work fine.


Now this without 3d acceleration 
[Message:   BepInEx] BepInEx 5.4.5.0 - HoneySelect2
[Info   :   BepInEx] Running under Unity v2018.4.11.7379119
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [CultureFix 13.2.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [MagicCarrot 13.2.0.0]
[Info   :   BepInEx] 3 patcher plugins loaded
[Info   :   Console] CultureFix - Forcing process culture to ja-JP.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Sirenix.Utilities] with [IllusionFixes.Patchers.MagicCarrotPatch]
[Info   :   BepInEx] Patching [Sirenix.Serialization] with [IllusionFixes.Patchers.MagicCarrotPatch]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 90 plugins to load
[Warning:   BepInEx] Skipping [Studio Wear Custom 0.1.5] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [HS2_QuickAccessBox 2.2.1] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Studio Camera Tweaks 1.0] because of process filters (CharaStudio, StudioNEOV2)
[Warning:   BepInEx] Skipping [StudioCharaRefresh 1.0] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [HS2_StudioAccessoryNames 1.0.0] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [HS2_StudioPOV 1.1.1] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Material Editor 2.0.6] because a newer version exists (Material Editor 2.4.1)
[Warning:   BepInEx] Skipping [Material Editor Maker 2.4.1] because of process filters (EmotionCreators)
[Warning:   BepInEx] Skipping [Animation Controller 2.2] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [FK and IK 1.1] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Material Editor Studio 2.0.6] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Pose Folders 1.0] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Pose Quick Load 1.0] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Studio Object Move Hotkeys 1.0] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Studio Scene Loaded Sound 1.1] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Uncensor Selector 3.9.1] because a newer version exists (Uncensor Selector 3.11.1)
[Warning:   BepInEx] Skipping [Fix Shader Dropdown Menu 15.1] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Invalid Scene Protection 15.1] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Pose Load Fix 15.1] because of process filters (StudioNEOV2)
[Warning:   BepInEx] Skipping [Studio Optimizations 15.1] because of process filters (StudioNEOV2)
[Info   :   BepInEx] Loading [Extended Save 16.2.0.2]
[Info   :   BepInEx] Loading [XUnity Resource Redirector 1.1.3]
[Info   :   BepInEx] Loading [Sideloader 16.2.0.2]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Manager.GameSystem and name IsPathAdd50 and parameters
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static System.Void Sideloader.Hooks::IsPathAdd50Hook(System.String _path, System.Boolean& __result)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <388cac1016f2477d966f58f4bc45074c>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <388cac1016f2477d966f58f4bc45074c>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <388cac1016f2477d966f58f4bc45074c>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <388cac1016f2477d966f58f4bc45074c>:0)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <388cac1016f2477d966f58f4bc45074c>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Type type, System.String harmonyInstanceId) (at <388cac1016f2477d966f58f4bc45074c>:0)
Sideloader.Sideloader+Hooks.InstallHooks () (at <a95e99aa2e454c4c8dc5b9b74b917456>:0)
Sideloader.Sideloader.Awake () (at <a95e99aa2e454c4c8dc5b9b74b917456>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
FileData:get_Path()
UserData:get_Path()
Illusion.Elements.Xml.Control:Read()
Manager.Config:.cctor()

[Info   :   BepInEx] Loading [MoreAccessories 1.2.1]
[Info   :   BepInEx] Loading [Modding API 1.15]
[Info   :   BepInEx] Loading [Skin Overlay Mod 5.2]
[Info   :   BepInEx] Loading [Uncensor Selector 3.11.1]
[Info   :   BepInEx] Loading [BonesFramework 1.4.1]
[Info   : Unity Log] BonesFramework: Trying to patch methods...
[Info   : Unity Log] BonesFramework: UncensorSelector found, trying to patch
[Info   : Unity Log] BonesFramework: UncensorSelector patched correctly
[Info   : Unity Log] BonesFramework: Patch successful!
[Info   :   BepInEx] Loading [HS2 Better Penetration 2.5.0.3]
[Info   :   BepInEx] Loading [Optimize IMGUI GC allocations 1.0]
[Info   :   BepInEx] Loading [BepisFixHS2 1.0]
[Info   :   BepInEx] Loading [Better Anti-Aliasing 1.5]
[Info   :   BepInEx] Loading [Runtime Unity Editor 2.3]
[Info   :   BepInEx] Loading [Cheat Tools 2.8.1]
[Info   :   BepInEx] Loading [HS2 PoV X 1.0.1]
[Info   :   BepInEx] Loading [Configuration Manager 16.1]
[Info   :   BepInEx] Loading [Input Length Unlocker 16.2.0.2]
[Info   :   BepInEx] Loading [Screenshot Manager 16.2.0.2]
[Info   :   BepInEx] Loading [Slider Unlocker 16.2.0.2]
[Info   :   BepInEx] Loading [BGM Loader 16.2.0.2]
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.Resources and name GetBuiltinResource and parameters (System.String, System.Type)
[Info   :   BepInEx] Loading [Message Center 1.1.1]
[Info   :   BepInEx] Loading [Autosave 1.0.1]
[Info   :   BepInEx] Loading [Character Export 1.0]
[Info   :   BepInEx] Loading [Demosaic 1.1]
[Info   :   BepInEx] Loading [Eye Control 1.0.1]
[Info   :   BepInEx] Loading [Input Hotkey Block 1.2]
[Info   :   BepInEx] Loading [Invisible Body 1.3.2]
[Info   :   BepInEx] Loading [Male Juice 1.2.1]
[Info   :   BepInEx] Loading [Material Editor 2.4.1]
[Info   :   BepInEx] Loading [Material Editor Maker 2.0.6]
[Info   :   BepInEx] Loading [Mute In Background 1.0]
[Info   :   BepInEx] Loading [Subtitles 2.0.2]
[Info   :   BepInEx] Loading [XUnity Auto Translator 4.11.3]
[Warning: Unity Log] OnLevelWasLoaded was found on AutoTranslationPlugin
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\log_wire [2466682E44-C26CBDF7E9].png.
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\SpriteAtlasTexture-sp_ai_H-2048x1024-fmt4 [290CA4BEF5-622DF12CB9].png.
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\SpriteAtlasTexture-sp_ai_pouch-1024x1024-fmt4 [4F5D94683E-D0AC8C6459].png.
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\SpriteAtlasTexture-sp_ai_system (Group 0)-1024x2048-fmt4 [738584A67C-144E74FF76].png.
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\sp_ai_title_00_00 [4D8C6627D4-2DCE2CC96F].png.
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\sp_hs2_00_19_00 [FAABFC31A5-5F864BB0D7].png.
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\sp_hs2_00_40_00 [D25A7583E1-E232D5A696].png.
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\sp_hs2_00_70_00 [9A0F3B5E1C-533DD74B36].png.
[Warning:XUnity.AutoTranslator] Image not loaded (unmodified): F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\Translation\en\Texture\sp_hs2_H_00_00 [AE6AF6CDFF-5ADBE2E76F].png.
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2018.4.11f1] game.
[Info   :   BepInEx] Loading [Text Resource Redirector 1.3.1]
[Info   :Text Resource Redirector] IllusionMods.ExcelDataHandler enabled
[Info   :Text Resource Redirector] IllusionMods.ScenarioDataHandler enabled
[Info   :Text Resource Redirector] IllusionMods.TextAssetTableHandler enabled
[Info   :Text Resource Redirector] IllusionMods.ChaListDataHandler enabled
[Info   :Text Resource Redirector] IllusionMods.VoiceInfoHandler enabled
[Info   :Text Resource Redirector] IllusionMods.BGMNameInfoHandler enabled
[Info   :Text Resource Redirector] IllusionMods.EventContentInfoDataHandler enabled
[Info   :Text Resource Redirector] IllusionMods.MapInfoHandler enabled
[Info   :Text Resource Redirector] IllusionMods.ParameterNameInfoHandler enabled
[Info   :Text Resource Redirector] IllusionMods.AchievementInfoDataHandler enabled
[Info   :   BepInEx] Loading [Heelz 1.14.3]
[Info   :   BepInEx] Loading [HS2_Hooah 1.4.2]
[Info   :   BepInEx] Loading [HS2_AnimationPairing 1.0.0]
[Info   :   BepInEx] Loading [boopz 1.0.1]
[Info   :   BepInEx] Loading [HeightBarX 3.3]
[Info   :   BepInEx] Loading [C# Script Loader 1.2.1]
[Info   :C# Script Loader] Found 1 scripts to compile, skipping 0 scripts because of `scriptignores` or process filters
[Info   :C# Script Loader] (12,35): error CS0619: `BepInEx.Harmony.HarmonyWrapper.PatchAll(System.Type, HarmonyLib.Harmony)' is obsolete: `Use HarmonyLib.Harmony.CreateAndPatchAll or HarmonyLib.Harmony.PatchAll'
[Info   :C# Script Loader] (12,35): error CS0029: Cannot implicitly convert type `HarmonyLib.Harmony [0Harmony20, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null -- F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\core\0Harmony20.dll]' to `HarmonyLib.Harmony [0Harmony, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null -- F:\GAMES\PC\ILLUSiON_XXX\Honey Select 2 - Libido\BepInEx\core\0Harmony.dll]'
[Info   :C# Script Loader] Failed to compile because Mono.CSharp.InternalErrorException: (8,21): AYAYA ---> System.InvalidOperationException: Method 'AYAYA.Main' does not have a method body.
[Info   :C# Script Loader]   at System.Reflection.Emit.MethodBuilder.fixup () [0x0005d] in <7ba07f088431485bb722f3b3373e87ee>:0
[Info   :C# Script Loader]   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo () [0x002d1] in <7ba07f088431485bb722f3b3373e87ee>:0
[Info   :C# Script Loader]   at System.Reflection.Emit.TypeBuilder.CreateType () [0x00000] in <7ba07f088431485bb722f3b3373e87ee>:0
[Info   :C# Script Loader]   at Mono.CSharp.TypeDefinition.CloseContainer () [0x00054] in <c25f87a7ef8b49b39bc5f3b5af8bd101>:0
[Info   :C# Script Loader]    --- End of inner exception stack trace ---
[Info   :C# Script Loader]   at Mono.CSharp.TypeDefinition.CloseContainer () [0x0006d] in <c25f87a7ef8b49b39bc5f3b5af8bd101>:0
[Info   :C# Script Loader]   at Mono.CSharp.TypeContainer.CloseContainer () [0x0001d] in <c25f87a7ef8b49b39bc5f3b5af8bd101>:0
[Info   :C# Script Loader]   at Mono.CSharp.TypeContainer.CloseContainer () [0x0001d] in <c25f87a7ef8b49b39bc5f3b5af8bd101>:0
[Info   :C# Script Loader]   at Mono.CSharp.ModuleContainer.CloseContainer () [0x0006b] in <c25f87a7ef8b49b39bc5f3b5af8bd101>:0
[Info   :C# Script Loader]   at ScriptLoader.MonoCompiler.Compile (System.Collections.Generic.Dictionary`2[TKey,TValue] sources, System.IO.TextWriter logger) [0x00284] in <c25f87a7ef8b49b39bc5f3b5af8bd101>:0
[Error  :C# Script Loader] Skipping loading scripts because of errors above.
[Info   :   BepInEx] Loading [HS2_BetterHScenes 2.5.8]
[Info   :   BepInEx] Loading [HS2_ClothColliders 1.0.1]
[Info   :   BepInEx] Loading [Configuration Manager wrapper for HoneySelect 2 16.2.0.2]
[Info   :   BepInEx] Loading [Camera Target Fix 15.1]
[Info   :   BepInEx] Loading [Adjust physics gravity to match AI-Shoujo 15.1]
[Info   :   BepInEx] Loading [Studio and Maker Data Corruption Fixes 15.1]
[Info   :   BepInEx] Loading [Maker Optimizations 15.1]
[Info   :   BepInEx] Loading [Manifest Corrector 15.1]
[Info   :   BepInEx] Loading [Null Checks 15.1]
[Info   :   BepInEx] Loading [Resource Unload Optimizations 15.1]
[Info   :   BepInEx] Loading [Settings Fix 15.1]
[Info   :   BepInEx] Loading [HS2_HCharaSwitcher 1.2.1]
[Info   :   BepInEx] Loading [HS2_HLightControl 1.2.0]
[Info   :   BepInEx] Loading [HS2_UnlockPlayerHClothes 1.4.0]
[Info   :   BepInEx] Loading [HS2_UnlockPlayerHeight 1.4.1]
[Info   :   BepInEx] Loading [Clothes Overlay Mod 5.2]
[Info   :   BepInEx] Loading [Clothes Overlay Mod GUI 5.2]
[Info   :   BepInEx] Loading [Drag & Drop 1.2.1]
[Info   :   BepInEx] Loading [Graphics Settings 1.2.0]
[Info   :   BepInEx] Loading [HideAllUI 2.2.0]
[Info   :   BepInEx] Loading [HS2ABMX (BonemodX) 4.4.1]
[Info   :   BepInEx] Loading [HS2_ColorPanelX 1.2.0]
[Info   :   BepInEx] Loading [Skin Overlay Mod GUI 5.2]
[Info   :   BepInEx] Loading [FPS Counter 3.0]
[Info   :   BepInEx] Loading [Maker/Studio Browser Folders 2.1]
[Info   :   BepInEx] Loading [Gravure plugin 1.3.1]
[Warning: Unity Log] OnLevelWasLoaded was found on GravurePlugin
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
[Info   :   BepInEx] Loading [HS2ChicksDigMapModdersPlugin 1.0.0]
[Info   :   BepInEx] Loading [HS2TakeChargePlugin 1.4.0]
[Info   :HS2TakeChargePlugin] Generating Default Ruleset
[Info   :   BepInEx] Loading [Graphics 0.3.3]
[Info   :   BepInEx] Loading [SayNoToModChecker 1.0.0]
[Message:   BepInEx] Chainloader startup complete
[Warning:Runtime Unity Editor] Vectrosity.dll is not available, drawing gizmos will be disabled

**Comment by denikson** [comment]
To me it looks like it works, however there are some plugin-related errors. Some of them are even outdated (for example, ScriptLoader is really outdated -- I am the maintainer of the plugin, after all).

Unfortunately, I cannot help with plugin-specific issues as BepInEx is a general Unity modding framework. For game-specific supportI strongly encourage visiting the forums used by the game (like [IllusionSoft Discord](https://discord.gg/illusionsoft) I mentioned).

I'm going to close this issue for now as there is nothing on BepInEx side that is to fix. If you have any new errors, please create a new issue.

**Comment by mantisss111** [comment]
Can you pack your BepInex folder and root files of game and upload on file hosting? Becuase I can't find solution

**Comment by denikson** [comment]
Instead of trying to Frankenstein your BepInEx install from my personal customized setup, I suggest instead installing something like [HS2 HF Patch](https://github.com/ManlyMarco/HS2-HF_Patch/releases).

Again, nothing much more I can help with since I have the game only for testing purposes. Since you seem to need more assistance than what can be provided here, I implore and urge to seek help in HS2 modding community which maintains the plugins and knows more about the game.

**Comment by mantisss111** [comment]
I have 5mbit connection (

**Comment by mantisss111** [comment]
> Instead of trying to Frankenstein your BepInEx install from my personal customized setup, I suggest instead installing something like [HS2 HF Patch](https://github.com/ManlyMarco/HS2-HF_Patch/releases).
> 
> Again, nothing much more I can help with since I have the game only for testing purposes. Since you seem to need more assistance than what can be provided here, I implore and urge to seek help in HS2 modding community which maintains the plugins and knows more about the game.

I updated game with patch now animation Link menu not working. Do you now what plugin is used for that?

**Comment by denikson** [comment]
As I said previously, this repo is for general BepInEx and we can't help with specific games.

I don't know of any plugins that HS2 uses enough to provide any kind of guidance.

Please seek help from IllusionSoft Discord or other places where HS2 modding is discussed (unfortunately I don't know of any besides the Discord server, but there might be some forums).

Since this is not a support ticket for HS2, I'll lock the issue. If you have any issues regarding BepInEx itself, please create a new issue ticket.
