### ISSUE TITLE
Accessing internals

### ISSUE THREAD

**Issue by Kyle873** [BepInEx/BepInEx#165]
I'm trying to patch an XNA game which has almost everything in terms of classes marked as internal which makes most things inaccessible. I work around this by generating a new version of the game's assembly with them converted to public instead of internal using dnlib and referencing that for my plugin while using the original assembly to launch the game. While this solves the issue of compiling the plugin itself, it will, of course, still fail at runtime.

I'm thinking a solution to this might be to inject the `InternalsVisibleToAttribute` into the assembly at runtime for each plugin to bypass the issue altogether. Maybe an extra attribute or config option or some such for a plugin to specify it wants to be added to the `InternalsVisibleTo` visibility list?

For now, I manually add the attribute for my plugin using dnSpy.

**Comment by js6pak** [comment]
Have you tried adding `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` to your plugin?

**Comment by Dual-Iron** [comment]
Try applying IgnoreAccessChecksToAttribute and SkipVerificationAttribute(true) to your assembly, and UnverifiableCodeAttribute to your module.
Relevant code snippet: https://github.com/Dual-Iron/RWBepInEx/blob/020c842fbf8730e85f577df6fea3537c35d50a72/BepInEx.Partiality.Patcher/Patcher.cs#L22

**Comment by ghorsington** [comment]
Closing this issue as stale (and as it did receive some possible answers).

If you do have any more problems regarding this issue, please create a new ticket.
