### ISSUE TITLE
BepInEx Wont Activate in Craftopia!

### ISSUE THREAD

**Issue by Gre3nDog** [BepInEx/BepInEx#170]
Hy!

Trying to use BepInEx for Craftopia so that i can expand my inventory but its not working Tryd the Version 5.4.5 and the 5.4.4 for the game Version 20210105.2115 im not sure what to do next Downgrade the game or the BepInEx version...some help maybe please!

Thx in Advanace!

**Comment by denikson** [comment]
Greetings!

It would be of utmost benefit to us if you used one of the issue templates that are available when you create a ticket and elaborated on your issue.
Most importantly, we always want to know the following:

* What did you try to do? How did you install BepInEx?
* Any patchers or plugins installed?
* Any errors in the console? Did you get any log files at all (e.g. `preloader_err` logs or `LogOutput.txt` in `BepInEx` folder)?

As BepInEx is designed to be game-agnostic, explaining your current setup in detail is helpful for us to understand how to reproduce the issue.

**Comment by denikson** [comment]
Update for this: I am unfortunately unable to replicate the issue, as it works fine with [BepInEx_x64_5.4.5.0](https://github.com/BepInEx/BepInEx/releases/download/v5.4.5/BepInEx_x64_5.4.5.0.zip)

Screenshot of the game + console launched which shoes the version as well:
![image](https://user-images.githubusercontent.com/13762037/104104438-da974300-52b0-11eb-84e6-8029b285832d.png)

As such, please provide additional details as I requested in the previous message.

**Comment by Gre3nDog** [comment]
HY!

So im trying to add more Inventory space to my game using this mod "https://www.nexusmods.com/craftopia/mods/1"!
My steps for installaling install fresh copy of the game from steam launch 1 time doing all the setup and creataning a character and world after exit downloading the BepinEx extracting all content from the rar in root of the game and starting it and closing it and see if in the Folder BepInEx all other folders where created and they ar puting the addon in the Plugings folder and start the game load up and still nothing...same with other mods from the website!

**Comment by denikson** [comment]
Here is my working set up (preconfigured to show the console as well, you can check `BepInEx\BepInEx.cfg` in a text editor like Notepad for other options as well):
[BepInEx_Craftopia.zip](https://github.com/BepInEx/BepInEx/files/5791515/BepInEx_Craftopia.zip)

Remove whatever you have installed (`BepInEx` folder, `doorstop_config.ini` and `winhttp.dll`) and extract everything from the zip into the game folder. If done correctly, your folder will look like this:
![image](https://user-images.githubusercontent.com/13762037/104104890-627e4c80-52b3-11eb-91af-64b83dac494e.png)

If you have extra files or folders, delete them (or better, move them to some other place temporarily).

That said, it looks like the mod you linked is outdated, since it fails to load with the following error:
```
TypeLoadException: Could not load type Oc.OcGameMng, Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
```
this error implies the there was a change in the game code that broke the plugin. You would have to contact the plugin author for the fix.

**Comment by Gre3nDog** [comment]
[LogOutput.log](https://github.com/BepInEx/BepInEx/files/5791536/LogOutput.log)
 Hier is the log for it! still not working.....

**Comment by denikson** [comment]
You can try to replace `BepInEx.cfg` with this (extract into `BepInEx\config`) folder which will give more logging and send over new `LogOutput.txt`:
[new_config.zip](https://github.com/BepInEx/BepInEx/files/5791551/new_config.zip)

However, as I said before **BigInventory is clearly broken in 20210105.2115**. So there is not much to do if you see
```
TypeLoadException: Could not load type Oc.OcGameMng, Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
```
in the console.

**Comment by Gre3nDog** [comment]
Hy!

So i used a other mod SuperStacks and still not starting...
[LogOutput.log](https://github.com/BepInEx/BepInEx/files/5791569/LogOutput.log)

**Comment by denikson** [comment]
It has the same problem, just different type:
```
[Error  : Unity Log] TypeLoadException: Could not load type Oc.Item.OcItem, Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
```
again, you will have to contact the dev to fix it.

**Comment by Gre3nDog** [comment]
Hy well i did try like 8 mods til now and all the olmost the same so the mods ar the problem and not the BepInEx now i can relax....but still tryng to play the game better and not posile well then heave to w8 for official mods from Workshop on steam!
Thx for help and Support!"
