### ISSUE TITLE
Plugin Issue?

### ISSUE THREAD

**Issue by matmor1208** [BepInEx/BepInEx#173]
**Describe the bug**

I'm trying to download a among us mod but when I try it comes up with errors in the LogOutput.
**To Reproduce**

I changed some of the files and added BepInEx to the Among us folders.
**Expected behavior**

It was supposed to load up a version of Among Us with a different region which allows more then 10 players to join a single 
**Screenshots and logs**

[LogOutput.log](https://github.com/BepInEx/BepInEx/files/5816330/LogOutput.log)

**Desktop (please complete the following information):**
 - Game and game version: Unknown
 - BepInEx version: Unkown 

**Additional context**

**Comment by denikson** [comment]
Greetings!

From the looks of the logs, this is indeed a plugin issue. BepInEx is a general Unity framework and as such we are not able to provide technical support for specific mods.

I suggest getting in contact with the mod developer to seek technical assistance. Unfortunately I do not know of any general Among Us modding communities, so you will have to search for yourself. That being said, I know of [Reactor Discord](https://discord.gg/pKM7pbufP3) which is a Discord server for a modding framework for Among Us. It could be possible that they might at least point you in the right direction.

If you do have other general BepInEx-related issues, do feel free to create another issue ticket.
