### ISSUE TITLE
Loading any external dlls and invoking methods during PrePatcher fails

### ISSUE THREAD

**Issue by Muchaszewski** [BepInEx/BepInEx#177]
**Describe the bug**
Loading any external dlls and invoking methods during PrePatcher fails

**To Reproduce**

1. Add Json.Net to the project.
2. Create simple pre-patcher
```
public class Test
{
    /// <summary>
    ///     List of assemblies to patch
    /// </summary>
    public static IEnumerable<string> TargetDLLs { get; } = new[] {"Assembly-CSharp.dll"};

    /// <summary>
    ///      Patches the assemblies in this case Assembly-CSharp.dll
    /// </summary>
    /// <param name="assembly"></param>
    public static void Patch(ref AssemblyDefinition assembly)
    {
        try
        {
            JsonConvert.SerializeObject(new TestJson());
        }
        catch (Exception e)
        {
            ConsoleLogger.LogFatal(e.ToString());
            throw;
        }
    }

    public class TestJson
    {
        public string Foo;
    }
}
```
3. Run
4. Exception

**Expected behavior**

JsonConvert runs successfully.

**Screenshots and logs**

```
[Fatal  :ConsoleLogger] System.TypeLoadException: Could not load type 'Newtonsoft.Json.JsonConvert' from assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
  at Test.Patch (Mono.Cecil.AssemblyDefinition& assembly) [0x00000] in <filename unknown>:0
[Error  :   BepInEx] Failed to run [Test] when patching [Assembly-CSharp]. This assembly will not be patched. Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Newtonsoft.Json.JsonConvert' from assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
  at Test.Patch (Mono.Cecil.AssemblyDefinition& assembly) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0
  at BepInEx.Preloader.Patching.AssemblyPatcher+<>c__DisplayClass10_0.<AddPatchersFromDirectory>b__3 (Mono.Cecil.AssemblyDefinition& pAss) [0x00000] in <filename unknown>:0
  at BepInEx.Preloader.Patching.AssemblyPatcher.PatchAndLoad (System.String directory) [0x00000] in <filename unknown>:0
```
**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: Dyson Sphere Programm 0.6.15.5678
 - BepInEx version [e.g. 4.0]: BepInEx 5.4.5

**Additional context**
The issue seems to be related to the patcher not loading any assemblies other than default ones. See: https://github.com/BepInEx/BepInEx/issues/176

**Comment by denikson** [comment]
Greetings!

I'm going to answer here as #176 stems from the same potential issue. What .NET Framework version did you build your assembly against? This game exceptionally bundles .NET Framework 3.5 equivalent API only, so you must build your assemblies against .NET Framework 3.5.

In general, you can try and deduce the API level to build against by checking the version of `mscorlib.dll`: if it is below `4.0.0.0`, you should use .NET Framework 3.5 as the build target. This is described in [BepInEx plugin writing walkthrough](https://bepinex.github.io/bepinex_docs/master/articles/dev_guide/plugin_tutorial/1_setup.html#creating-a-solution).
I have tested the code you provided in #176 while building against .NET Framework 3.5 and it did indeed run without any issues. BepInEx itself uses LINQ quite a bit so if the issue really were there, BepInEx wouldn't launch at all.

Please make sure your project is targeting .NET Framework 3.5, rebuild your assemblies and try again.

As a side note: if you are going to use JSON.NET for whatever reason in preloader patchers (which I do not recommend as preloader patchers were made for a very narrow purpose -- they do not replace normal plugins), you might have to build one yourself that's compatible with the .NET Framework 3.5 "equivalent" API that comes with Unity games. Unity games tend to leave out some assemblies that JSON.NET usually assumes are there (like `System.Data.dll`).

**Comment by Muchaszewski** [comment]
I originally wanted to use UnityEngine.JsonUtilities but I had problems with loading that assembly as well (the same error/issues as with Json.NET).

I will change the target project to 3.5 and will let you know.

**Comment by Muchaszewski** [comment]
![image](https://user-images.githubusercontent.com/5092066/106367534-a4932f00-6343-11eb-8b35-e1ebe58d8f60.png)
```
0>------- Started building project: TranslationCommonLibrary
0>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): Warning MSB3258 : The primary reference "UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" could not be resolved because it has an indirect dependency on the .NET Framework assembly "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which has a higher version "4.0.0.0" than the version "2.0.0.0" in the current target framework.
0>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): Warning MSB3258 : The primary reference "BepInEx, Version=5.4.5.0, Culture=neutral, PublicKeyToken=null" could not be resolved because it has an indirect dependency on the .NET Framework assembly "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which has a higher version "4.0.0.0" than the version "2.0.0.0" in the current target framework.
0>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva- /reference:"D:\Games\SteamLibrary\steamapps\common\Dyson Sphere Program\BepInEx\core\BepInEx.Harmony.dll" /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Core.dll" /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Data.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Xml.dll /reference:"D:\Games\SteamLibrary\steamapps\common\Dyson Sphere Program\DSPGAME_Data\Managed\UnityEngine.CoreModule.dll" /reference:"D:\Games\SteamLibrary\steamapps\common\Dyson Sphere Program\DSPGAME_Data\Managed\UnityEngine.IMGUIModule.dll" /reference:"D:\Games\SteamLibrary\steamapps\common\Dyson Sphere Program\DSPGAME_Data\Managed\UnityEngine.JSONSerializeModule.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\TranslationCommonLibrary.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /target:library /utf8output /langversion:7.3 ConsoleLogger.cs ITranslationProto.cs JsonUtil.cs LanguageContainer.cs LanguageData.cs LanguageSettings.cs Properties\AssemblyInfo.cs TranslationManager.cs Utils.cs
0>TranslationCommonLibrary -> C:\Users\Tomasz\RiderProjects\DSPSimpleBuilding\TranslationCommonLibrary\bin\Debug\TranslationCommonLibrary.dll
```

I have tried to change to .NET 3.5 but I'm unable to load any references now - even though the game's mscorlib.dll is 2.0
![image](https://user-images.githubusercontent.com/5092066/106367574-e1f7bc80-6343-11eb-9768-466f1afe8bfc.png)

Please, can you advise?

**Comment by denikson** [comment]
It appears that while the game is bundled with .NET Framework 3.5 equivalent API, the included Unity Engine DLLs were built against .NET Framework 4. While the mono runtime that runs the DLLs does not care for assembly versions too much, it affects the building process. This can happen in some Unity versions (so far I have seen one another game with the same problem).

The build process can be fixed by retargeting Unity Engine DLLs you use in your project (`UnityEngine.dll`, `UnityEngine.CoreModule.dll`, whatever else `UnityEngine*.dll` you use). One way is to use dnSpy which allows you to edit assemblies freely.

Another option is to write a simple program that edits the DLL with cecil. The basic code is

```cs
using var ms = new MemoryStream(File.ReadAllBytes(dllPath));
var var ass = AssemblyDefinition.ReadAssembly(ms);

ass.MainModule.Runtime = TargetRuntime.Net_2_0;

var corlib = ass.MainModule.AssemblyReferences.First(a => a.Name == "mscorlib");
corlib.Version = new Version(2, 0, 0, 0);

ass.Write(dllPath);
```

As an example I made a small CLI tool from the above code:
[DowngradeDll.zip](https://github.com/BepInEx/BepInEx/files/5899172/DowngradeDll.zip)


The process is:
1. Copy Unity Engine DLLs you use in your project from `Managed` into some other folder. You must do so as the assemblies will be used only for compiling purposes.
2. Drag n' drop assemblies onto the executable
3. After it's done, use the edited Unity Engine DLLs as your new assembly references.

Illustrative example (note that I'm not doing this in `Managed` to prevent overwriting original DLLs):
![downgrade](https://user-images.githubusercontent.com/13762037/106374291-84d32980-638a-11eb-8cc8-f4ca603f6cbc.gif)

You can use the fixed UnityEngine DLLs in the build process. At runtime mono won't really care about versioning so the plugin will work fine.

**Comment by Muchaszewski** [comment]
Thank you very much for the help.

Since Linq now works as intended I could proceed to make it work, but I have thought of a solution that would use Harmony instead of Mono Cecil. 
Mono Cecil would require me to write a JSON parser from scratch, as UnityEngine is not loaded at the time of execution and Json.NET (even those targeted for Unity runtime for .NET 3.5) do not work from the Patcher since as you mentioned some libraries/methods are missing in runtime.

```
[Error  :   BepInEx] Failed to run Initializer of Test: System.TypeInitializationException: An exception was thrown by the type initializer for Newtonsoft.Json.JsonWriter ---> System.TypeLoadException: A type load exception has occurred.
  at Newtonsoft.Json.JsonWriter.BuildStateArray () [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.JsonWriter..cctor () [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Newtonsoft.Json.JsonTextWriter..ctor (System.IO.TextWriter textWriter) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value) [0x00000] in <filename unknown>:0
  at Test.Initialize () [0x00000] in <filename unknown>:0
```

I will leave this issue open (and close #176) so that maybe you will find a way to include JSON parsing in a Patcher.

Again thank you for your help!

**Comment by denikson** [comment]
Did you try using JSON.NET in normal plugins?
As I said, normal releases of it will not likely work because of Unity mono not being shipped with some assemblies. 

If it doesn't work in normal BepInEx plugin at which time all assemblies are usable, it won't work at all. In that case it isn't an issue with BepInEx but simply an issue with the game not coming with necessary assembles for normal JSON.NET.

I'm not sure what you mean by "targeted for Unity runtime" here but you can pull latest JSON.NET source, edit preprocessor flags so that all the extra database/linq support is left out and build. JSON.NET doesn't seem to document available preprocessor flags, but you can check its source.

**Comment by Muchaszewski** [comment]
I have used this plugin with success in the past in Unity until we have changed to 4.X .NET Runtime, and I would assume that this plugin which supposed is "targeted for Unity runtime" would work. https://github.com/SaladLab/Json.Net.Unity3D/tree/v9.0.1

I will look into JSON.NET preprocessor flags and see what else can be done if my current approach is not working for this mod.

**Comment by denikson** [comment]
If it helps, we actually had a similar question about this in our BepInEx Discord. As a result, the person who had the issue made a fork of JSON.NET with unnecessary dependencies deleted and correct preprocessor flags already preset:

https://github.com/Deli-Counter/Deli.Newtonsoft.Json

You should be able to just clone it and build. This was tested on as low Unity version as 5.6 so it should work fine with newer Unity as well.

**Comment by ghorsington** [comment]
This has been tested and it appears to work fine with latest v5-lts and master builds. As such, I'll close the issue for now.

If the issue persists, feel free to create a new ticket.
