### ISSUE TITLE
Console window doesn't show with unity 2020 x64

### ISSUE THREAD

**Issue by nanikit** [BepInEx/BepInEx#179]
**Describe the bug**
I tried using BepInEx with unity 2020.2.1f1 x64 executable but it did not work.

**To Reproduce**
- Install Unity 2020.2.1
- Create test project and change build settings to x64
- Build
- Copy BepInEx 5.4.5.0 to build directory
- Copy some pregenerated `BepInEx/config/BepInEx.cfg`
- Change above config file's `[Logging.Console] Enabled = false` to `Enabled = true`
- Run executable in build directory

**Expected behavior**
Console window appears.

**Screenshots and logs**
```
[Message:   BepInEx] BepInEx 5.4.5.0 - test
[Info   :   BepInEx] Running under Unity v2020.2.1.2559448
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
```

**Desktop:**
- Game and game version: Unity 2020.2.1f1
- BepInEx version: 5.4.5.0

**Comment by nanikit** [comment]
Close, checked normal run with bleeding edge.

**Comment by nanikit** [comment]
Reopen, it wasn't.

**Comment by denikson** [comment]
Greetings!

Unfortunately I am unable to reproduce the issue. Following the steps you provided, I can get BepInEx running normally:

![unity_test](https://user-images.githubusercontent.com/13762037/107407494-66032e80-6b12-11eb-85cd-2b9c423b7832.gif)

Here is my whole setup (test game + BepInEx as seen in the gif above):

[unitytest.zip](https://github.com/BepInEx/BepInEx/files/5953320/unitytest.zip)

Have you tried BepInEx with other games and seen this behaviour persist? I don't know of any games that use Unity 2020 yet but BepInEx has been tested quite extensively with Unity 2019 without issues.

**Comment by nanikit** [comment]
Wierd.. after overwriting by your file I can't reproduce it.  Close this because I can't reproduce it anyway.
