### ISSUE TITLE
Valheim crashes on start

### ISSUE THREAD

**Issue by JoeTheDestroyer** [BepInEx/BepInEx#182]
**Describe the bug**
Installing BepInEx into the game directory (and nothing else) results in the game crashing immediately on startup.

**To Reproduce**
1. Extract "BepInEx_x64_5.4.5.0.zip" to game directory
2. Run "valheim.exe"

**Expected behavior**
Game should run, config file "BepInEx.cfg" should be created.

**Screenshots and logs**
There are no error messages displayed, and no logs are created (by default).

Editing doorstop_config.ini to have "redirectOutputLog=true" gives [output_log.txt](https://github.com/BepInEx/BepInEx/files/5976316/output_log.txt).

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: [Valheim](https://store.steampowered.com/app/892970/Valheim/) 0.143.5 (2021-02-09)
 - UnityPlayer.dll version: 2019.4.16
 - BepInEx version [e.g. 4.0]: 5.4.5.0

**Additional context**
Attempted solutions:

Cleaning the game directory and installing Bleeding Edge "BepInEx_UnityMono_x64_7fa0e8c_6.0.0-be.344.zip" allows the game to run, but no evidence of BepInEx being loaded. "BepInEx.cfg" is not created, no log files are created. Even after manually creating an appropriate "BepInEx.cfg", no log files are created and the console window does not open. No log file is created by Doorstop, even with "redirectOutputLog=true".

Installing "BepInEx_UnityIL2CPP_x64_7fa0e8c_6.0.0-be.344.zip" also allows the game to run, but similar results to above. However, a log file is created by Doorstop when configured: [output_log.txt](https://github.com/BepInEx/BepInEx/files/5976371/output_log.txt)

Last attempted solution was to use newer version of Doorstop (from Bleeding Edge) with release BepInEx. Game starts, but again no evidence that BepInEx is loaded.

Attempted debugging with dnSpy, but crash apparently happens too fast for debugger to attach. (And this is getting pretty far outside my experience.)

**Comment by JoeTheDestroyer** [comment]
Forgot to mention, I can supply/gift a copy of the game if that will help resolving the issue.

**Comment by ghorsington** [comment]
Greetings!

At the moment, Valheim comes with some core game DLLs stripped to the point where BepInEx does not run by default.

Until there is a more permanent solution, check out NeighTools/UnityDoorstop#10 and use normal BepInEx 5.

**Comment by JoeTheDestroyer** [comment]
Thank you.

I didn't think to check Doorstop issues, sorry for the trouble.
