### ISSUE TITLE
valheim linux dedicated server (valheim+ mod) - unable to stop server via ctrl+c/sigint

### ISSUE THREAD

**Issue by xanathos79** [BepInEx/BepInEx#185]
Hi,

I'm opening this issue on both doorstop and BepInEx as I'm not sure on which of these the actual problem is.
The regular Valheim server can be stopped via ctrl+c or by sending a sigint to the PID.
After installing the Valheim+ mod, which contains BepInEx and Doorstop, the server starts as usual but neither control+c on the console or sending a sigint works to gracefully stop the server.
Killing the server via sigterm/sigkill can leave the world data corrupted.

Let me know if you need any additional data, I'm happy to help where possible.
Ticket on Valheim+: https://github.com/nxPublic/ValheimPlus/issues/65

**Comment by ghorsington** [comment]
Fixed in 1339467d4181600c0314ef86199495bdd55f2d08

New binaries containing the fix will be released shortly.

**Comment by ouroborus** [comment]
This issue exists in 5.4.16.0. Unable to shutdown Valheim with crtl+c or sigint.
