### ISSUE TITLE
Linux server command line arguments.

### ISSUE THREAD

**Issue by benocspeter** [BepInEx/BepInEx#186]
Hi, this might be a stupid question, but I am trying to mod a valheim dedicated server with your loader. There is a .sh file which I have to change to set the executable's path. But the problem is that I can not add command line arguments to the path of the executable because the run_bepinex.sh throws error. 

Any idea to go around this?

**Comment by ghorsington** [comment]
Grettings!

Could you provide some more information? What game are you trying to use BepInEx on? What is your distribution?

In future, please use the issue template we provide, as it helps you help us by collecting the important information we can use to actually debug the problem right away.

As for the script, you should be able to normally add the command-line arguments you need for example by [editing `run_bepinex.sh` execution line and adding the arguments you need](https://github.com/BepInEx/BepInEx/blob/v5-lts/doorstop/run_bepinex.sh#L100).

**Comment by Thomseeen** [comment]
Not sure whether it's a BepInEx thing, but I might be struggling with a similar issue using the [`denikson-BepInExPack_Valheim-5.4.701`](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) pack on Ubuntu Server 20.04.
To start my server I use a generic script I use for a couple of game servers, but the same issue arises with the provided script.
If I comment the BepInEx stuff to not have it bootstrap, the command line arguments are read and used as expected. When I uncomment the BepInEx stuff as in the given example, the command line arguments are ignored, the server starts with the default world name and on the default port etc.

```
#!/bin/bash

DIR="/home/gameserver/valheim"
BIN="$DIR/valheim_server.x86_64 -name Salzheim -port 20020 -world Salzheim -password *** -savedir /home/gameserver/valheim/saves"
SN="valheim"

# --- BepInEx
export DOORSTOP_ENABLE=TRUE
export DOORSTOP_INVOKE_DLL_PATH=$DIR/BepInEx/core/BepInEx.Preloader.dll
export DOORSTOP_CORLIB_OVERRIDE_PATH=$DIR/unstripped_corlib

export LD_LIBRARY_PATH=$DIR/doorstop_libs:$LD_LIBRARY_PATH
export LD_PRELOAD=$DIR/doorstop_libs/libdoorstop_x64.so:$LD_PRELOAD
# ---

export LD_LIBRARY_PATH=$DIR/linux64:$LD_LIBRARY_PAT
export SteamAppId=892970

start() {
        cd $DIR
        echo Starting...
        screen -AmdS $SN $BIN
}

stop() {
        cd $DIR
        echo Stopping...
        screen -r $SN -X quit
}

attach() {
        cd $DIR
        screen -r $SN
}

case "$1" in
        start) start ;;
        stop) stop ;;
        restart) stop ; sleep 15; start ;;
        view) attach ;;
        *) echo "usage: $0 start|stop|restart|view" >&2
                exit 1
                ;;
esac
```

**Comment by ghorsington** [comment]
Thanks for the info, I'll give it a test when I can. That being said, I have tested the tailored launch script that comes with the BepInEx Valheim pack and it did work on Ubuntu Server fine (although I used the LTS version).

Meanwhile, I see one small syntax error:
```sh
export LD_LIBRARY_PATH=$DIR/linux64:$LD_LIBRARY_PAT
```

which likely is missing `H` at the end. Though I am fairly sure that shouldn't affect anything in this case.

**Comment by Thomseeen** [comment]
With the most recent Valheim-Sever Version and the 5.4.800 Version of the preconfigured [BepInExPack](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) this seems to have resolved itself. I guess with the original author not replying this can be closed.

**Comment by ghorsington** [comment]
Fair enough, thanks for the info!

I'll close the issue for now. If the issue still persists, please create a new ticket.
