### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by Somamint** [BepInEx/BepInEx#188]
I try to use the installation manual 

   " Extract the archive into a folder. Do not extract into the game folder.
    Move the contents of BepInExPack_Valheim folder into <Steam Location>\steamapps\common\Valheim.
    Run the game via Steam."

But it seems like its not working. No Mod who requires BepInEx does not load.

**Comment by ghorsington** [comment]
Greetings!

From your description you attempted to use [BepInEx Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/5.4.601/) pack off Thunderstore. Version 5.4.601 only have files for Windows and thus do not work on Linux.

The [new 5.4.602 version on Thunderstore](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) now includes necessary files to Linux. The README was also updated with the guide on how to use it.

As such, I am closing this issue as Windows pack was attempted to be used on Linux. If you have new issues, please create a new ticket.
