### ISSUE TITLE
Unable to run in wine (Mac)

### ISSUE THREAD

**Issue by netzpixel** [BepInEx/BepInEx#192]
I'm comming from this ticket: #52
The thing is, I'm using wine, but on Mac. I tried "PlayOnMac" and "Crossover" but I had no luck what so ever with both. I installed mono, tried to run the following command but got an error:

`mono nuget.exe restore -PackagesDirectory .`
`This folder does not contain project files and packages.config files.`

Now I don't know what to do... Can someone help?

**Comment by jy1263** [comment]
the loader worked for me with the prebuilt binaries on wine when adding `winhttp` to dll overides as stated here: https://github.com/BepInEx/BepInEx/issues/52#issuecomment-433602459

**Comment by netzpixel** [comment]
So you play on your Mac with BepInEx and it works? Which wine Tool do you use? Can you maybe write me what exactly you did to get it working?

**Comment by jy1263** [comment]
I just opened up `winecfg` and typed in winhttp and clicked add: 
![image](https://user-images.githubusercontent.com/50583248/115637729-32cfed80-a354-11eb-9bfe-1f3a16cdf2e5.png)
opening up wincfg may be different for you depending on what you're using

**Comment by netzpixel** [comment]
Danke! Hat funktioniert!
