### ISSUE TITLE
Integrate into my idea

### ISSUE THREAD

**Issue by Uber-God** [BepInEx/BepInEx#200]
**Is your feature request related to a problem? Please describe.**

I have no experience coding or modding
**Describe the solution you'd like**

I'd like experienced people to help me. Especially you guys :D
**Describe alternatives you've considered**

Fluxuating Valheimwide Market
**Additional context**

https://github.com/Uber-God/Longship

**Comment by ghorsington** [comment]
Greetings!

This issue tracker is for issues related directly to BepInEx or its development. We would like to keep it that way and not handle tickets related to specific plugins.

If you are seeking help for plugin development, I suggest checking out [BepInEx Plugin Development Docs](https://bepinex.github.io/bepinex_docs/v5.4.4/articles/dev_guide/plugin_tutorial/index.html) or [Valheim Modding Discord](https://discord.gg/RBq2mzeu4z).

I am closing down this issue as not related to BepInEx core development. If you have any other issues, feel free to create a new ticket.
