### ISSUE TITLE
Plugins Folder etc. Not Generating After Install

### ISSUE THREAD

**Issue by bekrause2** [BepInEx/BepInEx#204]
**Describe the bug**

After installation of BepInEx_x64_5.4.8.0 into the game directory for Valheim and running the game no plugins or config folder is available in the BepInEx folder: 
Installation - https://i.imgur.com/TJpv1mY.png
After running Valheim through Steam and the .exe directly - https://i.imgur.com/0u2pkwn.png

**To Reproduce**

Nothing; this is my first time ever attempting installation

**Expected behavior**

After running the game I expect the D:\SteamLibrary\steamapps\common\Valheim\BepInEx to populate with a plugins/config folder etc.

**Screenshots and logs**

changelog.txt reads...
'2 commits since v5.4.7

Changelog (excluding merges):
* (0763065) [ghorsington] Bump version
* (1af1e64) [ghorsington] Update BepInEx.Harmony'

...but I'm pretty sure that doesn't help 

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: Valheim version 0.147.3
 - BepInEx version [e.g. 4.0]: 5.4.8

**Additional context**

I've ensured the game is running in 64bit; tried moving the installation folder of the game into the drive where my OS is installed; tried older stable versions of BepInEx (5.4.7), same result

**Comment by Windows10CE** [comment]
Could you please try installing with https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/

**Comment by bekrause2** [comment]
> 
> 
> Could you please try installing with https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/, as mentioned in #182 Valheim has core DLLs stripped that are needed for BepInEx, this package includes them.

This worked! I thought I searched through here but I guess I didn't recognize those issues as my issue. Thank you so much!
