### ISSUE TITLE
Fallback handler could not load library errors

### ISSUE THREAD

**Issue by BamBam4275** [BepInEx/BepInEx#205]
When I start my server I get all these... I don't know if it is having much of an effect but I thought it would be good to put them here for you to see.

Windows 10

`"Starting server PRESS CTRL-C to exit"
Mono path[0] = 'C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Managed'
Mono config path = 'C:/Games/Steam/steamapps/common/Valheim dedicated server/MonoBleedingEdge/etc'
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/lib/usr/lib/libSystem.dylib
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/lib/usr/lib/libSystem.dylib.dll
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/lib/usr/lib/libSystem.dylib
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/libc.so.6
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/libc.so.6.dll
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/libc.so.6
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/data-0000021D103E8080.dll
[Message:   BepInEx] BepInEx 5.4.8.0 - valheim_server
[Info   :   BepInEx] Running under Unity v2019.4.20.7197120
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/data-0000021D10FC6020.dll
[Message:   BepInEx] Preloader finished
Initialize engine version: 2019.4.20f1 (6dd1c08eedfa)
[Subsystems] Discovering subsystems at path C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.037 seconds
Microsoft Media Foundation video decoding to texture disabled: graphics device is Null, only Direct3D 11 and Direct3D 12 (only on desktop) are supported.
UnloadTime: 0.740100 ms
[Message:   BepInEx] BepInEx 5.4.8.0 - valheim_server
[Info   :   BepInEx] Running under Unity v2019.4.20.7197120
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 4 plugins to load
[Info   :   BepInEx] 4 plugins to load
[Info   :   BepInEx] Loading [Discord Notifier 0.0.3.5]
[Info   :   BepInEx] Loading [Discord Notifier 0.0.3.5]
[Message:Discord Notifier] CryptikLemur's Discord Notifier (v0.0.3.5) has started
[Message:Discord Notifier] CryptikLemur's Discord Notifier (v0.0.3.5) has started
[Info   :   BepInEx] Loading [ServerSideMap 1.2.1.0]
[Info   :   BepInEx] Loading [ServerSideMap 1.2.1.0]
Fallback handler could not load library C:/Games/Steam/steamapps/common/Valheim dedicated server/valheim_server_Data/Mono/data-0000021DBCEC6130.dll
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 1.0.0]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 1.0.0]
[Info   :   BepInEx] Loading [Better Server Config 0.0.80]
[Info   :   BepInEx] Loading [Better Server Config 0.0.80]
[Message:   BepInEx] Chainloader startup complete
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] 03/08/2021 19:17:38: Starting to load scene:start

03/08/2021 19:17:38: Starting to load scene:start`

**Comment by ghorsington** [comment]
Greetings!

This is not an issue: the messages are what mono runtime displays. All BepInEx errors always include word `BepInEx` in it.

From the messages everything works fine. If you want to disable duplicate message writing for the dedicated server, you can go to `BepInEx/config/BepInEx.cfg` and edit

```ini
[Logging.Console]

Enable = true
```

to

```ini
[Logging.Console]

Enable = false
```

Closing this issue as there is no problem judging from the logs. If you have any other issues, feel free to create another issue.
