### ISSUE TITLE
AssemblyCache causes stale version info to get logged

### ISSUE THREAD

**Issue by notpeelz** [BepInEx/BepInEx#206]
After updating a plugin, the cached assembly information becomes stale, causing BepInEx to display the wrong plugin version in the logs:
```
[Info   :   BepInEx] Loading [QoL Fix 0.2.0]
[Message:   QoL Fix] Initializing plugin [0.3.0+gitb688f3a-dirty-dev] (Standalone version)
```

After deleting `BepInEx\cache\chainloader_typeloader.dat`:
```
[Info   :   BepInEx] Loading [QoL Fix 0.3.0+gitb688f3a-dirty-dev]
[Message:   QoL Fix] Initializing plugin [0.3.0+gitb688f3a-dirty-dev] (Standalone version)
```

**Comment by ghorsington** [comment]
Greetings!

Could you provide some more info? What BepInEx version did you use? What game did you test this on?

**Comment by notpeelz** [comment]
BIE: 6.0.0-be.346
Game: GTFO (IL2CPP)

**Comment by ghorsington** [comment]
I wasn't able to reproduce it, however it likely was caused by the file's last edit date not being updated for some reason.

I replaced the date check with a file hash comparison instead which should solve the issue (check 1816981b72bc662fd53df3221f059775256def55). The performance impact is negligible owing to speed of MD5 hashing on modern PCs.

**Comment by notpeelz** [comment]
Ah now I think about it, I had my plugin dll symlinked to the `BepInEx/plugins` folder, which would explain why `File.GetLastWriteTimeUtc` was returning the wrong timestamp. This could be solved by resolving the symbolic link to its real path, but looks like symlink support in .NET is still an [unsolved issue](https://github.com/dotnet/runtime/issues/24271).
Good thinking on using a hash check; it's a much more reliable way of checking if an assembly actually changed (plus it's not subject to filesystem intricacies).
