### ISSUE TITLE
Core Dumped on Ubuntu 20.04

### ISSUE THREAD

**Issue by phellarv** [BepInEx/BepInEx#214]
Game:
Valheim 0.147.3

OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

Running run_bepinex.sh (set -x included for log):
+ executable_name=valheim.x86_64
+ export DOORSTOP_ENABLE=TRUE
+ export DOORSTOP_INVOKE_DLL_PATH=/home/phellarv/.local/share/Steam/steamapps/common/Valheim/BepInEx/core/BepInEx.Preloader.dll
+ [ ! -x  -a ! -x valheim.x86_64 ]
+ doorstop_libs=/home/phellarv/.local/share/Steam/steamapps/common/Valheim/doorstop_libs
+ arch=
+ executable_path=
+ lib_postfix=
+ uname -s
+ os_type=Linux
+ executable_path=/home/phellarv/.local/share/Steam/steamapps/common/Valheim/valheim.x86_64
+ lib_postfix=so
+ [ -n  ]
+ LD_PRELOAD= file -b /home/phellarv/.local/share/Steam/steamapps/common/Valheim/valheim.x86_64
+ executable_type=ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=2a1da7a4ffbc16bad3cab634551563522905febf, stripped
+ arch=x64
+ doorstop_libname=libdoorstop_x64.so
+ export LD_LIBRARY_PATH=/home/phellarv/.local/share/Steam/steamapps/common/Valheim/doorstop_libs:
+ export LD_PRELOAD=libdoorstop_x64.so:
+ export DYLD_LIBRARY_PATH=/home/phellarv/.local/share/Steam/steamapps/common/Valheim/doorstop_libs
+ export DYLD_INSERT_LIBRARIES=/home/phellarv/.local/share/Steam/steamapps/common/Valheim/doorstop_libs/libdoorstop_x64.so
+ /home/phellarv/.local/share/Steam/steamapps/common/Valheim/valheim.x86_64
Found UnityPlayer, hooking into it instead
Found path: /home/phellarv/.local/share/Steam/steamapps/common/Valheim/valheim.x86_64
Aborted (core dumped)

Please advice.

**Comment by ghorsington** [comment]
Greetings!

Thank you for the log. From the looks of it, you're trying to use base BepInEx with Valheim. Unfortunately owing to issues outlined in #182 and NeighTools/UnityDoorstop#10, base BepInEx pack does not work with Valheim. Valheim is to date one of the few games that need a specially bundled BepInEx.

I suggest using [BepInExPack for Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) instead which includes all the required files and a premade launch script. This pack has been verified to work on multiple distros, although I don't remember anyone testing it on Ubuntu 20.04 yet. Nevertheless, it is suggested to use the special BepInExPack for Valheim.

**Comment by ghorsington** [comment]
Closing as the issue appears inactive. If you still have an issue, feel free to create a new issue ticket.
