### ISSUE TITLE
Unable to  loading plugin for Unity2017.1

### ISSUE THREAD

**Issue by hswangrui** [BepInEx/BepInEx#216]
Unable to  find plugin(e.g. UnityExplorer) in Unity2017.1
But It  works  in Unity 2018.3.

Log File:
[Message: Preloader] BepInEx 6.0.0-be.350 - GS
[Message: Preloader] BLEEDING EDGE Build #350 from 07a69cf99b29f123f480ef26eaffe63a6879aa46 at master
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2017.1.0.0
[Message: Preloader] Generating Il2CppUnhollower assemblies
[Info   : Preloader] Generating Il2CppDumper intermediate assemblies
[Info   : Preloader] Executing Il2CppUnhollower generator
[Info   :Unhollower] Reading assemblies... 
[Info   :Unhollower] Done in 00:00:01.6090158
[Info   :Unhollower] Computing renames... 
[Info   :Unhollower] Done in 00:00:00.0394772
[Info   :Unhollower] Creating typedefs... 
[Info   :Unhollower] Done in 00:00:00.0808727
[Info   :Unhollower] Computing struct blittability... 
[Info   :Unhollower] Done in 00:00:00.0033373
[Info   :Unhollower] Filling typedefs... 
[Info   :Unhollower] Done in 00:00:00.0241074
[Info   :Unhollower] Filling generic constraints... 
[Info   :Unhollower] Done in 00:00:00.0018462
[Info   :Unhollower] Creating members... 
[Info   :Unhollower] Done in 00:00:00.6688301
[Info   :Unhollower] Scanning method cross-references... 
[Info   :Unhollower] Done in 00:00:01.0549402
[Info   :Unhollower] Finalizing method declarations... 
[Info   :Unhollower] Done in 00:00:01.2477912
[Info   :Unhollower] 0 total potentially dead methods
[Info   :Unhollower] Filling method parameters... 
[Info   :Unhollower] Done in 00:00:00.1908352
[Info   :Unhollower] Creating static constructors... 
[Info   :Unhollower] Done in 00:00:00.3429853
[Info   :Unhollower] Creating value type fields... 
[Info   :Unhollower] Done in 00:00:00.0513711
[Info   :Unhollower] Creating enums... 
[Info   :Unhollower] Done in 00:00:00.0217058
[Info   :Unhollower] Creating IntPtr constructors... 
[Info   :Unhollower] Done in 00:00:00.0455950
[Info   :Unhollower] Creating type getters... 
[Info   :Unhollower] Done in 00:00:00.0789731
[Info   :Unhollower] Creating non-blittable struct constructors... 
[Info   :Unhollower] Done in 00:00:00.0036166
[Info   :Unhollower] Creating generic method static constructors... 
[Info   :Unhollower] Done in 00:00:00.0306107
[Info   :Unhollower] Creating field accessors... 
[Info   :Unhollower] Done in 00:00:00.9515615
[Info   :Unhollower] Filling methods... 
[Info   :Unhollower] Done in 00:00:01.9196677
[Info   :Unhollower] Generating implicit conversions... 
[Info   :Unhollower] Done in 00:00:00.0093879
[Info   :Unhollower] Creating properties... 
[Info   :Unhollower] Done in 00:00:00.0640325
[Warning:Unhollower] Not performing unstripping as unity libs are not specified
[Info   :Unhollower] Generating forwarded types... 
[Info   :Unhollower] Done in 00:00:00.0017638
[Info   :Unhollower] Writing xref cache... 
[Info   :Unhollower] Done in 00:00:04.5526936
[Info   :Unhollower] Writing assemblies... 
[Info   :Unhollower] Done in 00:00:05.8400670
[Info   :Unhollower] Writing method pointer map... 
[Info   :Unhollower] Done in 00:00:00.3659012
[Info   :Unhollower] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized

**Comment by ghorsington** [comment]
Greetings!

Is that all of the log message? It seems to be cut.

Please send over the entire log. The log can be found in `BepInEx/LogOutput.log`.

**Comment by ghorsington** [comment]
This appears to be a stale issue. If you still encounter similar problems, feel free to create a new issue ticket.
