### ISSUE TITLE
BepInEx 5.4.9 BepInEx.Preloader.dll flagged by Norton Antivirus

### ISSUE THREAD

**Issue by Saik19922** [BepInEx/BepInEx#219]
Using this for Valheim.

One of us is super safe with his downloading behaviour and not-so-tech-savy to trust source code.

Norton is flagging the Preloader.dll as a threat and automatically deleting it. Sadly can't provide the reason as Norton isn't stating any.

Is there any way to resolve this? I know this is because of the behaviour of BepInEx and how it works.

**Comment by ghorsington** [comment]
Greetings!

Thank you for the report. Unfortunately the best option is to ignore the BepInEx DLLs in the anti-virus program for the time being and making sure you get BepInEx only for official sources. The official BepInEx sources for Valheim are

* [BepInExPack for Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/)
* [BepInEx releases on GitHub](https://github.com/BepInEx/BepInEx/releases)

When using other sources, inquire the developer about where they get their binaries from.

Meanwhile, I'll try to send the problematic DLLs over to Norton to see if they can mark it as a false positive. I'll keep the issue open for the time being until there are more updates on the matter,

**Comment by Saik19922** [comment]
Hello!

I've also already submitted to Norton's Customer Support noticing them of a false positive. They claim it's 48 hours but I've submitted at around the same time I've notified you of this.

By now I've also got the reason why Norton is flagging it. It's their generic Reputation reason (WS.Reputation.1) basically stating "Hey, this DLL has weird behaviour (as it's injecting other DLL's to a process, as such modifying behaviour of an existing program) and we don't know it yet". It's also most DLL's in BepInEx that get flagged like that - and most DLL's that have to do with modding in general.

Thanks for the response, however. As long as Norton doesn't process the submission we're "stuck" with not using Mods at all. 

[Here is my submission link for reference.](https://submit.norton.com/?type=CHECK&submission_id=8dfbe568-24d6-4f69-a3de-b191331a9bac)

**Comment by ghorsington** [comment]
It's been quite a while since this happened. I also sent out a report yesterday, but it's too yet to be processed.

Since it's unlikely to change for now, and I haven't received any further reports on this, I'll close the ticket for now. 
If there are any updates or renewed reports, we can reopen the ticket or create a new one.

I'll keep the ticket unlocked so that everyone can still post updates and replies here.
