### ISSUE TITLE
Flag for server side configuration entries

### ISSUE THREAD

**Issue by Algorithman** [BepInEx/BepInEx#220]
With more and more games going client/server, the need for server-side-only configuration arises.
Configuration values which are present on client and server, values provided by the server (the individual mod has to take care of delivering/synchronizing) and being editable (with the Configuration Manager for example) by admins only (also mod responsibility to admin check)

**Describe the solution you'd like**
A simple additional bool value in the config entry base should suffice.
The flag doesn't need to be saved/loaded since the mod's are responsible for the creation.

**Describe alternatives you've considered**
Tried to incorporate the idea into the configuration manager, but without BepInEx config being changed it won't happen.

PS: Hail to the Horse!

**Comment by ghorsington** [comment]
Greetings!

Thank you for your input! Looking at your suggestion I understand that what you are suggesting is

* Ability to add some kind of additional data (a bool flag, for instance) to a configuration entry
* Not doing anything with the value itself on BepInEx side. Instead it is up to the plugin developer to make use of the flag.
* The flag is only present at runtime and doesn't have to be saved to a file

At this moment this is all achievable by using *tags* which is a simple collection of arbitrary objects that you can pass to the config entry upon binding.

One way of passing tags is when using [`Bind<T>(String, String, T, ConfigDescription)`](https://bepinex.github.io/bepinex_docs/v5.4.4/api/BepInEx.Configuration.ConfigFile.html#BepInEx_Configuration_ConfigFile_Bind__1_System_String_System_String___0_BepInEx_Configuration_ConfigDescription_). Simply construct your own [`ConfigDescription(string, AcceptableValueBase, params object[])`](https://bepinex.github.io/bepinex_docs/v5.4.4/api/BepInEx.Configuration.ConfigDescription.html#constructors) and pass any objects you want. 

Example:
```cs
Config.Bind("Section", "Key", "Initial Value", new ConfigDescription("This is a description", null, "tag1", 10, "adminOnly"));
```

This will create config `[Section].Key` with initial value `Initial Value`, description `This is a description` and the following tags:

* `"tag1"`
* `10`
* `adminOnly`

You can query these tags from all `ConfigEntryBase` instances by accessing their [`Description`](https://bepinex.github.io/bepinex_docs/v5.4.4/api/BepInEx.Configuration.ConfigEntryBase.html#BepInEx_Configuration_ConfigEntryBase_Description) property.

As such, BepInEx already has ability to store arbitrary metadata. It can be of any type and have any contents, so you're free to specify its contents and custom handler code. I don't see why there is a need to add an explicit boolean flag into bepin when its logic is all user-defined and does not play role in BepInEx core itself.

For an another example, ConfigurationManager in fact too checks tags of the config entries it finds. The tags are queried in [`ConfigSettingEntry`](https://github.com/BepInEx/BepInEx.ConfigurationManager/blob/master/ConfigurationManager/ConfigSettingEntry.cs#L36)
and the values are parsed in [`SettingEntryBase.SetFromAttributes()`](https://github.com/BepInEx/BepInEx.ConfigurationManager/blob/d402bde665794e1685ec9aaa86abc7d70da36f7e/ConfigurationManager/SettingEntryBase.cs#L135). It is thus not extremely difficult to add additional tag handlers.

**Comment by Algorithman** [comment]
Thx for the fast answer.

I didn't notice the tags. Yes indeed there is no need for changes inside BepIn.

Thx again and have a nice sunday
