### ISSUE TITLE
Game stuck at loading screen

### ISSUE THREAD

**Issue by smallcuber** [BepInEx/BepInEx#224]
**Describe the bug**
The game always gets stuck at the loading screen.

**To Reproduce**
r2modman 3.1.10
BepInExPack 5.4.9
HookGenPatcher 1.2.0
R2API 3.0.7

**Screenshots and logs**

Console output:
[Message:   BepInEx] BepInEx 5.4.9.0 - Risk of Rain 2
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.Loader 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.1.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [R2API.Patcher 1.0.0.0]
[Info   :   BepInEx] 4 patcher plugins loaded
[Warning:   BepInEx] Tried to load duplicate assembly Assembly-CSharp.dll from Managed folder! Skipping...
[Warning:   BepInEx] Tried to load duplicate assembly Assembly-CSharp_2019_12_22.dll from Managed folder! Skipping...
[Warning:   BepInEx] Tried to load duplicate assembly Assembly-CSharp_2020_04_04.dll from Managed folder! Skipping...
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   MonoMod] Collecting target assemblies from mods
[Message:   BepInEx] Preloader finished
[Info   :   Console] Could not resolve type with token 01000014 (from typeref, class/assembly Mono.Cecil.GenericParameterConstraint, Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e)
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [R2API 3.0.7]
[Error  :     R2API] ************************************************************************
[Error  :     R2API] *                                                                      *
[Error  :     R2API] *                               !ERROR!                                *
[Error  :     R2API] *                The patch of R2API seems to be missing                *
[Error  :     R2API] *                 Please make sure that a file called:                 *
[Error  :     R2API] *                          R2API.Patcher.dll                           *
[Error  :     R2API] *      is present in the Risk of Rain 2\BepInEx\patchers\ folder       *
[Error  :     R2API] *If you don't have this folder or the dll, please download BepInEx again from the     *
[Error  :     R2API] * thunderstore and make sure to follow the installation instructions.  *
[Error  :     R2API] *                                                                      *
[Error  :     R2API] ************************************************************************
[Info   :     R2API] Enabling R2API Submodule: ILLine
[Error  : Unity Log] Skin skinCrocoDefault (RoR2.SkinDef) has an empty renderer field in its rendererInfos.
[Message:   BepInEx] Chainloader startup complete
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   :   Console] Facepunch.Steamworks Arch: x64
Setting breakpad minidump AppID = 632360
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198094031101 [API loaded no]
[Info   :   Console] Searching for compatible XInput library...
[Info   :   Console] Found Xinput1_4.dll.
[Info   : Unity Log] Initializing Mod System...
[Info   : Unity Log] Mod System initialized.
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   : Unity Log] Setting current language to "en"
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.Console.Awake () (at <c36b0eadbe0a4afc83f7e70a917dc2c1>:IL_0016)
UnityEngine.GameObject:AddComponent()
RoR2.RoR2Application:OnLoad()
RoR2.RoR2Application:Awake()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.SystemInitializerAttribute.Execute () (at <c36b0eadbe0a4afc83f7e70a917dc2c1>:IL_000B)
RoR2.RoR2Application.OnLoad () (at <c36b0eadbe0a4afc83f7e70a917dc2c1>:IL_01BA)
RoR2.RoR2Application.Awake () (at <c36b0eadbe0a4afc83f7e70a917dc2c1>:IL_005D)

[Info   : Unity Log] Active scene changed from  to splash
[Info   : Unity Log] Loaded scene splash loadSceneMode=2
[Info   : Unity Log] "set_scene" is not a recognized ConCommand or ConVar.
[

![image](https://user-images.githubusercontent.com/12606285/113952831-7703af80-97e4-11eb-89b5-37c798dfaa36.png)

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: 
1.1.0.1
 - BepInEx version [e.g. 4.0]: 
BepInExPack 5.4.9

**Comment by ghorsington** [comment]
Greetings!

Thank you for providing the log and information about the issue!  
Looking at your log, there are errors in some plugins. Unfortunately we cannot provide plugin-specific support here, as BepInEx is a general-purpose Unity modding framework aimed at supporting various Unity games. As such, we provide help with BepInEx-related issues, but we are not able to track issues related to specific plugin setups.

Instead, I suggest seeking help from RoR2 Modding Discord: https://discord.gg/VREqSF 
Provide them the same error log you sent here and I'm sure they will be able to solve your plugin-related problem.

I'll close this issue for now, but don't hesitate to create another should you need further help or a pointer where to get more information.
