### ISSUE TITLE
"Skipping over type [class] as no metadata attribute is specified"

### ISSUE THREAD

**Issue by MajesticPeter** [BepInEx/BepInEx#232]
I have a mod that over the course of development I decided to split into multiple .cs files as the code was getting too long. The problem is that BepInEx ignores them and my mod doesn't work. I get a warning at load time saying "Skipping over type [myclass] as no metadata attribute is specified". The metadata attribute that it's referring to is the [BepInPlugin] correct? How am I supposed to set it up? If I add [BepInPlugin] to every parent class in a .cs file and use the same metadata, it gets ignored because a "newer version was found". If I put a different version, it loads the same mod twice. Once for each .cs or each metadata attribute. 

How do I reference the metadata specified in the main .cs file? I just want to load a .dll with multiple .cs files. The guide doesn't mention how this is done and I've been struggling to get it working for days now.

**Comment by ManlyMarco** [comment]
Why are you trying to load multiple copies of your plugin? In almost all cases you should only have one entry point that inherits BaseUnityPlugin and has the attribute.

Or are you trying to use the BaseUnityPlugin base class for utility classes? If you are making your own classes then either don't inherit from anything, or inherit from MonoBehavior.

Link to your code if it's on github or come talk on the discord server.

**Comment by MajesticPeter** [comment]
The problem was that I was inheriting from the main class that inherits from BaseUnityPlugin. It caused a chain reaction. Just a dumb mistake on my part.
