### ISSUE TITLE
No Plugin Injection In Bloons TD 6

### ISSUE THREAD

**Issue by CallMeEchoCodes** [BepInEx/BepInEx#234]
**Describe the bug**
No Plugin Injection In Games

**To Reproduce**
1. Install BepInEx On BloonsTD6
2. Add the correct unity libs to Bepinex/unity-libs/
3. Add The Melonloader Plugin (seems to not effect the outcome)
4. Add a Melonloader Mod (seems to not effect the outcome)

**Expected behavior**
Melonloader To Load And Plugins To Work

**Screenshots and logs**
Log Is On Pastebin At https://pastebin.com/zqVe0pkN

**Desktop (please complete the following information):**
 - Game and game version [Bloons TD 6 25.0]: 
 - BepInEx version [Bleeding Edge Build #362](https://builds.bepis.io/projects/bepinex_be)]: 

**Additional context**
None

**Comment by mjdegue** [comment]
I'm having something similar with Rogue Legacy 2, BepInEx loads the plugin but it doesn't patch the methods at all :/

**Comment by js6pak** [comment]
Latest BepInEx seems to be working fine with Bloons TD 6 which I'm guessing could have been a side effect of updating il2cppdumper

**Comment by ghorsington** [comment]
This indeed appears to work fine after updates to Il2CppUnhollower and Il2CppDumper. As such, I'll close the issue.

If you have similar issues, feel free to create a new ticket.
