### ISSUE TITLE
Koikatsu/Koikatu BepinEx can't read mods

### ISSUE THREAD

**Issue by KYplayerX** [BepInEx/BepInEx#236]
**Describe the bug**
I downloaded Koikatsu BetterRepack RX8. When I try to open the game It will start normally and I can download characters and use them in short I can play it So I downloaded some mod Like pmxeditor when I open The mod it doesn't work. Some mods that don't need Bepinex it work.

**To Reproduce**

< A short description of what I did for the bug to happen >

I tried to download HFpatch and didn't work too:( And I tried to look at output log and preloader log and Outdoor_Config ,The only thing I understood in preloader log is : ("System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for BepInEx.Preloader.Preloader ---> System.UnauthorizedAccessException: Access to the path "D:\Games\[ScrewThisNoise] Koikatsu BetterRepack RX8\BepInEx\config\BepInEx.cfg" is denied") I think the problem from this

**Expected behavior**
Expected behavior I can export models from pmxeditor

**Screenshots and logs**
output_log : https://pastebin.com/h17bSf6u

Preloader_log : https://pastebin.com/JP3WLVZ1

doorstop_config : https://pastebin.com/2dNDuWLX

InitSetting.config : https://pastebin.com/P5Rc4NFv

 - Game : [ScrewThisNoise] Koikatsu BetterRepack RX8
 - Game version : Sorry I don't know where to get it but I downloaded it in march in the official site
 - BepInEx version [e.g. 4.0]: It downloaded automatically with this repack

**Additional context**
There is translation in BepinEx folder but it doesn't work too It writes it with japan language

**Comment by WildCard65** [comment]
That error means that the game can't read/write BepInEx's configuration file, here's the possible reasons why:

1. The configuration file has invalid permissions (unlikely unless you changed them after last successful load)
2. The config folder is missing/has invalid permissions
3. Your BepInEx install is corrupted and you must re-install BepInEx

**Comment by ghorsington** [comment]
Greetings!

Sorry for the late reply; I meant to answer you earlier.
Right now, it seems like your installation is broken. Like @WildCard65 mentions, the permissions for BepInEx files appear to be incorrect.

I suggest first trying to fix your folder and file permissions for your game folder. [Here is a basic guide with images that I found quickly with a bit of Googling](https://www.tenforums.com/tutorials/85640-set-unset-read-only-attribute-files-folders-windows-10-a.html). Make sure your game folder and all files inside it are not read-only.

I suggest joining [Koikatsu Discord server](https://discord.gg/hevygx6) and asking for technical assistance there.
Koikatsu community has also premade BepInEx plugin packs and installers that can automatically fix your game (such as the [HFPatch](https://github.com/ManlyMarco/KK-HF_Patch)). I will close this issue since you're better off seeking technical assistance from the game community directly.

If you have any other new issues or the issue persists, please create a new issue ticket here.

**Comment by KYplayerX** [comment]
> That error means that the game can't read/write BepInEx's configuration file, here's the possible reasons why:
> 
> 1. The configuration file has invalid permissions (unlikely unless you changed them after last successful load)
> 2. The config folder is missing/has invalid permissions
> 3. Your BepInEx install is corrupted and you must re-install BepInEx

Thank you for your help I followed your steps and nothing worked : 

Step 1 : When first time I download this game It had this problem and didn't change anything expect Some mods export folder dir like KSOS and Pmxtool

Step 2 : Bepinex.cfg is existed it's in bepinex\config and Invalid permissions I just unchecked readonly

Step 3 : I reinstall and Updated to last version and nothing happened

**Comment by KYplayerX** [comment]
> Greetings!
> 
> Sorry for the late reply; I meant to answer you earlier.
> Right now, it seems like your installation is broken. Like @WildCard65 mentions, the permissions for BepInEx files appear to be incorrect.
> 
> I suggest first trying to fix your folder and file permissions for your game folder. [Here is a basic guide with images that I found quickly with a bit of Googling](https://www.tenforums.com/tutorials/85640-set-unset-read-only-attribute-files-folders-windows-10-a.html). Make sure your game folder and all files inside it are not read-only.
> 
> I suggest joining [Koikatsu Discord server](https://discord.gg/hevygx6) and asking for technical assistance there.
> Koikatsu community has also premade BepInEx plugin packs and installers that can automatically fix your game (such as the [HFPatch](https://github.com/ManlyMarco/KK-HF_Patch)). I will close this issue since you're better off seeking technical assistance from the game community directly.
> 
> If you have any other new issues or the issue persists, please create a new issue ticket here.

How can I ask them for technical assistance

**Comment by WildCard65** [comment]
Another thing to check for is if the file or any parent folders is hidden, Windows treats hidden files as files you shouldn't mess with unless you know what you are doing.
