### ISSUE TITLE
Error when starting Bepin with mods

### ISSUE THREAD

**Issue by Quickshadow2003** [BepInEx/BepInEx#237]
**Describe the bug**
[Error  : Unity Log] FileNotFoundException: Could not find file "G:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\plugins\Images\WindBar.png"
Stack trace:
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.File.OpenRead (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.File.ReadAllBytes (System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
SailingOverhaul.SailingOverhaul.HudAwakeOnFix (On.Hud+orig_Awake orig, Hud self) (at <d54860724bda4e6bbee7843ffb0365bc>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Hud::Awake>?-2002824832(Hud)
UnityEngine.Object:Instantiate(GameObject, Transform)
InstantiatePrefab:Awake()
>

**To Reproduce**
Started game after update last week with mods on Vortex

**Expected behavior**
Prior to update, this didn't occur.
[ImprovedDropTables-445-1-3-0-1617653534.zip](https://github.com/BepInEx/BepInEx/files/6362360/ImprovedDropTables-445-1-3-0-1617653534.zip)

**Desktop (please complete the following information):**
 - Valheim, bepinex 5.4.9

**Additional context**

**Comment by ghorsington** [comment]
Greetings!

Please excuse the late response. Judging by the error, you're missing a file name in `BepInEx\plugins\Images\WindBar.png`. This is clearly a plugin issue and not something related to BepInEx.

When games update, some plugins may break. I suggest updating your plugins and, if needed, contact the plugin developer of SailingOverhaul. 
BepInEx is a general-purpose modding framework, and thus we can't, unfortunately, help with game-specific issues. I suggest talking about it on the game's own forums. If you have issues with plugins, [Valheim Modding Discord](https://discord.gg/RBq2mzeu4z) has people who know about Valheim modding.

I'm closing this issue as there is nothing that we can do to fix it.
