### ISSUE TITLE
New Valheim version incompatible with Bepinex

### ISSUE THREAD

**Issue by f1ames0ff** [BepInEx/BepInEx#246]
During load bepinex:
`[Error  : Unity Log] Unable to find method SendPreWillRenderCanvases in [UnityEngine.UIModule.dll]UnityEngine.Canvas`

**Comment by ghorsington** [comment]
Greetings!

I assume you're using [BepInExPack Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) on Thunderstore. Valheim was recently updated to use a newer Unity version which has slightly updated Unity DLLs which conflict with the unstripped ones that are shipped with the pack (refer to NeighTools/UnityDoorstop#10 for more info on why this is done for Valheim).

[BepInExPack Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) was just updated to version 5.4.1001 which includes updated DLLs. Please update if you haven't done so yet.

**Comment by holgero** [comment]
Wow! What a fast reaction. I just noticed my installation didn't start anymore and nearly the first thing I find on the web is the already closed issue about this. Kudos!

**Comment by f1ames0ff** [comment]
@ghorsington Thank you for such a quick response!

**Comment by AlexandruVerenca** [comment]
I'm having the same exact issue with the latest version installed.

**Comment by DeadSix27** [comment]
I think in the latest version (Valheim 209.5) it stopped working again and needs new corlibs? I downloaded Unity and picked version 2020.3.0f1 which seemed to be the version valheim uses now, however even after getting together all the libs from the unity install and replacing them in the corlib folder it still crashes.. but it did at least show up the bepin console..

but I probably just used a wrong version or so.. this stacktrace was logged:

```
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFAC00C7611)
0x00007FFAC00C7611 (UnityPlayer) (function-name not available)
```

**Comment by ghorsington** [comment]
> I think in the latest version (Valheim 209.5) it stopped working again and needs new corlibs? I downloaded Unity and picked version 2020.3.0f1 which seemed to be the version valheim uses now, however even after getting together all the libs from the unity install and replacing them in the corlib folder it still crashes.. but it did at least show up the bepin console..

The latest version is only available via public-test branch. You can manually download and extract the correct Unity core libraries from <https://unity.bepinex.dev/> until the update is officially released. Once the update is officially live, [BepInExPack for Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) will be updated to include the new core libraries automatically.

**Comment by DeadSix27** [comment]
> you can manually download and extract the correct Unity core libraries from https://unity.bepinex.dev/

The site only offers me basic basic mono libraries (e.g System*) and UnityEngine.dll, but the game has way more unstripped libraries in the folder, where would I aquire those ? In other words, what do the version numbers on that site represent? 3.4.x is not a Unity engine version right?

**Comment by MrLawbreaker** [comment]
> The latest version is only available via public-test branch. You can manually download and extract the correct Unity core libraries from https://unity.bepinex.dev/ until the update is officially released. Once the update is officially live, [BepInExPack for Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) will be updated to include the new core libraries automatically.

The Game Update is now out, waiting for the library update

**Comment by Alex134831** [comment]
pls some attention to fixing BepInEx on arm64
