### ISSUE TITLE
BepInEx version 3.2 makes game update cdp05v25 not work.

### ISSUE THREAD

**Issue by chlorine03** [BepInEx/BepInEx#26]
I'm not sure if it's an issue of incompatible plugins or something else, but after updating to update 05v25, Koikatu.exe starts up then instantly terminates itself after applying BepInEx.Patcher. I can confirm BepInEx is the issue here because after I re-applied the game update patch, Koikatu.exe starts working fine.

Now the main problem is that I need to roll back the game version to apply BepInEx to load the save game, because not applying BepInEx makes the game unable to load the save file. After that I'm not even sure if re-saving the game with BepInEx 3.2 would make the game recognize the save.

**Comment by bbepis** [comment]
It may be plugin related. Try deleting all your plugins and see if the game still refuses to load.

If you have done any hardmods (especially Patchwork), that may also be the reason for issues.
If deleting plugins doesn't cause it to work, you may need to get completely fresh Managed folder(s).

**Comment by chlorine03** [comment]
After deleting everything in the plugins folder and using only files from the r4 package, things seem to have started working again. I was able to start up the game and load the save files. So it's likely that it's a plugin related error, possibly belonging to the debug plugin. I'll ask the maker of the plugin about this problem. Thanks for the help.
