### ISSUE TITLE
Error With Honey Select 2

### ISSUE THREAD

**Issue by Scy550** [BepInEx/BepInEx#265]
I am using v5.0 with Honey Select 2 and get this error.
System.BadImageFormatException: Could not resolve field token 0x04000018, due to: Could not load type of field 'BepInEx.Preloader.RuntimeFixes.UnityPatches:<HarmonyInstance>k__BackingField' (0) due to: Could not resolve type with token 01000033 (from typeref, class/assembly HarmonyLib.Harmony, 0Harmony, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:0Harmony, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null type:HarmonyLib.Harmony member:(null) signature:<none> assembly:C:\illusion\HS2\BepInEx\core\BepInEx.Preloader.dll type:UnityPatches member:(null) signature:<none>
File name: 'BepInEx.Preloader'
  at BepInEx.Preloader.Patching.AssemblyPatcher.PatchAndLoad (System.String directory) [0x00060] in <baccfc0f2a9d4f1fb34653c1eb3ab62a>:0 
  at BepInEx.Preloader.Preloader.Run () [0x001f4] in <baccfc0f2a9d4f1fb34653c1eb3ab62a>:0

**Comment by ghorsington** [comment]
Greetings!

The problem appears to come from a bad install. It could be possible that either you installed two BepInEx versions on top of each other or have some incompatible plugin.

I suggest doing a clean install of BepInEx. That is, move out your BepInEx folder out of the game folder and instead install the latest BepInEx from the releases. You might have to reconfigure it to show the console if you had it enabled previously. 

As far as HS2 is concerned, you might also want to consider asking in [IllusionSoft Discord Server](https://discord.gg/illusionsoft). They might have some premade BepInEx distributions that are tailored for the game.

**Comment by ghorsington** [comment]
This appears to be a stale issue now. As such, I'm closing it.

If you have any further issues, feel free to create a new ticket.
