### ISSUE TITLE
No Il2Cpp Unity on stable release page

### ISSUE THREAD

**Issue by bernhard-eiling** [BepInEx/BepInEx#266]
No `Il2Cpp Unity` stable `5.X` release is listed on the release page:
https://github.com/BepInEx/BepInEx/releases

Bleeding edge releases only contain `6.X` releases
https://builds.bepis.io/projects/bepinex_be

Could you please add a stable `5.X Il2Cpp Unity` release to the release page?
Thanks!

**Comment by ghorsington** [comment]
Greetings!

There reason there are not Il2Cpp releases for BepInEx 5 is simply because there is

**Comment by bernhard-eiling** [comment]
Ah ok thanks!
