### ISSUE TITLE
BepInEx doesn't follow symbolic links if that's the executable

### ISSUE THREAD

**Issue by TheAwesome98-Real** [BepInEx/BepInEx#273]
If the executable the shell script points at is a symlink, it won't execute it, it just tells you what it is.

**Comment by ghorsington** [comment]
I added an experimental fix in b2b0e5b5ed65efbf386514f591755af7cb6f9d0e. From the looks of it, [there is no simple way to resolve symlinks on both Linux and macOS](https://stackoverflow.com/a/42918).

If the issue still appears in the upcoming BepInEx version, feel free to create a new issue ticket.

**Comment by GeBo1** [comment]
This fails on Mac if you have a relative symlink in the chain somewhere.

I tested `resolve_executable_path` using:
- Mac readlink
- GNU readlink
- relative links
- absolute links
- files that aren't links
- chains containing both relative and absolute links
- paths with spaces
- paths without spaces

```
abs_path() {
    echo "$(cd "$(dirname "$1")" && pwd)/"$(basename "$1")
}

_readlink() {
    # relative links with readlink (without -f) do not preserve the path info 
    local abs_path="$(abs_path "$1")"
    local link="$(readlink "${abs_path}")"
    [[ "$link" == /* ]] || link="$(dirname "$abs_path")/$link"
    echo "$link"
}

resolve_executable_path () {
    local executable_path="$(abs_path "${executable_path}")"
    
    while [[ -L "${executable_path}" ]]; do 
        executable_path=$(_readlink "${executable_path}"); 
    done
    echo "${executable_path}"
}

# ...

executable_type="$(LD_PRELOAD="" file -b "$(resolve_executable_path "${executable_path}")")";
```

**Comment by ghorsington** [comment]
Thanks! I modified your snippet a little for better POSIX compliance and added it to the script.
