### ISSUE TITLE
BepinEx sh script not working with exe & proton

### ISSUE THREAD

**Issue by Exitiumundos** [BepInEx/BepInEx#277]
**Describe the issue**
the shell script does not seem to work exe executables.

**Comment by ghorsington** [comment]
Greetings!

.exe executables mean that the game is originally compiled for Windows and not Linux/macOS. In this case, you need to use Wine/Proton and BepInEx for Windows to run the game.

I updated the script to mention this separately in 3e713195054253c23a9474af14d52c50ff37f65b. You can follow the guide on [BepInEx docs](https://docs.bepinex.dev/articles/advanced/steam_interop.html#protonwine) on how to use Wine/Proton on Linux to work with BepInEx.

If you have any further questions, feel free to create a new ticket.
