### ISSUE TITLE
Is there any plugin auto update mechanism?

### ISSUE THREAD

**Issue by hanabi1224** [BepInEx/BepInEx#278]
**Describe the issue**
Just what to figure out what's the best way to detect and install plugin updates, I think there's a feature in unity-mod-manager to do so, mod author can specify version info + version check url + download url in mod manifest and users can get notified in umm's built-in management UI when there's an update, thanks.

**Comment by ManlyMarco** [comment]
There is no generic update mechanism, each of the major modding communities use their own setups like Thunderstore, KKManager, nexusmods. Notifications for plugin updates are handled by posting plugin builds in github releases with correct tags.

**Comment by ghorsington** [comment]
Greetings!

This question appears to be answered. As Marco said, we allow the community to use their own game and community-specific setups for managing mods. At the moment, [Thunderstore](https://thunderstore.io/) is one of the biggest plugin and mod repositories for BepInEx and a dozen of games. Thunderstore is just one solution, and we don't limit people to just one solution.

I'll close the issue as it's answered. If you have any more questions, feel free to create a new issue ticket.
