### ISSUE TITLE
BepInEx doesn't load correctly

### ISSUE THREAD

**Issue by pzzzl** [BepInEx/BepInEx#281]
**Describe the issue**

BepInEx isn't loading correctly on newer versions. Releases tested: 5.4.13, 5.4.12 & 5.4.11.

**To Reproduce**

**I'VE ONLY TESTED ON CARX (Steam)**. I've also made a Python installer to BepInEx and KiNO mod (in which i'm facing the issues) to simplify the process.

1. Download BepInEx into game's root folder.
2. Open the game to generate `plugins` folder and other ones related to the first execution.
3. **Folders are not created.**

I've reinstalled BepInEx a lot of times, including `vcredist_x64.exe`.

**Expected behavior**

The automatically generated folders should've been created. Also I changed `redirectOutputLog` to `true` on `doorstop_config.ini` and the log didn't pop out.

**Screenshots and logs**

There's no visual confirmation of the error, since nothing happens on game load.

**Desktop (please complete the following information):**
 - Game and game version: CarX Drift Racing Online 2.11.1.
 - BepInEx version: 5.4.13, 5.4.12 & 5.4.11.

**Additional context**

I've did this same process lot of times before, so it's not like a first time error 😅 As I said above, it was even working on my personal BepInEx/KiNO Installer (which is basically a bundle) and have worked lots of times. I don't know if this could help, but the issue started specifically yesterday to this moment.

**Comment by ManlyMarco** [comment]
Post the game's output_log or LogOutput.log from the bepinex folder.

**Comment by pzzzl** [comment]
**Update**

I give it some time, tried again and it worked out of nowhere. Same installation process, same files. The release that made it work was the latest one [5.4.13].

Changing `redirectOutputLog` to `true` again made it pop the log correctly.

Also I did installed the other mod I was trying to and it loaded succesfully.

Looked like magic. 😄

Thanks @ManlyMarco!
