### ISSUE TITLE
Mods don't run

### ISSUE THREAD

**Issue by FireMeshCloud** [BepInEx/BepInEx#291]
### What happened?

Hi, I'm newer to mods, and I don't now if I'm the only newb on who that's fall, but I have installed BepInEx
Within SWPT, but nothing happens, any new folder in the folder "BepInEx", then any mods can be installed,
Please Help Me x_x"

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
- OS: Windows 10, latest version I think
- BepInEx: 5.4.14
- Game: She Will Punish Them Remastered
```

**Comment by ghorsington** [comment]
Greetings!

BepInEx appears to work just fine on She Will Punish Them:

![image](https://user-images.githubusercontent.com/13762037/128417799-09a9266e-0802-460c-8df5-f7af073d6cde.png)

As this is lacking further logs and information, I'm converting this issue into a discussion.
