### ISSUE TITLE
I had to set dllSearchPathOverride=BepInEx/core in doorstop_config to make it work

### ISSUE THREAD

**Issue by Raicuparta** [BepInEx/BepInEx#304]
### What happened?

I was always getting errors when using plain BepInEx with no mods in a Unity 2017.4 game, BepInEx wouldn't load (see attached logs).
  
Then I set `dllSearchPathOverride=BepInEx/core` in `doorstop_config.ini`, and it boots fine. I never had to do this before, so not sure why I would need it in this game. But never saw anywhere suggesting to try this.
  

### Steps to reproduce

Follow instructions to install BepInEx in Outer Wilds, try to run it.

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'HarmonyLib.Harmony' from assembly '0Harmony, Version=2.5.4.0, Culture=neutral, PublicKeyToken=null'.
  at BepInEx.Preloader.PreloaderRunner.PreloaderMain () [0x00000] in <filename unknown>:0 
  at BepInEx.Preloader.PreloaderRunner.PreloaderPreMain () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at BepInEx.Preloader.Entrypoint.Main () [0x00000] in <filename unknown>:0
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: BepInEx 5.4.15
- Game: Outer Wilds (Unity 2017.4)
```

**Comment by ghorsington** [comment]
Greetings!

I just tested BepInEx 5.4.15 and it works fine with the default configuration in Outer Wilds. Given the error message and your "fix", it is almost certain that you may have some game libraries mixed or misplaced. This could happen if you, for example, installed some other mod loader or misplaced BepInEx files in the wrong folder.

If you have only BepInEx installed, you should only have the following files in your game folder:

![image](https://user-images.githubusercontent.com/13762037/134707913-4d923a03-15e5-4b2f-8e44-3d01994bbd92.png)

Moreover, your `OuterWilds_Data/Managed` folder should be clean and not contain BepInEx libraries like `0Harmony.dll`. Stock and clean `Managed` folder in Outer Wilds has only 117 DLLs. 

The fact that you have to use Doorstop's `dllSearchPathOverride` implies that you have some extra libraries in the wrong folder which overrides the default DLL search path. The option forces the DLL search order to prioritise a specific folder and it is meant primarily for unstripping games (like documented in Doorstop's configuration).

I highly suggest making sure your game folder is clean and stock before installing BepInEx. If you are unsure about your `OuterWilds_Data/Managed` folder, delete it and verify the integrity of game files on Steam (which will cause Steam to regenerate the original files).

**Comment by Raicuparta** [comment]
You're right, I fucked it up somehow. No idea what I did though since I had just done a fresh install before installing BepInEx. Thanks for the help and sorry if I wasted too much of your time!

**Comment by Raicuparta** [comment]
Turns out it was because of Steam Game Theater, a VR feature that plays flat games in a VR theater. Apparently if the game runs through that, BepInEx won't start at all for some reason.
