### ISSUE TITLE
Cannot identify executable type (got )!

### ISSUE THREAD

**Issue by KimoriWasTaken** [BepInEx/BepInEx#333]
### What happened?

Got a [Valheim Server](https://pimylifeup.com/raspberry-pi-valheim-server/) working on my raspberrypi and tried to implement [ValheimPlus](https://www.nexusmods.com/valheim/mods/4?tab=description) but it spits out this error message and I can't seem to figure out [how to fix it](https://github.com/valheimPlus/ValheimPlus/blob/development/resources/unix/start_server_bepinex.sh).

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
./start_server_bepinex.sh: 73: file: not found
Cannot identify executable type (got )!
Please create an issue at https://github.com/BepInEx/BepInEx/issues.
```

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Kernel: Linux 5.10.63-v8+
- Architecture: arm64
- BepInEx: ValheimPlus
- Game: Valheim Server
```

**Comment by ghorsington** [comment]
Greetings!

ValheimPlus has its own edited startup script. As such, it would make more sense to make an issue at [valheimPlus/ValheimPlus](https://github.com/valheimPlus/ValheimPlus). They unfortunately still kept our error message that asks to report the issue to our repo, but in general ValheimPlus-related issues are better asked first in ValheimPlus repo.

That being said, here are some points related to Raspberry Pi and Valheim:

* `file: not found` means `file` command is not installed. You can install it via `apt`.
* Raspberry Pi's processor is built on ARM/ARM64 architecture, while Valheim Dedicated Server and BepInEx only have x86 and x64 (x86_64) builds. This means that you cannot run Valheim nor BepInEx on a Raspberry Pi unless you have some kind of emulator setup. Even then I kind of doubt you can run BepInEx as bootstrapping it relies on some x64 quirks.

**Comment by KimoriWasTaken** [comment]
Thanks for your reply, I got most of it working but something seems to cause a sigsegv and after another day of trying things out I gave up on it except you can point me in the right direction...

Using vanilla bepinex start_server_bepinex.sh for valheim I get
`Found UnityPlayer, hooking into it instead
3844|SIGSEGV @0x7fa01f51ac (???(0x7fa01f51ac)) (x64pc=0x7fa0a2ffd7/./doorstop_libs/libdoorstop_x64.so:"./doorstop_libs/libdoorstop_x64.so/check_rel", rsp=0x7f9fac2240, stack=0x7f9f2c3000:0x7f9fac3000 own=(nil) fp=0x7f9fac2330), for accessing 0x1fb658 (code=1/prot=0), db=0x7124a000(0x7fa01f5170:0x7fa01f5308/0x7fa0a2ffb3:0x7fa0a30047/./doorstop_libs/libdoorstop_x64.so/check_rel:clean, hash:980bcde/980bcde) handler=(nil)
Segmentation fault
`

And using valheimplus start_server_bepinex.sh I get:
`Found UnityPlayer, hooking into it instead
3805|SIGSEGV @0x7f9763c1ac (???(0x7f9763c1ac)) (x64pc=0x7f97e74fd7//home/pi/valheim_server/doorstop_libs/libdoorstop_x64.so:"/home/pi/valheim_server/doorstop_libs/libdoorstop_x64.so/check_rel", rsp=0x7f96f090b8, stack=0x7f9670a000:0x7f96f0a000 own=(nil) fp=0x7f96f091a8), for accessing 0x1fb658 (code=1/prot=0), db=0x97e1d1b0(0x7f9763c170:0x7f9763c308/0x7f97e74fb3:0x7f97e75047//home/pi/valheim_server/doorstop_libs/libdoorstop_x64.so/check_rel:clean, hash:980bcde/980bcde) handler=(nil)
Segmentation fault
`
