### ISSUE TITLE
Game crashing on launch with only BepInEx installed

### ISSUE THREAD

**Issue by win32kbase** [BepInEx/BepInEx#340]
### What happened?

Installing BepInEx and launching Ratz Instagib instantly crashes the game with an access violation in mono.dll, can provide mono.dll if needed

![notepad_gESecjLZKY](https://user-images.githubusercontent.com/6201484/144174973-40fa1743-3e5b-4432-9a0f-ab16a1452659.png)

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
BepInEx Log: None
Preloader error log: None
Unity Player log: https://pastebin.com/qfjqUXRf
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: 5.4.17.0
- Game: Ratz Instagib (32 bit standard Mono assembly)
```

**Comment by ghorsington** [comment]
Greetings!

Unity 4 is one of the older Unity versions that can have issues with the default BepInEx setup. Have you tried to follow the [troubleshooting guide](https://docs.bepinex.dev/articles/user_guide/troubleshooting.html#unity-5-and-older) and try changing the entry point? Also, you might check that the game has the necessary DLLs to run BepInEx.

**Comment by win32kbase** [comment]
Changing the entrypoint worked, thanks! Maybe the troubleshooting guide should be added to Resources on the readme so it's a bit easier to find.
