### ISSUE TITLE
Loading an assembly with a name other than Gameassembly.dll 

### ISSUE THREAD

**Issue by dhlrunner** [BepInEx/BepInEx#354]
### Describe your proposal

Sorry if this is a weird question... The game I want to run basically uses the encrypted/packed `Gameassembly.dll` file, and when the game is run, the decrypted dll is loaded into memory by the decryption library. I made a hook mod that dumps the decrypted `Gameassembly.dll` when it is loaded and writes it to the `dumped-Gameassembly.dll` file. However, BepInEx tries to load the encrypted `Gameassembly.dll` and crashes. I wish there was a way to load a binary named something other than `Gameassembly.dll`.

### Proposed solution

Support Loading an main assembly with a name other than `Gameassembly.dll`

**Comment by ghorsington** [comment]
Greetings!

Thank you for the proposal. At this moment, BepInEx supports loading both `GameAssembly.dll` and `UserAssembly.dll` as the alternative name that some games use — as such, using `UserAssembly` as the name will make BepInEx hook that DLL instead.

However, Unhollower is hardcoded to always search for `GameAssembly`, which means you'd have to edit the Unhollower to add the support for loading a custom assembly. So it's mainly up to Unhollower to support changing the DLL name.

Moreover, it seems like there is much more to it than just dumping and loading a library. Simply dumping a library and loading it won't make the game use its code unless you also modify how it loads the decrypted DLL. Instead, I would try to decrypt the DLL once, dump it and rename it to `GameAssembly` while disabling decryption logic (or rerouting the decryption handler to load the decrypted DLL instead).

**Comment by dhlrunner** [comment]
Thank you very much for your reply. I'will find another way to load the decrypted GameAssembly.
Or, is there a way to make BepInEx possibly hook memory at a specific address? Cause the game I'm trying to run seems to use CriWare's decryption function, and getting the game to use the decrypted GameAssembly doesn't seem to be an easy way.
thank you.
