### ISSUE TITLE
Time to Load Mod

### ISSUE THREAD

**Issue by HeberPcL** [BepInEx/BepInEx#367]
### Describe your problem

Hey, with the growing evolution and diversity of mods. I've been feeling the need to measure the loading time of mods. Something like the example below...

`
[Info   :   BepInEx] Loading [Example Mod 1 0.0.1] **in 25ms**

[Info   :   BepInEx] Loading [Example Mod 2 0.1.0] **in 12ms**

[Info   :   BepInEx] Loading [Example Mod 3 1.0.1] **in 45ms**
`

It would be possible? What's your opinion?

### Proposed solution

Display or loading time of each mod.

### Alternatives

n/a

**Comment by ManlyMarco** [comment]
Use startup profiler from https://github.com/BepInEx/BepInEx.Debug
