### ISSUE TITLE
Valheim Update!

### ISSUE THREAD

**Issue by 4LpHaOnE** [BepInEx/BepInEx#368]
### What happened?

Version problems occur after patching the game.
the start screen says version xx.yyy (beta)

Is this a problem with the version verification of BepInEx or is it because of the mods?

For the log-files I used a fresh installed Version plus given Modpack by our Admin!

![LoginScreen](https://user-images.githubusercontent.com/100707043/156205044-96f5be2e-b268-408a-b5cd-715c143fe77a.jpg)

[LogOutput.log](https://github.com/BepInEx/BepInEx/files/8163070/LogOutput.log)

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
Uploaded the Log file!
```

### Environment

```markdown
- OS:
(Edition Windows 10 Home
Version	21H2
Build	19044.1566
Windows Feature Experience Pack 120.2212.4170.0
)

- BepInEx:
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.17.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.2.0.0]

- Game: Valheim Patch 0.207.20
```

**Comment by 4LpHaOnE** [comment]
[Info   :   BepInEx] Loading [TombstoneSecure 1.0.0]
[Info   :   BepInEx] Loading [OdinsUndercroft 1.0.5]
[Error  : Unity Log] InvalidProgramException: Invalid IL code in (wrapper dynamic-method) Player:DMD<Player::UpdatePlacementGhost> (Player,bool): IL_0226: call      0x00000079


Stack trace:
System.RuntimeMethodHandle.GetFunctionPointer () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetFunctionPointer (System.Reflection.MethodBase method, System.RuntimeMethodHandle handle) (at <a3e7db5d9f924acea1a3fada3479a63b>:0)
MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetNativeStart (System.Reflection.MethodBase method) (at <a3e7db5d9f924acea1a3fada3479a63b>:0)
MonoMod.RuntimeDetour.DetourHelper.GetNativeStart (System.Reflection.MethodBase method) (at <a3e7db5d9f924acea1a3fada3479a63b>:0)
MonoMod.RuntimeDetour.Detour._TopApply () (at <a3e7db5d9f924acea1a3fada3479a63b>:0)
MonoMod.RuntimeDetour.Detour._RefreshChain (System.Reflection.MethodBase method) (at <a3e7db5d9f924acea1a3fada3479a63b>:0)
MonoMod.RuntimeDetour.Detour.Apply () (at <a3e7db5d9f924acea1a3fada3479a63b>:0)
MonoMod.RuntimeDetour.Detour..ctor (System.Reflection.MethodBase from, System.Reflection.MethodBase to, MonoMod.RuntimeDetour.DetourConfig& config) (at <a3e7db5d9f924acea1a3fada3479a63b>:0)
(wrapper dynamic-method) MonoMod.RuntimeDetour.ILHook+Context.DMD<MonoMod.RuntimeDetour.ILHook+Context::Refresh>(MonoMod.RuntimeDetour.ILHook/Context)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<MonoMod.RuntimeDetour.ILHook+Context::Refresh>?2097716224(object)
HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (System.Object self) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
MonoMod.RuntimeDetour.ILHook.Apply () (at <a3e7db5d9f924acea1a3fada3479a63b>:0)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
HarmonyLib.Harmony.PatchAll () (at <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0)
OdinUndercroft.OdinUndercroftPlugin.Awake () (at <0cdad6c2a1a44767a88f5a99aae8acad>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by ghorsington** [comment]
Greetings!

Based on the log you provided, the issue is outdated plugins. For example, the stack trace points to `OdinUndercroftPlugin` being amongst the mods that do not work with the new game.

I just tested base BepInEx with Valheim, and it seems to work fine:

![image](https://user-images.githubusercontent.com/13762037/156207218-ae02a355-3133-4175-babb-da537f1066e3.png)

This project GitHub is for BepInEx-specific issues. You should resolve any problems related to user-made plugins with plugin developers. I suggest removing outdated mods and contacting their developers about the game update. Most plugin developers list their contact info in their mod READMEs, and some mod developers are available in [Valheim Modding Discord](https://discord.gg/RBq2mzeu4z).

**Comment by 4LpHaOnE** [comment]
Thanks for your fast reply

**Comment by crborga** [comment]
Updating Jotunn fixed most of my mods.
