### ISSUE TITLE
BepInEx won't load on ARM architecture, with BOX86 & 64 emulators

### ISSUE THREAD

**Issue by AevumTacet** [BepInEx/BepInEx#370]
### What happened?

I been trying for a long time to get BepInEx to work on an Oracle ARM virtual instance. I was convinced that the errors reported in here before, mainly the SEGFAULT error was entirely on the emulator's side. And it seem I was right, for I was able to get rid of it by adding some BOX emulator parameters, specifically the "$BOX64_LD_PRELOAD $BOX64_NOSIGSEGV and $BOX64_LD_LIBRARY_PATH", into the launch file for the BepInEx Server. As a result, I got the launch sequence to complete, with no SEGFAULT error stopping it, and the server finally loading the world, but with no BepInEx loading, just the vanilla server.
From that point on, I find myself stranded. I'm afraid there are no more solutions I can try to get it to work, as the error preventing BepInEx from loading is on its own side. Does anyone here have a clue on what it might be? Any potential solution or workaround? Is it just an essential incompatibility with no possible fix on the BepInEx side?

### Steps to reproduce

Valheim server for Linux.

-Get an Oracle Cloud free tier account.
-Create a new virtual instance with an Ampere 4 cores & 24GB Ram shape and  Canonical Ubuntu 20.04  as image.
-Install Box86 and Box64 emulators.
-Install Steam for Linux and the Valheim dedicated server and run it to create the essential files.
-Install BepinEx by manually placing the files in the Valheim_server folder (using and FPT client).
-Open the start_server_bepinex.sh file and modify it to add the following parameters: 

export DOORSTOP_ENABLE=TRUE
export DOORSTOP_INVOKE_DLL_PATH=/home/ubuntu/valheim_server/BepInEx/core/BepInEx.Preloader.dll
export DOORSTOP_CORLIB_OVERRIDE_PATH=/home/ubuntu/valheim_server/unstripped_corlib

export LD_LIBRARY_PATH="/home/ubuntu/valheim_server/doorstop_libs:**$BOX86_LD_LIBRARY_PATH $BOX64_LD_LIBRARY_PATH**"
export BOX64_LD_PRELOAD="/home/ubuntu/valheim_server/doorstop_libs/libdoorstop_x64.so:**$BOX64_LD_PRELOAD $BOX86_NOSIGSEGV $BOX64_NOSIGSEGV**"
####
export LD_LIBRARY_PATH="/home/ubuntu/valheim_server/linux64:**$BOX86_LD_LIBRARY_PATH $BOX64_LD_LIBRARY_PATH**"
export SteamAppId=892970

exec ./valheim_server.x86_64 -nographics -batchmode -port 2456 -public 1 -name "XXXX" -world "XXXX" -password "XxXx" -savedir "/home/ubuntu/valheim_data"

-Launch the start_server_bepinex.sh file and watch as it loads a fully running vanilla server, with no trace of BepInEx working.
-Cry.

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
- OS: Cannonical Ubuntu 20.04 on Ampere ARM 4 cores, 24GB RAM, and BOX86 & 64 emulators.
- BepInEx: 5.4.19
- Game: Valheim
```

**Comment by ghorsington** [comment]
Greetings!

Thank you for the information. We already have a ticket for the issue (#336) and, as such, I'll close this as duplicate. I'll link this issue in the old ticket as this provides some initial debug info.
