### ISSUE TITLE
how do i unfuck this

### ISSUE THREAD

**Issue by Jasgjl** [BepInEx/BepInEx#371]
### What happened?

this is the line im worried about

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000055 (from typeref, class/assembly RoR2.ContentManagement.IContentPackProvider, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
```

### Environment

```markdown
- OS: Windows 10 Home
- BepInEx: latest on github
- Game: Risk of Rain 2
```

**Comment by ghorsington** [comment]
Greetings!

Based on the (very short) log snippet, the error comes from Unity and not BepInEx. If you have any plugins, it could be that some of them are causing the issue.
Risk of Rain 2 was recently updated, which broke many plugins. Moreover, the update requires additional files and plugins available via the [BepInExPack for RoR2](https://thunderstore.io/package/bbepis/BepInExPack/).

I'm closing this issue as I cannot replicate it on a clean game with stable BepInEx 5.4.19 installed. I suggest going to [Risk of Rain 2 Modding Discord](https://discord.gg/5MbXZvd) and seeking further help related to plugins and their state after the game update.
