### ISSUE TITLE
BepInEx 4.0 messes up clothes on characters created under BepInEx 3.2 or earlier

### ISSUE THREAD

**Issue by AdaBallard** [BepInEx/BepInEx#38]
**Describe the bug**
After migration to BepInEx 4.0 from 3.2 (or installing 4.0 from scratch) many characters that were created under 3.2 or earlier appear in game wearing wrong clothes or not wearing them at all. But these characters load with correct clothes in editor. 

**To Reproduce**
Load a gamesave with charactes created under Bep 3.2 or earlier and start gameplay.

**Expected behavior**
Characters should load with clothes, shown on them in editor mode (depending on current state (in school, leaving school, etc)).

**Screenshots and logs**
A person under BepInEx 3.2:
![koikatsu-2018-07-20-01-36-34](https://user-images.githubusercontent.com/18511021/42957516-46488654-8bc6-11e8-9f8f-4a311d21256d.png)

The same person from same save under BepInEx 4.0:
![koikatu 2018-07-20 01-57-54-193](https://user-images.githubusercontent.com/18511021/42958496-02c9db82-8bc9-11e8-986a-86bbd4824d75.png)

Also the console is constantly spamming with this (you can see it on the 2nd screenshot, don't know if it's an error or not):

Sideloader marker found
External info count: 0
Loading card []
Sideloader marker found
External info count: 0
Loading card []

**Desktop**
 - Game and game version: Koikatu with 06/29 cumilative update
 - BepInEx version: 4.0

**Additional context**
I can send my chara and sideloader folders if it's necessary.

**Comment by ManlyMarco** [comment]
It looks like an issue with the sideloader plugin, not BepInEx itself.
Try to apply the HF Patch v1.3.1 hotfix (only the supplied Sideloader.dll is needed) and re-save all characters that get broken now.

**Comment by AdaBallard** [comment]
Found out it wasn't BepInEx 4.0's fault.

Sorry for the late reply.

This issue can be closed now.
