### ISSUE TITLE
BepInEx logo resembles pedobear meme character

### ISSUE THREAD

**Issue by ghostlyghastly** [BepInEx/BepInEx#383]
### What happened?

The color scheme and eye shape of bepinex logo matches [pedobear's](https://en.wikipedia.org/wiki/Pedobear).

Looking at a related patreon I do realize that bepinex might mainly serve adult games modding so maybe this is intended and the team is aware of it but in case they aren't I thought I'd let them know.

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
branding
```

**Comment by ghostlyghastly** [comment]
Okie-dokie. In the past minutes I learned about Spurdo, Gondola and Wu wei.

![image](https://user-images.githubusercontent.com/61316553/159124383-cbf319c9-89a5-4c24-b818-76c073d70ecc.png)

**Comment by bbepis** [comment]
Was about to leave a comment here about it as it's probably one of the very few topics I have a PhD in, but you're correct in that it's actually [Gondola](https://knowyourmeme.com/memes/gondola). Here's a reference guide for future viewers of this issue

![guide to spurdo](https://user-images.githubusercontent.com/36346617/159124820-5d53a731-f505-4fd9-88f7-30d1fc051d4b.png)
