### ISSUE TITLE
BepInEx doesn't start for Raid Shadow Legends

### ISSUE THREAD

**Issue by jhunnius** [BepInEx/BepInEx#410]
### What happened?

I copied the contents to the folder that hosts the executable.
When I start the exe manually, the game can't log into the server.
When I start it from PLarium Play, nothing happens in BepInEx. I think the doorstep dll is ignored.

### Steps to reproduce

1. Install Plarium Play / Raid Shadow Legends
2. Copy the BepInEx content
3. Start the game

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
Nothing
```

### Environment

```markdown
- OS: Win 11
- BepInEx: 5.4.19
- Game: Raid Shadow Legends by Plarium
```

**Comment by ghorsington** [comment]
Greetings!

Reposting this from Discord, Raid Shadow Legends is using Il2Cpp runtime. For these games, you need to use BepInEx 6 the is at the moment available via [Bleeding Edge builds](https://builds.bepinex.dev/projects/bepinex_be). See [installation instructions](https://docs.bepinex.dev/master/articles/user_guide/installation/unity_il2cpp.html) for more information.

After installing and configuring BepInEx 6, it indeed seems to work with the game fine:

![image](https://user-images.githubusercontent.com/13762037/167018590-82cad56f-1472-4c21-8fa2-697fb0501e95.png)

As such, I'll close the issue for now. If you have any more problems, feel free to create a new ticket.
