### ISSUE TITLE
NEEDY GIRL OVERDOSE is don‘t working

### ISSUE THREAD

**Issue by pjy612** [BepInEx/BepInEx#418]
### What happened?

BepInEx not working with Game NEEDY GIRL OVERDOSE
not create config folder

doorstop_225bfa91.log
```
Doorstop started!
EXE Path: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose.exe
App dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE
Working dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE
STDOUT handle at 0000000000000000
Pointer to GetFinalPathNameByHandleA 00007FF843774DC0
STDOUT handle path: 
DLL Path: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\WINHTTP.dll
Doorstop DLL Name: WINHTTP
Looking for original DLL from E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\WINHTTP_alt.dll
Looking for original DLL from C:\Windows\system32\WINHTTP.dll
Proxy loaded
CONFIG: UnityDoorstop.enabled = true
CONFIG: UnityDoorstop.ignoreDisableSwitch = false
CONFIG: UnityDoorstop.redirectOutputLog = true
CONFIG: UnityDoorstop.targetAssembly = BepInEx\core\BepInEx.Preloader.dll
CONFIG: UnityDoorstop.dllSearchPathOverride = 
CONFIG: MonoBackend.runtimeLib = 
CONFIG: MonoBackend.configDir = 
CONFIG: MonoBackend.corlibDir = 
CONFIG: MonoBackend.debugEnabled = false
CONFIG: MonoBackend.debugSuspend = false
CONFIG: MonoBackend.debugAddress = 127.0.0.1:10000
ARGS: "E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose.exe" 
Config loaded
Redirected output log!
CMDLine: "E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose.exe"  -logFile "E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\output_log.txt"
Doorstop enabled!
Installing IAT hook
Hook installed!!
Got mono_jit_init_version at 00007FFFD7350000
Loaded all runtime functions
Starting Mono domain "Unity Root Domain"
STDOUT handle at 0000000000000000
STDOUT handle path: 
Setting config paths: base dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\; config path: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose.exe.config
Assembly dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose_Data\Managed
Loading assembly: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\BepInEx\core\BepInEx.Preloader.dll
Invoking method 00000130DF08F5C8
Done!

```

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
preloader_20220523_134853_537.log
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: void System.Reflection.Module.GetPEKind(System.Reflection.PortableExecutableKinds&,System.Reflection.ImageFileMachine&)
  at BepInEx.Preloader.PreloaderRunner.PreloaderPreMain () [0x00000] in <c168f36e9658474caf2ce5cde2db8d01>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <8852402bcef94a58b437b519782e3eee>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <8852402bcef94a58b437b519782e3eee>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <8852402bcef94a58b437b519782e3eee>:0 
  at BepInEx.Preloader.Entrypoint.Main () [0x0008b] in <c168f36e9658474caf2ce5cde2db8d01>:0
```

### Environment

```markdown
- OS: win10 x64
- BepInEx: 5.4.19
- Game: NEEDY GIRL OVERDOSE
```

**Comment by pjy612** [comment]
maybe the game has streamlined some class libraries

**Comment by ghorsington** [comment]
Greetings!

The game is likely shipped with stripped assemblies. Refer to ["Stripped Unity games and how to unstrip them"](https://hackmd.io/@ghorsington/rJuLdZTzK) guide for more information.

**Comment by pjy612** [comment]
> Greetings!
> 
> The game is likely shipped with stripped assemblies. Refer to ["Stripped Unity games and how to unstrip them"](https://hackmd.io/@ghorsington/rJuLdZTzK) guide for more information.

i try do it.
but had a new problem.
i don‘t find System.Native.dll

output_log.txt
```
Mono path[0] = 'E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/Managed'
Mono config path = 'E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/MonoBleedingEdge/etc'
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/System.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/MonoBleedingEdge/libSystem.Native
Initialize engine version: 2021.2.1f1 (c20c6d589440)
[Subsystems] Discovering subsystems at path E:/SteamLibrary/steamapps/common/NEEDY GIRL OVERDOSE/Windose_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 2080 Super (ID=0x1ed3)
    Vendor:   NVIDIA
    VRAM:     8010 MB
    Driver:   30.0.15.1215
Begin MonoManager ReloadAssembly
- Completed reload, in  0.059 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.754300 ms
[Steamworks.NET] SteamAPI_Init() failed. Refer to Valve's documentation or the comment above this line for more information.
Uploading Crash Report
DllNotFoundException: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <0db57d93060a4947bc33f69c868416f5>:0 
Rethrow as TypeInitializationException: The type initializer for 'Sys' threw an exception.
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <0db57d93060a4947bc33f69c868416f5>:0 
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <0db57d93060a4947bc33f69c868416f5>:0 
  at System.IO.File.Exists (System.String path) [0x00043] in <0db57d93060a4947bc33f69c868416f5>:0 
  at ES3Internal.ES3IO.FileExists (System.String filePath) [0x00000] in <588bbddbd9804acaa0637f7073b1709f>:0 
  at ES3.FileExists (ES3Settings settings) [0x0000e] in <588bbddbd9804acaa0637f7073b1709f>:0 
  at ES3.FileExists (System.String filePath) [0x00007] in <588bbddbd9804acaa0637f7073b1709f>:0 
  at ngov3.Boot.Start () [0x0004f] in <cb69b0cfabd24f978c809cf13a4f6795>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <0db57d93060a4947bc33f69c868416f5>:0 
  at UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () [0x00002] in <3b59130d41b6472bbbe3ed90f1914ec0>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x00056] in <3b59130d41b6472bbbe3ed90f1914ec0>:0 
  at UnityEngine.UnitySynchronizationContext.ExecuteTasks () [0x00014] in <3b59130d41b6472bbbe3ed90f1914ec0>:0 
```-

doorstop_2290661f.log
```
Doorstop started!
EXE Path: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose.exe
App dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE
Working dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE
STDOUT handle at 0000000000000000
Pointer to GetFinalPathNameByHandleA 00007FF843774DC0
STDOUT handle path: 
DLL Path: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\WINHTTP.dll
Doorstop DLL Name: WINHTTP
Looking for original DLL from E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\WINHTTP_alt.dll
Looking for original DLL from C:\Windows\system32\WINHTTP.dll
Proxy loaded
CONFIG: UnityDoorstop.enabled = true
CONFIG: UnityDoorstop.ignoreDisableSwitch = false
CONFIG: UnityDoorstop.redirectOutputLog = true
CONFIG: UnityDoorstop.targetAssembly = BepInEx\core\BepInEx.Preloader.dll
CONFIG: UnityDoorstop.dllSearchPathOverride = unstripped_corlib
CONFIG: MonoBackend.runtimeLib = 
CONFIG: MonoBackend.configDir = 
CONFIG: MonoBackend.corlibDir = 
CONFIG: MonoBackend.debugEnabled = false
CONFIG: MonoBackend.debugSuspend = false
CONFIG: MonoBackend.debugAddress = 127.0.0.1:10000
ARGS: "E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose.exe" 
Config loaded
Redirected output log!
CMDLine: "E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose.exe"  -logFile "E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\output_log.txt"
Doorstop enabled!
Installing IAT hook
Hook installed!!
Got mono_jit_init_version at 00007FFFD7350000
Loaded all runtime functions
Starting Mono domain "Unity Root Domain"
Current root dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose_Data\Managed
New root path: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\unstripped_corlib
Search path: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\unstripped_corlib;E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose_Data\Managed
STDOUT handle at 0000000000000000
STDOUT handle path: 
Setting config paths: base dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\; config path: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose.exe.config
Assembly dir: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\Windose_Data\Managed
Loading assembly: E:\SteamLibrary\steamapps\common\NEEDY GIRL OVERDOSE\BepInEx\core\BepInEx.Preloader.dll
Invoking method 000001933E0CE928
Error invoking code!
Error message: System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <0db57d93060a4947bc33f69c868416f5>:0 
   --- End of inner exception stack trace ---
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <0db57d93060a4947bc33f69c868416f5>:0 
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <0db57d93060a4947bc33f69c868416f5>:0 
  at System.IO.File.Exists (System.String path) [0x00043] in <0db57d93060a4947bc33f69c868416f5>:0 
  at System.TimeZoneInfo.TryLoadTzFile (System.String tzFilePath, System.Byte[]& rawData, System.String& id) [0x00000] in <0db57d93060a4947bc33f69c868416f5>:0 
  at System.TimeZoneInfo.TryGetLocalTzFile (SystDone!

```

**Comment by pjy612** [comment]
Unity version is 2021.2.1  (2021.2.1f1)
is in full library
![image](https://user-images.githubusercontent.com/4072526/169760279-c69dd1dc-b3a3-4738-8f29-04456d56b678.png)
where is this?

**Comment by pjy612** [comment]
[mscorlib.zip](https://github.com/BepInEx/BepInEx/files/8752182/mscorlib.zip)
this is Game used library.

them different

this is full
![image](https://user-images.githubusercontent.com/4072526/169762322-69bfd0c4-d324-485a-8f3e-bf7c59094f2a.png)


this is game used
![image](https://user-images.githubusercontent.com/4072526/169762553-ef92d94c-6bf5-4ba5-bb1a-6a4e46a04ca2.png)

**Comment by ghorsington** [comment]
The game probably uses older .NET 4.6 API, which requires different DLLs. In that case, you can download Unity Editor 2021.2.1 and grab the correct mscorlib etc from it. I can probably check it out later once I get some time.

The DLLs that are available on unity.bepinex.dev generally target .NET Standard API because that's more common nowadays.

**Comment by pjy612** [comment]
> The game probably uses older .NET 4.6 API, which requires different DLLs. In that case, you can download Unity Editor 2021.2.1 and grab the correct mscorlib etc from it. I can probably check it out later once I get some time.
> 
> The DLLs that are available on unity.bepinex.dev generally target .NET Standard API because that's more common nowadays.

ok, maybe  unity.bepinex.dev need have a win platform. 
i see System.Native not in windows OS ...

i'm try to download a Unity Editor 2021.2.1

**Comment by pjy612** [comment]
> The game probably uses older .NET 4.6 API, which requires different DLLs. In that case, you can download Unity Editor 2021.2.1 and grab the correct mscorlib etc from it. I can probably check it out later once I get some time.
> 
> The DLLs that are available on unity.bepinex.dev generally target .NET Standard API because that's more common nowadays.

I build with win32 it is work...

**Comment by pjy612** [comment]
maybe need 

2021.2.1f1c1\Editor\Data\MonoBleedingEdge\lib\mono\unityjit-win32

**Comment by xDaswx** [comment]
> Greetings!
> 
> The game is likely shipped with stripped assemblies. Refer to ["Stripped Unity games and how to unstrip them"](https://hackmd.io/@ghorsington/rJuLdZTzK) guide for more information.

Thanks!
