### ISSUE TITLE
BaseUnityPlugin got destroyed after awake, can't use update / onGUI

### ISSUE THREAD

**Issue by nmanhei** [BepInEx/BepInEx#420]
### What happened?

"Start()", "Update()" and "OnGUI()" didn't get called ,
Found out the plugin class got destroyed .

### Steps to reproduce

1. create a plugin with UnityEngine.Debug.Log inside Awake(), Update() and OnDestroy()
2. add it into the plugin folder and run it
3. read the log as the plugin got destroyed, update() never get called

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
[Message:   BepInEx] BepInEx 5.4.11.0 - Craftopia
[Info   :   BepInEx] Running under Unity v2022.1.0.9261453
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MultiFolderLoader 1.1.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :MultiFolderLoader] Loading preloader patchers from mod
[Info   :MultiFolderLoader] Loading 0 preloader patchers from mods...
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :MultiFolderLoader] Finding plugins from mods...
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [CraftopiaBepinExDemo 0.0.1]
[Info   :   BepInEx] Loading [ShowItemChest Plug-In 1.0.0.7]
[Message:   BepInEx] Chainloader startup complete
[Message:   BepInEx] BepInEx 5.4.11.0 - Craftopia
[Info   :   BepInEx] Running under Unity v2022.1.0.9261453
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MultiFolderLoader 1.1.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :MultiFolderLoader] Loading preloader patchers from mod
[Info   :MultiFolderLoader] Loading 0 preloader patchers from mods...
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :MultiFolderLoader] Finding plugins from mods...
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [CraftopiaBepinExDemo 0.0.1]
[Info   : Unity Log] CraftopiaBepinExDemo DontDestroyOnLoad
[Info   : Unity Log] CraftopiaBepinExDemo SetParent(null)
[Info   : Unity Log] CraftopiaBepinExDemo Awake
[Info   : Unity Log] CraftopiaBepinExDemo OnEnable
[Info   :   BepInEx] Loading [ShowItemChest Plug-In 1.0.0.7]
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] CraftopiaBepinExDemo OnDisable
[Info   : Unity Log] CraftopiaBepinExDemo OnDestroy
[Info   : Unity Log] OcUI_HomeScene.OnUnityAwake
[Info   : Unity Log] VersionInt=205192016
[Info   : Unity Log] IsAdmin = True
[Info   : Unity Log] OcSteamworkHander:OnUnityAwake
[Info   : Unity Log] [Steamworks.NET] SteamAPI_Init() success.
[Info   : Unity Log] NetLog:<color=#7fff00>[CLT]OcNetMng.setJoinState:NotConnect</color>:Frame=0
[Info   : Unity Log] NetLog:<color=cyan>[SVR]OcNetMng.setServerState: SrvState=Default joinWaitNetPlId=-1</color>:Frame=0
[Info   : Unity Log] Initialize UniTask.MainThreadDispatcher
[Info   : Unity Log] OcUI_HomeScene.Start
```

### Environment

```markdown
- OS: windows10
- BepInEx: 5.4.11.0
- Game: Craftopia
```

**Comment by Eradev** [comment]
I can confirm that those three methods are no longer called in the last two stable versions of Craftopia.

1) I used the Logger, and it doesn't work.

2) Seems to work; I can see the calls being made. Although I'm not sure what that option does?

**Comment by Eradev** [comment]
From an old log file I found, it seems the Unity version has changed. Is it that the new version is not supported?

```
[Message:   BepInEx] BepInEx 5.4.16.0 - Craftopia (2021-12-23 2:49:37 AM)
[Info   :   BepInEx] Running under Unity v2020.3.8.5273881
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.16.0]
```

**Comment by ghorsington** [comment]
> 2. Seems to work; I can see the calls being made. Although I'm not sure what that option does?

The option marks the BepInEx plugin manager object as hidden from the Unity scene, which prevents the game from deleting it. This is useful for some games that do manual extremely aggressive scene cleanup at the early stages of the game. Some games also use this approach as a rudimentary anti-cheat/anti-modding measure. It's impossible to know for sure without analysing the game code.

Another option would be to adjust the entry point, but I have not modded Craftopia to know the appropriate entry point for it.

> Is it that the new version is not supported?

Seems like it is working fine. If it wasn't supported, setting `HideManagerGameObject` would not help either.

All in all, it seems that in the newer versions of the game you should enable this option. Alternatively, you can locate a better entry point for the game or find the code that does early aggressive scene cleanup.

**Comment by nmanhei** [comment]
> Greetings!
> 
> Please try the following:
> 
> 1. Use BepInEx's own `Logger` instance instead of Unity's. For example, instead of `UnityEngine.Debug.Log` you can use `Logger.LogInfo`. `Logger` is a property provided by `BaseUnityPlugin`.
> 2. You can try setting `HideManagerGameObject = true` in BepInEx.cfg. If you don't have that option in the config, update your BepInEx version
> 
> The first step is to rule out `Debug.Log` not being logged (this can happen in some games). The second option is to test that the MonoBehaviour is really being destroyed. The second case is extremely rare, so it's better first to test logging.

changing the HideManagerGameObject works fine, thank you

**Comment by LovelyA72** [comment]
Is it possible for BepinEx to send out an alert (to logger or something) about the deletion of the node?
