### ISSUE TITLE
when Game use UnityEngine.InputSystem, BepinEx hotkeys are not available

### ISSUE THREAD

**Issue by pjy612** [BepInEx/BepInEx#434]
### What happened?

Bepinex hotkeys are not available
Log send Error
![image](https://user-images.githubusercontent.com/4072526/175761136-57db6861-60c0-4e1c-bbfc-9af9d483260a.png)

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
[Error  : Unity Log] InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
```

### Environment

```markdown
- OS: win10
- BepInEx: 5.4.19.0
- Game: 20MinuteTillDawn
```

**Comment by pjy612** [comment]
I learned that the game may use UnityEngine.InputSystem;
Now I adjust to
```
 void Update()
        {
            //if (ShowCounter.Value.IsDown())
            if (Keyboard.current.f7Key.isPressed)
            {
                DisplayingWindow = !DisplayingWindow;
            }
            UpdateData();
        }
```
Hope to be compatible in the future

**Comment by pjy612** [comment]
@ghorsington

**Comment by ghorsington** [comment]
Support for using Unity.InputSystem in KeyboardShortcuts was added in 5.4.20 via #444. Closing this issue as completed.

**Comment by JoewAlabel** [comment]
I am having the same problem with BepInEx 6.0.0-be.665.

My code:

```
public static ConfigEntry<KeyboardShortcut> InfiniteStamHotKey { get; set; }
void Awake()
{
InfiniteStamHotKey = configFile.Bind("Hotkeys", "InfiniteStamHotKey", new KeyboardShortcut(KeyCode.Keypad4, KeyCode.LeftAlt));
}

if (InfiniteStamHotKey.Value.IsDown())
{
	infiniteStam = !infiniteStam;
 
	 if (infiniteStam == false)
	{
		Logger.LogInfo($"Infinite Stam Disabled!");
	}
	else
	{
		Logger.LogInfo($"Infinite Stam Enabled!");
        }
}
```
The error:
```
[Error  : Unity Log] InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
```

This code work, but i can not find a way to allow users set the keys using KeyboardShortcut():
```
if (Keyboard.current[Key.LeftAlt].isPressed)
{
    if (Keyboard.current[Key.Digit4].wasPressedThisFrame)
    {
        //Log.LogInfo("Keys Pressed!");
    }
}
```

Can you tell me how I make it work, please?
Thank you!!!!

**Comment by ManlyMarco** [comment]
Looks like the fix wasn't merged into the main branch yet.

**Comment by pjy612** [comment]
> Looks like the fix wasn't merged into the main branch yet, you can use 5.x if you don't need IL2Cpp support to avoid the issue.

Do you know anything about @ghorsington? Has something happened to him? He's been gone for six months, by the looks of things.
