### ISSUE TITLE
fail to generate i12cpp interop assemlies

### ISSUE THREAD

**Issue by JJflywuhu** [BepInEx/BepInEx#437]
### What happened?

First i use R2 install BeplnEx 2.0,the game is run un and the control manual just not show up. THEN I renew the game document and manually Installa,then control manual show up but not working and close immediately.
![Desktop Screenshot 2022 07 02 - 23 28 45 33 (2)](https://user-images.githubusercontent.com/89703015/177008239-1168097e-f390-4c4b-86d8-69e05f6adaa9.png)
.

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Environment

```markdown
- OS: windows 10 21H1
- BepInEx:2.0.0 (based on BepInEx PR #391) BREAKING
Unhollower has been replaced with Il2CppInterop
The Mono runtime has been replaced with CoreCLR which means plugins can now be compiled for .NET 6
- Game: gtfo
```

**Comment by ghorsington** [comment]
Greetings!

Please try the following:

1. Download [dotnet.zip](https://github.com/BepInEx/BepInEx/files/9033306/dotnet.zip)
2. Go to `dotnet` folder that is inside GTFO folder
3. Extract the ZIP you downloaded into the `dotnet` folder. Overwrite when asked.
4. Run the game again

Please also send a screenshot of your `dotnet` folder after you have completed the steps.

**Comment by JJflywuhu** [comment]
IT WORK!!!! Thanks a lot!!!!! I Manually install  BeplnEx 2.0 and overwrite the folder,and the mod is working too! THIS is the screensho of new /donet . THANKS again!! >_<
![1656866025880](https://user-images.githubusercontent.com/89703015/177048848-8981af7f-c792-4345-befb-d2d3cc14805c.png)

**Comment by ghorsington** [comment]
This should now be properly fixed for the latest Bleeding Edge builds, although GTFO BepInExPack might take a while to update. Closing this issue for now as fixed based on my tests
