### ISSUE TITLE
目前BepInEx不支持unity2021.2.x、Unity2021.3.x系列的所有IL2CPP的交互，请问官方何时能支持呀？

### ISSUE THREAD

**Issue by guochaolinDLKF** [BepInEx/BepInEx#457]
### Describe your problem

目前BepInEx不支持unity2021.2.x、Unity2021.3.x系列的所有IL2CPP的交互，请问官方何时能支持呀？

### Proposed solution

目前BepInEx不支持unity2021.2.x、Unity2021.3.x系列的所有IL2CPP的交互，请问官方何时能支持呀？

**Comment by ghorsington** [comment]
Greetings!

Unity 2021 and 2022 are indeed not fully supported at the moment. The support relies on Il2CppInterop and not BepInEx. There is already an issue related to Unity 2021-2022 (#455), so I'll close this as duplicate.
