### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by zoli456** [BepInEx/BepInEx#460]
### What happened?

Why BepInEx doesnt load the translator?

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
https://pastebin.com/0k3U03s2
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: 5.4.21.0 
- Game: Awakening Remastered The Dreamless Castle
```

**Comment by ghorsington** [comment]
Greetings!

One common reason for ` Illegal byte sequence encounted in the input.` is when your game is located in a path with non-ASCII characters (i.e. anything other than A-z and 0-9), see #407. The current workaround is to move the game to a path that doesn't include any special character.s
