### ISSUE TITLE
Plugins do not load

### ISSUE THREAD

**Issue by JoewAlabel** [BepInEx/BepInEx#464]
### What happened?

Created the project from template (BepInEx 6 ll2Cpp Plugin Template)  using Visual Studio and .NET 6.0 (.NET Standard 2.1)
Added all references, packages.
Compiled.
Copied DLL to Plugins folder.

Mod is not detected and it is not loaded.

How fix it, please?
ty!
 ```[Message: Preloader] BepInEx 6.0.0-be.648 - Rune Factory 5
[Message: Preloader] Built from commit b41697c34a83a69986527cfd665402560b4d60ad
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2019.4.17f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
```

### Steps to reproduce

1- Created the project from template (BepInEx 6 ll2Cpp Plugin Template)  using Visual Studio and .NET 6.0 (.NET Standard 2.1)
2- Added all references, packages.
3- Compiled.
4- Copied DLL to Plugins folder.
5- Started the game.

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.648 - Rune Factory 5
[Message: Preloader] Built from commit b41697c34a83a69986527cfd665402560b4d60ad
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2019.4.17f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
```

### Environment

```markdown
- OS: Windows 11
- BepInEx: Bleeding Edge BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.649+78b5b58
- Game: Rune Factory 5
```

**Comment by ghorsington** [comment]
Greetings!

Latest BE builds have a different project setup from 6.0.0-pre.1 (and -be.5xx builds). Because of this, just switching the target framework does not suffice. You have a few options:

* Stay on 6.0.0-pre.1 as it is currently locked in feature set
* Convert your project to use the latest BE builds. This involves removing **all** package references and re-adding new ones. For example, for Il2Cpp, the new package name is `BepInEx.Unity.IL2CPP`
* Use new [BepInEx.Templates v2.0.0-be.1](https://github.com/BepInEx/BepInEx.Templates/releases/tag/v2.0.0-be.1) template package made for the new BE builds. The documentation is not yet done, but it should be up in a day or two

**Comment by JoewAlabel** [comment]
> Greetings!
> 
> Latest BE builds have a different project setup from 6.0.0-pre.1 (and -be.5xx builds). Because of this, just switching the target framework does not suffice. You have a few options:
> 
>     * Use new [BepInEx.Templates v2.0.0-be.1](https://github.com/BepInEx/BepInEx.Templates/releases/tag/v2.0.0-be.1) template package made for the new BE builds. The documentation is not yet done, but it should be up in a day or two
> 
> 
> If you still have problems, please send over a minimal plugin for which you are able to replicate the issue.

Idk which pass i missed, but i did all again sing the template and worked as indeed!
Thank you very much!!!!

**Comment by BlueFalconHD** [comment]
I am facing the same issue. I am using BepInEx from https://github.com/BepInEx/BepInEx/commit/6b500b35727716f8ba182dedae304a628dbbb608 (BepInBuilds 6b500b3) and the new BE templates. The game is Mono x64 on macOS. No plugin will load. Custom ones, or things like unity explorer.

The log is:
```
[Message: Preloader] BepInEx 6.0.0-be.665 - Sasquatch
[Message: Preloader] Built from commit 6aabdb5ff9500fca541dbd66df7fbd7fe1dacd78
[Info   :   BepInEx] System platform: macOS Unknown (kernel 22.3.0.0) 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   : Preloader] Running under Unity 2020.3.17f1
[Info   : Preloader] CLR runtime version: 4.0.30319.17020
[Info   : Preloader] Supports SRE: False
[Message: Preloader] Preloader started
[Info   :AssemblyPatcher] Loaded 1 patcher type from [BepInEx.Unity.Mono.Preloader 6.0.0.0]
[Info   : Preloader] 1 patcher plugin loaded
[Info   : Preloader] 117 assemblies discovered
[Message:AssemblyPatcher] Executing 1 patch(es)
[Message: Preloader] Preloader finished
2023-04-16 13:23:20.643 Sasquatch[9618:359525] (null) preferred device: Apple M2 (high power)
2023-04-16 13:23:20.643 Sasquatch[9618:359525] Metal devices available: 1
2023-04-16 13:23:20.643 Sasquatch[9618:359525] 0: Apple M2 (high power)
2023-04-16 13:23:20.643 Sasquatch[9618:359525] Using device Apple M2 (high power)
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Current Language: English
```

and my directory structure is:
```
BepInEx
├── config
│   └── BepInEx.cfg
├── core
│   ├── 0Harmony.dll
│   ├── AssetRipper.VersionUtilities.dll
│   ├── BepInEx.Core.dll
│   ├── BepInEx.Core.xml
│   ├── BepInEx.Preloader.Core.dll
│   ├── BepInEx.Preloader.Core.xml
│   ├── BepInEx.Unity.Common.dll
│   ├── BepInEx.Unity.Common.xml
│   ├── BepInEx.Unity.Mono.Preloader.dll
│   ├── BepInEx.Unity.Mono.Preloader.xml
│   ├── BepInEx.Unity.Mono.dll
│   ├── BepInEx.Unity.Mono.xml
│   ├── Mono.Cecil.Mdb.dll
│   ├── Mono.Cecil.Pdb.dll
│   ├── Mono.Cecil.Rocks.dll
│   ├── Mono.Cecil.dll
│   ├── MonoMod.RuntimeDetour.dll
│   ├── MonoMod.Utils.dll
│   └── SemanticVersioning.dll
├── patchers
└── plugins
    ├── MyFirstPlugin.dll
    ├── UnityExplorer.BIE6.Mono.dll
    └── UniverseLib.Mono.dll
```

And the game directory/where the game is located is this:
```
drwxrwxr-x@ 7    224 BepInEx
drwxr-xr-x  8    256 MyFirstPlugin
drwxr-xr-x@ 3     96 Sasquatch.app
-rw-rw-r--@ 1  54176 libdoorstop.dylib
-rwxrw-r--@ 1   8338 run_bepinex.sh
```
