### ISSUE TITLE
BepInEx 3.0.0 (Based on BepInEx 6.0.0-be.648) fails to boot [GTFO]

### ISSUE THREAD

**Issue by Aceolu** [BepInEx/BepInEx#466]
### What happened?

Ever since the latest update for BepInEx for GTFO on Thunderstore, the game is unable to boot modded.

All that happens is an window pop-up that just displays "Failed to start BepInEx" along with creating a preloader log which has the following:
[preloader_20220819_145305_263.log](https://github.com/BepInEx/BepInEx/files/9384699/preloader_20220819_145305_263.log)

BepInEx was updated using the r2modmanager, and verifying the game's files, reinstalling the game, reinstalling the modmanager. 
Installing the same version of BepInEx manually into the game's steam folder outside of r2modmanager does allow the game to boot regularly, but does not allow any usage of r2modmanager's features.

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
Unfortunately this error does not give me a log output.
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: 6.0.0.0
- Game: GTFO
```

**Comment by ghorsington** [comment]
Greetings!

BepInEx indeed seems to work fine with a normal install following the [manual installation guide in the package's README](https://gtfo.thunderstore.io/package/BepInEx/BepInExPack_GTFO/). Issues with loading in r2modman seem to be related to r2modman itself; I cannot even start the game via r2modman.

I suggest taking it up to r2modman devs as basic BepInEx installation works fine. I'll close this down for now as unrelated to base BepInEx.
