### ISSUE TITLE
Can we get an isolated version of Sideloader?

### ISSUE THREAD

**Issue by mrwallace888** [BepInEx/BepInEx#494]
### Describe your problem

I've found like 2 or more versions of BepInEx's Sideloader for specific Unity games such as H3VR but I can't find a version of Sideloader that's its own separate thing that works for any game.

On another note, I tried using H3VR's Sideloader on other Unity games and sometimes it works, but there's a couple games I've tried such as Ravenfield and The Long Drive where it seems to initialize Sideloader and load "1 mod" (a test mod replacing an asset or more in the games) like normal but nothing changes in-game.

### Proposed solution

Just making a separate version of Sideloader as part of BepInEx.

**Comment by ghorsington** [comment]
Greetings!

Unfortunately, this is very unlikely to be possible to implement a general-purpose Sideloader with a feature set expected from such a plugin.

Different modding communities have a different understanding of "sideloading". However, broadly based on my observations of various plugins in various communities, sideloaders are plugins that solve the general problem of *loading common in-game resources* while abstracting away the process of setting up necessary game logic. Replacing existing resources is generally just one of the features, but more important is adding new resources with as little scripting as possible. For example

* Illusion games have various Sideloader plugins to load new items into the game. Each game has a slightly different codebase and architecture, so each game has its separate sideloader.
* Outward has a Sideloader plugin that provides asset loading and API for interacting with the game. Again, they interact with the game itself to get assets loaded incorrectly.
* H3VR has OtherLoader + Stratum, which works together to load new weapons, maps and items into the game. This requires accessing the game API to provide proper sideloading. The original H3VR Sideloader, in this sense, is much more limited; in fact, the idea was to add proper new weapon loading into it before Deli managed to do it first and much better.

To provide a good clean experience for modders, you will generally have to touch the game code. This is more of a job for each modding community than core BepInEx, and as such, I do not see this as actionable by us.

Based on your description, however, I think what you are probably asking for is an *asset replacer*. For that, there is a general-purpose solution: check out [XUnity.AutoTranslator](https://github.com/bbepis/XUnity.AutoTranslator) (yes, really). While XUAT itself provides only basic asset replacement, for the sake of translations, you can use its [resource redirection API](https://github.com/bbepis/XUnity.AutoTranslator#implementing-a-resource-redirector) to implement a more general-purpose asset replacement. You should be able to make some asset replacement, though it still won't work for assets that aren't dynamically loaded or are loaded in some very obscure manner (for that, you'd have to again go deep into the game's code). Even then, I don't think this is something that should be included in core BepInEx. Instead, we keep the core lean and provide API to expand it via plugins.

All in all, I don't see this as something actionable by us. Feel free to check out XUAT and potentially make a general asset replacer.
