### ISSUE TITLE
FEMDOM WIFE GAME - ZOE (dont work with this game)

### ISSUE THREAD

**Issue by ivann142** [BepInEx/BepInEx#512]
### What happened?

Dont work with this game with all versions

[preloader_20221114_165323_596.log](https://github.com/BepInEx/BepInEx/files/10003595/preloader_20221114_165323_596.log)

Checked using two versions (ofc not in same time)

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
- OS: Windows
- BepInEx: 5.4.21 and 6.0.0-be.663+5796f53
- Game: FEMDOM WIFE GAME - ZOE
```

**Comment by TheLounger** [comment]
Hi there,

This game seems to ship with **stripped assemblies**. After following this guide I was able to make it work: https://hackmd.io/@ghorsington/rJuLdZTzK
Let us know if you this solves your issue 👍

![FWG_Unstripped](https://user-images.githubusercontent.com/4087076/201725881-07fcde8d-a837-4e52-ab14-747188284256.png)

**Comment by ivann142** [comment]
Thanks, I will inform my friend about this and give an answer later.

**Comment by ivann142** [comment]
As my friend told me game start but BepInEx + XUnity Auto Translator still dont work (game dont create any translation)
