### ISSUE TITLE
Cannot identify executable type (got )!

### ISSUE THREAD

**Issue by tebbeh-dev** [BepInEx/BepInEx#526]
### What happened?

When i put the (executable_name="valheim_server.x86_64") and chmod the run_bepinex on my Debian server this is the result. 

Its fresh install both server and bepinex.
![image](https://user-images.githubusercontent.com/46937387/206908975-09e78c73-ac8b-4d1e-98d5-b046a5d27641.png)

Also server runs without any problems without BepInEx.
What did i miss?

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
Dont know how to get logging really. I dont think i get that far.
```

### Environment

```markdown
- OS: Debian GNU/Linux 10 (buster)
- BepInEx: Latest stable
- Game: Latest from SteamCMD
```

**Comment by ghorsington** [comment]
Greetings!

Judging from the message (specifically the `file: not found`), your server install is probably missing `file` program. For Debian-based distros that don't have it installed by default, you should be able to `apt-get install file` to install it.

**Comment by tebbeh-dev** [comment]
> Greetings!
> 
> Judging from the message (specifically the `file: not found`), your server install is probably missing `file` program. For Debian-based distros that don't have it installed by default, you should be able to `apt-get install file` to install it.

You were 100% correct, im sorry for this. Basic linux knowledge. Thanks!
