### ISSUE TITLE
BepInEx 6-pre.1 plugin not detect (IXION)

### ISSUE THREAD

**Issue by hsinyu-chen** [BepInEx/BepInEx#542]
### What happened?

installed BepInEx 6-pre.1
and use dotnet new bep6plugin_unity_il2cpp create project
build project to Dll
copy dll to BepInEx\plugins
but not detect by BepInex

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-pre.1 - Ixion
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   : Preloader] Running under Unity v2021.2.6
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
Setting breakpad minidump AppID = 1113120
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198004157263 [API loaded no]
```

### Environment

```markdown
- OS: Windows 11 pro 64
- BepInEx: BepInEx_UnityIL2CPP_x64_6.0.0-pre.1_2
- Game: IXION
```

**Comment by Windows10CE** [comment]
The template for pre1 is `bep6plugin_il2cpp`, not `bep6plugin_unity_il2cpp`. The one you used is for the latest bleeding edge builds instead of pre1.

**Comment by hsinyu-chen** [comment]
> The template for pre1 is `bep6plugin_il2cpp`, not `bep6plugin_unity_il2cpp`. The one you used is for the latest bleeding edge builds instead of pre1. I believe you might have to downgrade the installed templates to get it though?

thanks for your time,  I instead downgrade the template but upgrade BepInEx to pre.665 , now it detect my plugin normally
