### ISSUE TITLE
Crashes when starting the game

### ISSUE THREAD

**Issue by DamonSayks** [BepInEx/BepInEx#575]
### What happened?

I checked the launch with disabling all plugins, except BepInEx  - does not work...
I checked the launch without the plugin BepInEx - it works!

I checked the launch with inly plugin BepInEx - does not works!
Error is always the same..

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
[Message:   BepInEx] BepInEx 5.4.21.0 - valheim (17.03.2023 21:52:45)
[Info   :   BepInEx] Running under Unity v2020.3.41.8133084
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 6 plugins to load
[Info   :   BepInEx] Loading [PlantEverything 1.13.3]
[Info   :   BepInEx] Loading [ServerSideMap 1.3.7.0]
[Info   :ServerSideMap] Store1: False
[Info   :ServerSideMap] Store2: False
[Info   :   BepInEx] Loading [Sailing 1.1.5]
[Info   : Unity Log] 03/18/2023 14:36:44: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 03/18/2023 14:36:44: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 03/18/2023 14:36:44: Loaded localization file #0 - 'localization' language: 'Russian'
[Info   : Unity Log] 03/18/2023 14:36:44: Loaded localization file #1 - 'localization_extra' language: 'Russian'
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.1]
[Info   :   BepInEx] Loading [Equipment and Quick Slots 2.1.2]
[Info   :   BepInEx] Loading [MassFarming 1.5]
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] 03/18/2023 14:36:49: Starting to load scene:start
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 03/18/2023 14:36:52: Using environment steamid ******
[Info   : Unity Log] 03/18/2023 14:36:52: Using steam APPID:***
[Info   : Unity Log] 03/18/2023 14:36:53: Authentication:k_ESteamNetworkingAvailability_Attempting
[Info   : Unity Log] 03/18/2023 14:36:53: Steam initialized, persona:****
[Info   : Unity Log] 03/18/2023 14:36:53: PlayFab custom ID set to "Steam_****"
[Info   : Unity Log] 03/18/2023 14:36:53: Using default prefs
[Info   : Unity Log] 03/18/2023 14:36:53: Valheim version:0.214.300
[Info   : Unity Log] 03/18/2023 14:36:53: Worldgenerator version setup:2
[Info   : Unity Log] 03/18/2023 14:36:53: Render threading mode:MultiThreaded
[Warning: Unity Log] 03/18/2023 14:36:53: Missing audio clip in music respawn
[Info   : Unity Log] 03/18/2023 14:36:53: Checking for installed DLCs
[Info   : Unity Log] 03/18/2023 14:36:53: DLC:beta installed:False
[Error  : Unity Log] GetPixel called on an undefined mip (valid values are 0 - 6
```

### Environment

```markdown
- OS: Windows 10 x64
- BepInEx: 5.4.2100
- Game: Valheim 0.214.300
```

**Comment by moddedNoob** [comment]
Im getting a similar error. Game stars when removing the BepInEx folder. Putting it back breaks the game on startup. 
Deleting the content of the plugin-folder / removing all mods (confimed by log: "0 plugins to load") won't make difference.
The same error happens with 2 of my friends that have the same mod setup. They are on win 11.

[Player.log](https://github.com/BepInEx/BepInEx/files/11012084/Player.log)

- OS: Windows 10 x64
- BepInEx: 5.4.2100
- Game: Valheim 0.214.300

**Comment by toddlersizedsharkcage** [comment]
There's a newer version available on the BepInEx Discord which fixed this for me:
https://discord.com/channels/623153565053222947/624272422295568435/1088135732574556160

You can also find it by joining the Discord server at https://discord.gg/MpFEDAg and looking for the post by Azumatt in #bepinex-issues posted two days ago.

**Comment by DamonSayks** [comment]
> There's a newer version available on the BepInEx Discord which fixed this for me: https://discord.com/channels/623153565053222947/624272422295568435/1088135732574556160
> 
> You can also find it by joining the Discord server at https://discord.gg/MpFEDAg and looking for the post by Azumatt in #bepinex-issues posted two days ago.

Thanks!
It's working for me

**Comment by toddlersizedsharkcage** [comment]
Damn, realizing now that patch is if you're using the public test version of Valheim.  Shouldn't be needed if you're using the official current release.

**Comment by DamonSayks** [comment]
> Damn, realizing now that patch is if you're using the public test version of Valheim. Shouldn't be needed if you're using the official current release.

Ooh, you're right! I didn't say I had a test patch enabled

**Comment by secure-the-code** [comment]
make sure in Steam you don't have valheim'beta' selected. It will do this for sure with mods if you do.
