### ISSUE TITLE
Config entries being orphaned

### ISSUE THREAD

**Issue by RyanHx** [BepInEx/BepInEx#584]
### What happened?

I'm making a plugin that lets the user assign a label to an object and saving their input using the plugin's `Config`:

``` c#
input = GUILayout.TextField(input);
if (GUILayout.Button("Submit"))
{
    Plugin.ConfigInstance.TryGetEntry(
        $"World.{guid}",
        storageIndex.ToString(),
        out ConfigEntry<string> entry
    );
    if (entry != null)
    {
        entry.Value = input;
    }
    else
    {
        Plugin.ConfigInstance.Bind($"World.{guid}", storageIndex.ToString(), input);
    }
    this.enabled = false;
}
```

I have `SaveOnConfigSet` set to true and tried a couple of test submissions which saved to the config file successfully:
```
[World.51cec5e8-76b4-4926-a00c-f3f936d14233]
# Setting type: String
# Default value: 1234
18890 = 1234

# Setting type: String
# Default value: test2
18887 = test2
```

When the player later hovers their crosshair over this object I hook the method that gets the "Interact" HUD text and add their label to it:
``` c#
Plugin.ConfigInstance.TryGetEntry(
    $"World.{guid}",
    boxIndex.ToString(),
    out ConfigEntry<string> entryMaybe
);
if (entryMaybe != null && !entryMaybe.Value.IsNullOrEmpty())
{
    __result += $"\n{entryMaybe.Value}";
}
```

All of this works fine **during a single play session**. However when I restart the game the `Entries` property inside the `ConfigFile` is empty, and both entries have been moved to `OrphanedEntries`. How can I prevent this from happening? I read that entries are only orphaned if `Bind` isn't called on them, but I use that method to create them and they're saved, should they not be loaded back into `Entries` the next time I start the game? Since all the values are set at runtime I can't `Bind` everything inside my plugin `Awake` method, so I'm not sure how to keep them 'active' so to speak. Any help would be greatly appreciated!

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
N/A - config operations aren't logged and no errors are shown.
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: 5.4.21
- Game: Raft
```

**Comment by RyanHx** [comment]
Currently working around this via reflection:

``` c#
private void Update()
{
    var orphans = Traverse.Create(Config).Property("OrphanedEntries").GetValue<Dictionary<ConfigDefinition, string>>();
    if (orphans != null)
    {
        foreach(var kvp in orphans)
        {
            Config.Bind(kvp.Key, kvp.Value);
        }
    }
}
```
Not sure if there's a better way.

**Comment by ManlyMarco** [comment]
This is intended, you have to Bind the setting to move it out of the OrphanedEntries list.

**Comment by RyanHx** [comment]
Thanks for the reply! Yeah I might switch over to serializing it myself, I was just wondering if I'd missed something in the docs before making any big changes. My UI is just a text field and cancel/submit buttons to get the input at the moment, no management going on. Thanks again :)
