### ISSUE TITLE
Cannot read property target Assembly of undefined

### ISSUE THREAD

**Issue by Sergey5588** [BepInEx/BepInEx#595]
### What happened?

I have a problem with doorstop_config.ini
"Cannot read property target Assembly of undefined" when I try to run Risk of Rain 2 (Epic games) via r2modman 
I searched the entire Internet and did everything in my power
I even completely removed r2modman
this happened after I upgraded BebInEx to version 5.4.2106 
reinstalling didn't help

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
Error
Failed to update doorstop_config.ini
Cannot read property 'targetAssembly' of undefined   //moded


Error
Failed to update doorstop_config.ini
Cannot read property 'enabled' of undefined  //vanilla
```

### Environment

```markdown
- OS: Windows 10 Pro 22H2
- BepInEx: 5.4.2107 now but this happened after I upgraded BepInEx to version 5.4.2106
- Game: Risk of Rain 2
```

**Comment by xiaoxiao921** [comment]
This is an issue with r2modman (epic game store + doorstop4 only) and a fix is coming soon™

**Comment by Sergey5588** [comment]
> This is an issue with r2modman (epic game store + doorstop4 only) and a fix is coming soon™
very thx
