### ISSUE TITLE
Package not exist

### ISSUE THREAD

**Issue by NikoCat233** [BepInEx/BepInEx#650]
### What happened?

What is Samboy063.Cpp2IL.Core v2022.1.0-development.866 ?
This version litterly doesnt exist!
My complier thought the newest version 2022.0.7.2 is older than it and won't accept it.

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
- OS: 
- BepInEx: 
- Game:
```

**Comment by JieGeLovesDengDuaLang** [comment]
You can add the package source of Samboy

`nuget.samboy.dev/v3/index.json`

**Comment by NikoCat233** [comment]
Sorry I didnt close this
I solved this myself =(
