### ISSUE TITLE
BepInEx 6 (Bleeding Edge) : Crashes after Setup

### ISSUE THREAD

**Issue by dlbuhtig4096** [BepInEx/BepInEx#671]
### What happened?

The game crashes after BepInEx setup the chain loader.
The game was `Megaman X Dive Offline`, it was made with Unity 2020.3.41, and the main il2cpp library was packed by the Enigma Protecter.
I have unpacked the library and everything worked so far without BepInEx.

If I disable the `UnityLogListening` in `BepInEx/config/BepInEx.cfg`, then the game would be able to boot up successfully.
However, after installing the [Unity Explorer](https://locoserver.net/dl/unityexplorer_bie6.zip), the game still crashed.

The exception code I got with `UnityLogListening` enabled was `0xC0000374`, which stands for heap corruption.
Possibly related to [#474](https://github.com/BepInEx/BepInEx/issues/474), however the warning message was different.

The below log was from a boot with Unity Explorer.

### Steps to reproduce

1. Install BepInEx
2. Run the game
3. Observe the normal assembly generation process after which you get a warning about `GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool` and crashes right after `Chainloader startup complete`.

### BepInEx Distribution

Bleeding Edge from BepisBuilds

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.674 - Game
[Message: Preloader] Built from commit 82077ec7c91c97f0e5f8ada5d178fd7ece6c0099
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2020.3.41f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [UnityExplorer 4.9.0]
[Message:UnityExplorer] UnityExplorer 4.9.0 initializing...
[Message:UnityExplorer] [UniverseLib] UniverseLib 1.5.1 initializing...
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[Message:UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Warning:Il2CppInterop] GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool
[Info   :Il2CppInterop] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[Message:UnityExplorer] Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[Message:   BepInEx] Chainloader startup complete
```

### Environment

```markdown
- OS: Win 11 64-bits, also tested with Win 10 64-bits
- BepInEx: Bleeding Edge
- Game: Megaman X Dive Offline
```

**Comment by SutandoTsukai181** [comment]
This is probably related to Il2CppInterop, not BepInEx

I did a `git bisect` and it turns out the issue is related to this commit: https://github.com/BepInEx/Il2CppInterop/commit/4ef3f4ab25ab26c58e87a0c5cbfd7e1f8e0777d8

The issue was fixed when I rebased at https://github.com/BepInEx/Il2CppInterop/commit/63c7407e71f0c11ccd0a7b33fbfeb72ec944a0dc (latest master) without these 2 commits: [4ef3f4a](https://github.com/BepInEx/Il2CppInterop/commit/4ef3f4ab25ab26c58e87a0c5cbfd7e1f8e0777d8), [c589498](https://github.com/BepInEx/Il2CppInterop/commit/c5894986709bb88f12b24e4302b6a8176beff16c)

**Comment by dlbuhtig4096** [comment]
> This is probably related to Il2CppInterop, not BepInEx
> 
> I did a `git bisect` and it turns out the issue is related to this commit: [BepInEx/Il2CppInterop@4ef3f4a](https://github.com/BepInEx/Il2CppInterop/commit/4ef3f4ab25ab26c58e87a0c5cbfd7e1f8e0777d8)
> 
> The issue was fixed when I rebased at [BepInEx/Il2CppInterop@63c7407](https://github.com/BepInEx/Il2CppInterop/commit/63c7407e71f0c11ccd0a7b33fbfeb72ec944a0dc) (latest master) without these 2 commits: [4ef3f4a](https://github.com/BepInEx/Il2CppInterop/commit/4ef3f4ab25ab26c58e87a0c5cbfd7e1f8e0777d8), [c589498](https://github.com/BepInEx/Il2CppInterop/commit/c5894986709bb88f12b24e4302b6a8176beff16c)

Thanks. Could verify the game crashing issue got fixed without that commit.
Il2CppInterop still complained about `GarbageCollector::RunFinalizer not found, disabling Il2CppObjectPool` without crashing the game, so it seems not related to the garbage collection.
Maybe I will open an issue there, or you are going to report it?

**Comment by dlbuhtig4096** [comment]
Okay.
