### ISSUE TITLE
Valheim v0.217.22 The interface broke after the update of BepInEx - BepInEx 5.4.2200

### ISSUE THREAD

**Issue by RyaxnDev** [BepInEx/BepInEx#684]
### What happened?

I recently wrote that the new version of Valheim does not run on Bepinex version 5.4.2105. Today, a new version 5.4.22 was released, which I installed to replace the old one, but now the interface in the game does not work for me.

Here is a list of mods that I use:
![image](https://github.com/BepInEx/BepInEx/assets/66675705/8b9f3478-4c38-47d1-9199-0232dff6784a)
![image](https://github.com/BepInEx/BepInEx/assets/66675705/8a9b5910-c450-44da-83a1-bd48ca9613d2)
![image](https://github.com/BepInEx/BepInEx/assets/66675705/2e2b6563-e6e5-471a-acfa-36fb33173e76)

### BepInEx Distribution

Stable from GitHub

### Log outputs

![image](https://github.com/BepInEx/BepInEx/assets/66675705/e71cccc5-32b7-4afe-b34a-b6994036c09c)

```txt
[Error  : Unity Log] MissingMethodException: void Terminal/ConsoleCommand..ctor(string,string,Terminal/ConsoleEvent,bool,bool,bool,bool,bool,Terminal/ConsoleOptionsFetcher,bool)
Stack trace:
(wrapper dynamic-method) Terminal.DMD<Terminal::InitTerminal>()
(wrapper dynamic-method) Terminal.DMD<Terminal::Awake>(Terminal)
Console.Awake () (at <19c5e9736483495da0c4e300eb98ab45>:0)
UnityEngine.Object:Instantiate(GameObject)
FejdStartup:DMD<FejdStartup::Awake>(FejdStartup)

[Error  : Unity Log] MissingMethodException: ZInput/ButtonDef ZInput.AddButton(string,string,bool,single,single,bool,bool)
Stack trace:
JotunnLib.Patches.ZInputPatches+ResetPatch.Postfix (ZInput& __instance) (at <61e64fc53d134a03961a0b92bf808613>:0)
(wrapper dynamic-method) ZInput.DMD<ZInput::Reset>(ZInput)
ZInput..ctor () (at <aee0a26989e0479f9222199f259798da>:0)
(wrapper dynamic-method) ZInput.DMD<ZInput::Initialize>()
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Awake>(FejdStartup)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Localization.GetBoundKeyString (System.String bindingName, System.Boolean emptyStringOnMissing) (at <cf2fd99b8a1344b3abcf2804ea60ee5c>:0)
Localization.Translate (System.String word) (at <cf2fd99b8a1344b3abcf2804ea60ee5c>:0)
Localization.Localize (System.String text) (at <cf2fd99b8a1344b3abcf2804ea60ee5c>:0)
Localization.Localize (UnityEngine.Transform root) (at <cf2fd99b8a1344b3abcf2804ea60ee5c>:0)
Localize.Start () (at <cf2fd99b8a1344b3abcf2804ea60ee5c>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) ZInput.DMD<ZInput::GetButtonDown>(string)
UIGamePad.ButtonPressed () (at <19c5e9736483495da0c4e300eb98ab45>:0)
UIGamePad.Update () (at <19c5e9736483495da0c4e300eb98ab45>:0)
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: 5.4.22
- Game: Valheim
```

**Comment by BlessMyCode** [comment]
same here. how to fix plz

**Comment by Doodz59** [comment]
Same here, 
Got a unknown character named Ragnar, when switch to other character he dissapear but can't launch the game. 
Work fine in Vanilla. Since my few addon recquire BepinEx, can't launch the game as modded, only in vanilla.

![ragnar](https://github.com/BepInEx/BepInEx/assets/99396435/15fda556-be20-4607-8906-90f7b55b66ae)

got this error : [Error  : Unity Log] MissingFieldException: Field 'FejdStartup.m_connectionFailedError' not found.
Stack trace:
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::ShowConnectError>(FejdStartup,ZNet/ConnectionStatus)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

Used to have all the log error as [RyaxnDev](https://github.com/RyaxnDev) before I turn down the majority of my mods

**Comment by BlessMyCode** [comment]
its not a bapinex error, try to disable all mod except bepinex

**Comment by RyaxnDev** [comment]
> its not a bapinex error, try to disable all mod except bepinex

I can assume that some of my mods do not support the new version of bepinex at the moment, so this error comes out.

**Comment by Tdue21** [comment]
> its not a bapinex error, try to disable all mod except bepinex

It's EquipmentAndQuickSlots by RandyKnapp (may of course be others as well).

**Comment by RyaxnDev** [comment]
> > its not a bapinex error, try to disable all mod except bepinex
> 
> It's EquipmentAndQuickSlots by RandyKnapp (may of course be others as well).

I turned it off and nothing has changed, maybe it's the mods for the interface

**Comment by RyaxnDev** [comment]
[SOLVED] JotuhnLib doesn't support new BepInEx
