### ISSUE TITLE
Steam Overlay won't open

### ISSUE THREAD

**Issue by grundyboy34** [BepInEx/BepInEx#69]
**Describe the bug**
Steam overlay no longer opens, and can't be focused if opened via invite button.

**To Reproduce**
Install BebInEx. Attempt to open overlay, or press invite button in a lobby to open it (won't be able to interact or close)

**Desktop (please complete the following information):**
 - BebInEx 1.3

**Comment by denikson** [comment]
Greetings!

Could you provide more information? What game are you using BepInEx on? I assume it's Risk of Rain 2, judging from the version 1.3 (which is the current version of BepInEx modpack for that game, not the version of BepInEx itself).

Are you running the game directly or launching it via Steam? From my tests it seems to work when the game is launched directly via Steam (and not by running the EXE directly):

![confirm](https://user-images.githubusercontent.com/13762037/55995468-3d634100-5cbd-11e9-99c9-fb06b0012fd9.png)

The overlay seems to appear and be responsive in all game GUIs.

**Comment by grundyboy34** [comment]
Yeah, Risk of Rain 2, launched from Steam. I'm on Windows 10, so idk if it's a compatibility issue, but trying to load any of the plugins I could find also caused visible errors for BebInEx preloading. 
This bug however, happens with other without plugins so I just had to remove it for now.

**Comment by denikson** [comment]
Would you mind sharing these error messages? In fact, please post any errors you get right in the first message in the future, as per the issue template. Knowing exact errors usually helps us a lot with providing correct support.

You can either copy the errors from the console, take a screenshot, or send the whole `output_log.txt` here (you can usually find the file in `C:/users/UserName/AppData/LocalLow/CompanyName/ProductName`).

**Comment by grundyboy34** [comment]
Seems to be working no in 1.3.1

**Comment by denikson** [comment]
Fair enough. If you do have any other problems related to BepInEx, please create another issue.

In addition, I suggest first asking help from the game's modding community (as it is the one that creates custom packs of BepInEx). In case of RoR2, the [Mod Developers Discord](https://discord.gg/TY9y9XJ) is one potential place to ask for help.
