### ISSUE TITLE
Improved Translation.txt file.

### ISSUE THREAD

**Issue by SiTWulf** [BepInEx/BepInEx#7]
Hi. (English is not my native language).

This is a Improved translation.txt file:
[translation.txt](https://github.com/bbepis/BepInEx/files/1734911/translation.txt)

Changes:
Improvement some long descriptions with short texts.
Improvement translation of some text, for example Questions, join points, etc.
Uppercase first letter in some texts.

**Comment by geneishouko** [comment]
Hi there. Thank you for your contribution! Can you add some description of the changes you made to the text?

**Comment by SiTWulf** [comment]
Yeah.

**Comment by denikson** [comment]
Closing to the old age of the issue.

If you have any other questions/suggestions regarding Koikatsu plug-ins, consider posting them in [BepisPlugins](https://github.com/bbepis/BepisPlugins) repository.
