### ISSUE TITLE
SteamDeck Can't Run UNIX script

### ISSUE THREAD

**Issue by myxxmikeyxx** [BepInEx/BepInEx#706]
### What happened?

I tried running the unix script in run_bepinex.sh on my steamdeck to create the config file.
I followed the directions and added the exe name into the script but I am getting these error:
bash ./run_bepinex.sh

./run_bepinex.sh: line 8: $'\r': command not found

./run_bepinex.sh: line 11: $'\r': command not found

./run_bepinex.sh: line 16: $'\r': command not found

./run_bepinex.sh: line 18: $'\r': command not found

./run_bepinex.sh: line 21: $'\r': command not found

./run_bepinex.sh: line 24: $'\r': command not found

./run_bepinex.sh: line 28: $'\r': command not found

./run_bepinex.sh: line 31: $'\r': command not found

./run_bepinex.sh: line 50: syntax error near unexpected token `$'in\r''

'/run_bepinex.sh: line 50: `case $os_type in

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
no logs, scripts wont run.
```

### Environment

```markdown
- OS: SteamOS 3.4.11
- BepInEx: 5.4.22
- Game: Lethal Company
```

**Comment by toebeann** [comment]
This will be the case for many UNIX users of 5.4.22 due to the \r\n EOL in run_bepinex.sh - should be fixed in #700 

In the meantime, run this command in terminal in the folder of the run_bepinex.sh script:

```sh
dos2unix run_bepinex.sh
```

It will convert the file line endings for you.

If you don't have `dos2unix` command available in your shell, you can try `tr`:

```sh
echo "$(tr -d '\r' < run_bepinex.sh)" > run_bepinex.sh
```

**Comment by myxxmikeyxx** [comment]
Thank you I will try it and close if it works!

**Comment by myxxmikeyxx** [comment]
Well it worked but I have to use the Wine/Proton version.
Just one thing after another XD

`/run/media/mmcblk0p1/steamapps/common/Lethal Company/Lethal Company.exe
The executable is a Windows executable file. You must use Wine/Proton and BepInEx for Windows with this executable.
Uninstall BepInEx for *nix and install BepInEx for Windows instead.
More info: https://docs.bepinex.dev/articles/advanced/steam_interop.html#protonwine
`
