### ISSUE TITLE
unity mod manager

### ISSUE THREAD

**Issue by GamearooCodes** [BepInEx/BepInEx#740]
### Describe your problem

can run bepinex mods with unity mod manager mods

### Proposed solution

make a bersion for unity mod manager

### Alternatives

if there is a way to run both id like to know other wise it would be nice to have unity mod manager support since most mods use that ao i can use multiscreen mod ontop of route manager instead of having to chose which one i want more

**Comment by ju5tA1ex** [comment]
UnityModManager has installation method "Assembly". It can be used when need to use both loaders.
