### ISSUE TITLE
Game is crashing

### ISSUE THREAD

**Issue by abyx01** [BepInEx/BepInEx#77]
Game is crashing when there are any plugins in the plugins folder.

**Desktop (please complete the following information):**
 - Game is Minion Masters, x86. I think it's using NET 3.5, Unity 2018.3.4f1
 - BepInEx version 5.0, both stable and bleeding edge

[LogOutput.log](https://github.com/BepInEx/BepInEx/files/3170931/LogOutput.log)

**Comment by denikson** [comment]
Greetings!

Judging from the log, you are trying to use plugins that are not meant to be used with Minion Masters.  
My guess is that you tried to download and install BepisPlugins. Most of those plugins, however, are only for Koikatsu. Moreover, the plugins in BepisPlugins are meant for BepInEx 4.0 and not 5.0.

If you need plugins for Minion Masters, I suggest looking them elsewhere. Or even better, make them: I'm pretty sure there are people who would like seeing some plugins for Minion Masters.

**Comment by abyx01** [comment]
Oh sorry haven't realised that plugins are game-specifis. Thanks for an answer, everything is working now.😺
