### ISSUE TITLE
BepinEx Errors with Risk on Rain 2 

### ISSUE THREAD

**Issue by dynamiicRaft** [BepInEx/BepInEx#80]
**Description**
Whenever I start the modded client of Risk of Rain 2, I get an error message which causes my game not being able to use steamoverlay and the mod not working either. This does not imply when I start RoR2 without any mods, but with BepinEx, but the moment one mod is installed it goes haywire.

**Reproduction**
Installing a mod, any mod of a kind. Excluding BepinEx. The error refers to the com.bepis.r2api.cfg which is responsible for being able to match with modded clients online. But putting that from true to false wont help.

**Log** *Error highlighted*
[Message:   MonoMod] [Main] Scanning for mods in directory.
[Message:   MonoMod] [ReadMod] Loading mod dir: D:\Games\steamapps\common\Risk of Rain 2\BepInEx\monomod
[Message:   MonoMod] [Main] mm.PatchRefs(); fixup pre-pass
[Message:   MonoMod] [Main] mm.AutoPatch();
[Message:   MonoMod] [AutoPatch] Parsing rules in loaded mods
[Message:   MonoMod] [AutoPatch] PrePatch pass
[Message:   MonoMod] [AutoPatch] Patch pass
[Message:   MonoMod] [AutoPatch] PatchRefs pass
[Message:   MonoMod] [PostProcessor] PostProcessor pass #1
[Message:   MonoMod] [Main] Done.
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 / 1 plugins to load
**[Error  :   BepInEx] Missing the following dependencies for [ItemStats]:- com.bepis.r2api
Loading will be skipped; expect further errors and unstabilities.**
[Message:   BepInEx] Chainloader startup complete
Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Setting breakpad minidump AppID = 632360
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198377159403 [API loaded no]

**Desktop:**
 - Game and game version : Risk of Rain 2; The Scorched Acres update (26-06-2019)
 - BepInEx version : BepinEx 5.0 RCI

**Edit**
The problem with steamoverlay also showed up with BepinEx installed without mods, so I deleted BepinEx, but forgot to look at error messages

**Comment by denikson** [comment]
Greetings!

The error is pretty self-explanatory: ItemStats depends on another plug-in that you are missing.

In this case, `com.bepis.r2api` is the GUID for [R2API](https://thunderstore.io/package/tristanmcpherson/R2API/) that you need to have properly installed in order for the plug-in to work. Judging by the fact that BepInEx detects only one plug-in, you either have R2API installed incorrectly or simply missing.

For more precise technical support I suggest inquiring about the issue in RoR2 community. For instance, the [Mod Developer Discord](https://discord.gg/TY9y9XJ) has people that can provide you sufficient technical support related to using BepInEx in Risk of Rain 2.

**Comment by dynamiicRaft** [comment]
Thanks for the quick reply,

The errors are fixed thanks, I didn't notice R2API was missing. I assumed it came with BepInEx automatically, atleast that what it used to do.
