### ISSUE TITLE
Could not run preloader

### ISSUE THREAD

**Issue by SupertytanPL** [BepInEx/BepInEx#82]
![image](https://user-images.githubusercontent.com/52862400/61173925-f32e7c00-a599-11e9-995f-b238e39215fd.png)

Thats the error

Please help me

**Comment by SupertytanPL** [comment]
[preloader_20190713_183030_594.log](https://github.com/BepInEx/BepInEx/files/3388991/preloader_20190713_183030_594.log)



I reinstaled BepInEx and in game folder this appears

**Comment by SupertytanPL** [comment]
After restarting my pc problem from my first comment comes up

**Comment by denikson** [comment]
Closing the issue because of it being old. Seeing as this is a RoR2 related issue, you should instead get the [official BepInEx pack for RoR2](https://thunderstore.io/package/bbepis/BepInExPack/).

If you still have any issues, feel free to create a new issue.
