### ISSUE TITLE
Life is Strange: Before the Storm Crashing

### ISSUE THREAD

**Issue by bc15kle** [BepInEx/BepInEx#84]
Hello, I don't understand how to make bepinex work with this unity game (5.5.3f1), I tried assembly patcher since it's on a unity 5 version, but it made the game crashing 

"cri_ware_unity.dll caused an Access Violation (0xc0000005)
  in module cri_ware_unity.dll at 0033:ac33e3c0."

and when loading it directly without the patcher it does load the game, but bepinex itself doesn't work.
I want to try and load this plugin: https://github.com/ManlyMarco/RuntimeUnityEditor
Please, I need help, thank you.

**Comment by bbepis** [comment]
Hi, sorry for the delay in the response.

I've personally downloaded the game and checked for myself what works.

The assembly patcher is considered deprecated and shouldn't be used for platforms other than Windows for the time being. The Doorstop entrypoint has been ported to Linux and Mac OSX so it is planned to port those platforms to use Doorstop too, meaning that the patcher will only be used for fringe platforms like Android or ARM.

The 5.0 RC1 version, x64 Legacy build of BepInEx should work out of the box with this game. You can download it from here: https://github.com/BepInEx/BepInEx/releases/tag/v5.0-RC1

Install it by drag and dropping it into the game's directory, where winhttp.dll is extracted next to the game .exe.

Please let me know if you run into any more issues. Unity v5.X is known to potentially have issues with loading plugins while using the default entrypoint.

**Comment by bc15kle** [comment]
Yea the game's weird, u can't even use a realtime glitch software on it. The game has most of its content (cutscenes, script nods to storyforge) obfuscated, but stuff like basic gameplay control isn't. It did seem to work like it loaded the plugin

"[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 / 1 plugins to load
[Info: BepInEx] Loading [Runtime Unity Editor 1.5]
[Message:   BepInEx] Chainloader startup complete"

but pressing f12 in-game still shows nothing. Guess I should contact the guy who made the plugin from this point onward, right? 


Thanks for your help.

**Comment by denikson** [comment]
Closing this because it was moved to ManlyMarco/RuntimeUnityEditor#2.
If you do have any other problems, feel free to create a new issue.
