### ISSUE TITLE
BepInEx Console Reports “0 Plugins to Load” Not Detecting The Plugins In The Folder

### ISSUE THREAD

**Issue by BoxCarNibbo** [BepInEx/BepInEx#854]
### What happened?

Despite having plugins in the designated folder, the BepInEx console incorrectly shows that no plugins are available for loading. Not only that, Theres multiple plugins in that folder, so it shouldn't be the plugin itself. No error reports in the console, and no warnings.

 

### Steps to reproduce

Install BepInEx

Put In Plugins

Open The Game

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
[Message: Preloader] BepInEx 6.0.0-be.688 - Comedy Night
[Message: Preloader] Built from commit 49015217f3becf052d33fa4658ac19229f5daa3a
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.19f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
```

### Environment

```markdown
- OS: Windows 11
- BepInEx: BepInEx x64 5.4.22.0
- Game: Comedy Night
```

**Comment by toebeann** [comment]
> - BepInEx: BepInEx x64 5.4.22.0

> [Message: Preloader] BepInEx 6.0.0-be.688 - Comedy Night

so, if you downloaded the latest bleeding edge bepinex 6, but your plugins are for bepinex 5 (or even an earlier build of bepinex 6), then they aren't going to work on the latest bleeding edge bepinex 6.

where did you get the mods from?

**Comment by BoxCarNibbo** [comment]
> > * BepInEx: BepInEx x64 5.4.22.0
> 
> > [Message: Preloader] BepInEx 6.0.0-be.688 - Comedy Night
> 
> BepInEx 6 is unstable (still in development) and is not backwards compatible with mods for BepInEx 5. The latest bleeding edge builds of BepInEx 6 aren't even backwards compatible with mods for earlier builds of BepInEx 6.
> 
> So, if you downloaded the latest bleeding edge BepInEx 6, but your plugins are for a completely different version of BepInEx, then they aren't going to work on the version of BepInEx you downloaded. In other words, this isn't going to be a bug, It's going to be user error. The solution would be to just install the correct version of BepInEx for the mods you want to use.
> 
> Where did you get the mods from? If you can link me to the mods, I can tell you exactly which version of BepInEx they require. From googling around, I can't find any BepInEx mods for Comedy Night.


I got the mods from these:

https://www.youtube.com/watch?v=qufWSNPyeYQ&t=18s&ab_channel=VTVRVXIV

and

https://github.com/sinai-dev/UnityExplorer

**Comment by toebeann** [comment]
So, the mods from the video are probably not going to work. They would need to be updated to work with latest BepInEx 6 bleeding edge. From the links in the video they haven't been updated in 2 years. And because the game is using Unity 2022, you do need to use latest bleeding edge BepInEx 6.

But you can use UnityExplorer with the version of BepInEx you have, there is an updated version here that should work: https://github.com/yukieiji/UnityExplorer/releases/latest/download/UnityExplorer.BepInEx.Unity.IL2CPP.CoreCLR.zip

**Comment by BoxCarNibbo** [comment]
> So, the mods from the video are probably not going to work. They would need to be updated to work with latest BepInEx 6 bleeding edge. From the links in the video they haven't been updated in 2 years. And because the game is using Unity 2022, you do need to use latest bleeding edge BepInEx 6.
> 
> But freecam is included in UnityExplorer, and you don't need IsDebugBuild with newer versions of BepInEx 6, since it comes with doorstop 4 which already lets you attach a debugger. So, you don't need the mods from the video, you just need UnityExplorer.
> 
> To use UnityExplorer with the version of BepInEx you have, there is an updated version here that should work: https://github.com/yukieiji/UnityExplorer/releases/latest/download/UnityExplorer.BepInEx.Unity.IL2CPP.CoreCLR.zip
> 
> (Assuming you installed this build of BepInEx 6: https://builds.bepinex.dev/projects/bepinex_be/688/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.688%2B4901521.zip)

ok so now it detects unity the explorer plugin. thank you so much for helping me.
