### ISSUE TITLE
not mallware

### ISSUE THREAD

**Issue by nickythegreaty** [BepInEx/BepInEx#936]
### What happened?

mallware

### Steps to reproduce

mallware

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
- OS: 
- BepInEx: 
- Game:
```

**Comment by ayoGrox** [comment]
It isnt malware💀

**Comment by moxie-coder** [comment]
it's open source software you retarded dunce

**Comment by ayoGrox** [comment]
Goddamn Dumbass aint got IQ ppl use it to mod steam games that have Unity💀
