### ISSUE TITLE
bepinex nuget server is down

### ISSUE THREAD

**Issue by jshepler** [BepInEx/BepInEx#976]
### What happened?

On the off chance you weren't already aware, https://nuget.bepinex.dev/ is down

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
n/a
```

### Environment

```markdown
- OS: n/a
- BepInEx: n/a
- Game: n/a
```

**Comment by bobg9** [comment]
looks like https://unity.bepinex.dev is also down

**Comment by Flourek** [comment]
Pls fix :(
