### ISSUE TITLE
Not working ?

### ISSUE THREAD

**Issue by Nekotje** [BepInEx/BepInEx#985]
### What happened?

i copied the linux x64 in the game map set the permissions and added the commandline for steam. When i start the game via steam it starts but not making an config map.
WHen i run ./run_bepinex.sh im getting an error

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
/.steam/debian-installation/steamapps/common/Travellers Rest/Windows/TravellersRest.exe" is not compiled for x86 or x64 (might be ARM?)
If you think this is a mistake (or would like to encourage support for other architectures)
Please make an issue at https://github.com/NeighTools/UnityDoorstop
Got: PE32+ executable (GUI) x86-64, for MS Windows
```

### Environment

```markdown
- OS: Pop-os 22
- BepInEx: 5.4.23.2 
- Game: Travellers Rest
```

**Comment by toebeann** [comment]
It's a Windows game running through emulation with proton, so you need to use the Windows version of BepInEx, not the Linux version. The Linux version is for games built natively for Linux.

So, uninstall the version you installed, put in the appropriate Windows version, and just set your launch options to:
```
WINEDLLOVERRIDES="winhttp=n,b" %command%
```

And you should be set.

**Comment by Nekotje** [comment]
> It's a Windows game running through emulation with proton, so you need to use the Windows version of BepInEx, not the Linux version. The Linux version is for games built natively for Linux.
> 
> So, uninstall the version you installed, put in the appropriate Windows version, and just set your Steam launch options for the game to:
> 
> ```
> WINEDLLOVERRIDES="winhttp=n,b" %command%
> ```
> 
> And you should be set. Launch the game from Steam as normal and it should all just work™️.

Thank you this is now seems to work. 
 
I did try the windows version but the Steam command i was missing i didn't see that anywhere mentioned.

**Comment by toebeann** [comment]
Yeah it's the easiest way, there is an alternative method that also works which is listed in the docs here: https://docs.bepinex.dev/articles/advanced/proton_wine.html
