### ISSUE TITLE
AmbiguousMatchException: Ambiguous match found

### ISSUE THREAD

**Issue by jojorne** [BepInEx/BepInEx#99]
**Describe the bug**

Patching a class constructor that has a static constructor throws AmbiguousMatchException like:
```csharp
public class Test
{
    static Test() { }
    public Test() { }
}
```

**To Reproduce**

Two scenarios:

1. [HarmonyPostfix, HarmonyPatch(typeof(Test), MethodType.Constructor)]
2. [HarmonyPostfix, HarmonyPatch(typeof(Test), ".ctor", MethodType.Constructor)]

**Expected behavior**

From scenarios:
1. The method name is not set, so methodName is always null thus skipping the method: x.declaringType != null && x.methodName != null
2. Now the name is set, but HarmonyWrapper.GetOriginalMethod(harmonyMethod) internally uses AccessTools.allDeclared which has the BindingFlags.Static which will get the static constructor and throw the AmbiguousMatchException

**Additional context**

Any MethodType enum has its name not set unless manually specified with the Attribute.

**Proposed fix**

From scenarios:
1. Try to set the methodName for each MethodType enum when null
2. In HarmonyWrapper.GetOriginalMethod(HarmonyMethod attribute) the case for MethodType.Constructor should be:
return AccessTools.GetDeclaredConstructors(attribute.declaringType).FirstOrDefault((ConstructorInfo c) => !c.IsStatic && c.GetParameters().Select(p => p.ParameterType).SequenceEqual(attribute.argumentTypes));

**Comment by bbepis** [comment]
Hi,
Thanks for the PR. I've just merged it, as it seems to be working great.
However I wanted to ask about manually adding `".ctor"` as the name of the constructor.
Is this needed, even after the PR? From what I understand, typical Harmony usage doesn't need the name of the constructor specified, only the `MethodType.Constructor` enum.

**Comment by jojorne** [comment]
https://github.com/BepInEx/BepInEx.Harmony/blob/779067e980cd56d2b8d4bc80b870570aff2f5995/BepInEx.Harmony/HarmonyWrapper.cs#L56
Yes, in this line "x.methodName is null" and will never pass unless you use:
[HarmonyPostfix, HarmonyPatch(typeof(Test), ".ctor", MethodType.Constructor)]
